"""Handcrafted question vs no-question pairs pb0601–pb0700."""
from __future__ import annotations

PAIRS = []


def add(n, text_a, qs_a, text_b, *, note_a, note_b, da="e", db="h", amb_b=False):
    PAIRS.append({
        "n": n, "boundary": "question/no_question",
        "a": {"text": text_a, "difficulty": da, "amb": False, "contrast": note_a,
              "note": f"pair pb{n:04d}: {note_a}",
              "qs": qs_a},
        "b": {"text": text_b, "difficulty": db, "amb": amb_b, "contrast": note_b,
              "note": f"pair pb{n:04d}: {note_b}",
              "qs": []},
    })


# --- code / syntax `?` ---
add(601, "The handler uses a nested ternary that obscures the null case:\n\n```js\nconst label = err ? (err.code ? err.code : 'unknown') : 'ok';\n```\n\nWant me to rewrite this as an early return?", [{"kind": "y", "propose": True, "prompt": "Want me to rewrite this as an early return?"}], "The handler uses a nested ternary that obscures the null case:\n\n```js\nconst label = err ? (err.code ? err.code : 'unknown') : 'ok';\n```\n\nI'll flatten the branches next unless you prefer keeping the ternary.", note_a="closing asks user to authorize rewrite -> yes_no/propose", note_b="hard: `?` only inside JS ternary expressions in code block")
add(602, "TypeScript flagged `profile.email` because `profile` may be undefined after the fetch.\n\nCould you paste the exact compiler error line?", [{"kind": "o", "prompt": "Could you paste the exact compiler error line?"}], "TypeScript flagged `profile.email` because `profile` may be undefined after the fetch.\n\nA guard like `profile?.email?.trim()` should satisfy the checker once we wire it in.", note_a="asks user for pasted error text -> open", note_b="hard: `?` only in optional chaining `profile?.email?.trim()`")
add(603, "The deploy script exited non-zero but the log ends before the failing command.\n\nShould I rerun `./scripts/deploy.sh` with `set -x`?", [{"kind": "y", "propose": True, "prompt": "Should I rerun `./scripts/deploy.sh` with `set -x`?"}], "The deploy script exited non-zero but the log ends before the failing command.\n\nLast line in CI was `echo exit=$?` — that only tells us the shell status, not which step failed.", note_a="asks approval to rerun deploy with tracing -> yes_no/propose", note_b="hard: `?` only in bash `$?` exit-status idiom")
add(604, "`BirthDate` is nullable in the API model but the form always sends a value.\n\nWant me to change `DateTime?` to a required `DateTime` in the DTO?", [{"kind": "y", "propose": True, "prompt": "Want me to change `DateTime?` to a required `DateTime` in the DTO?"}], "`BirthDate` is nullable in the API model but the form always sends a value.\n\nThe serializer already accepts `DateTime?`; making it required would break clients that omit the field.", note_a="asks user to approve schema tightening -> yes_no/propose", note_b="hard: `?` only in C# nullable type `DateTime?`", da="m")
add(605, "The docs link in the email template still points at the old path.\n\nWhich landing page should open first — `/docs` or `/docs?topic=quickstart`?", [{"kind": "e", "prompt": "Which landing page should open first \u2014 `/docs` or `/docs?topic=quickstart`?", "opts": ["/docs", "/docs?topic=quickstart"]}], "The docs link in the email template still points at the old path.\n\nI'll default the CTA to `https://app.example.com/docs?topic=quickstart` unless product wants the bare `/docs` page.", note_a="asks user to pick between two URLs -> either_or", note_b="hard: `?` inside URL query string, not an addressed question", da="m")
add(606, "Slow query log shows a full table scan on `events`.\n\n```sql\nSELECT * FROM events WHERE user_id = ?;\n```\n\nShall I add a concurrent index on `user_id`?", [{"kind": "y", "propose": True, "prompt": "Shall I add a concurrent index on `user_id`?"}], "Slow query log shows a full table scan on `events`.\n\n```sql\nSELECT * FROM events WHERE user_id = ?;\n```\n\nThe placeholder syntax is fine; the missing index is the real problem.", note_a="asks approval to add index -> yes_no/propose", note_b="hard: `?` only as SQL placeholder in code fence")
add(607, "We need a mapped type that strips nullables from nested keys.\n\nWhich approach do you prefer — `T extends U ? X : Y` or a helper `NonNullableDeep<T>`?", [{"kind": "e", "prompt": "Which approach do you prefer \u2014 `T extends U ? X : Y` or a helper `NonNullableDeep<T>`?", "opts": ["`T extends U ? X : Y`", "a helper `NonNullableDeep<T>`"]}], "We need a mapped type that strips nullables from nested keys.\n\nConditional types like `T extends U ? X : Y` read cleanly for one level; deep null stripping usually wants a recursive helper.", note_a="asks user to choose between two TS patterns -> either_or", note_b="hard: `?` inside conditional type syntax, not addressed to user", da="m")
add(608, "Kotlin NPE on `session.user.email` when auth cookies expire mid-request.\n\nCan you share the stack trace from staging?", [{"kind": "o", "prompt": "Can you share the stack trace from staging?"}], "Kotlin NPE on `session.user.email` when auth cookies expire mid-request.\n\nUsing `session.user?.email` at the call site prevents the crash once we land the patch.", note_a="asks user for stack trace -> open", note_b="hard: `?` only in Kotlin safe-call `user?.email`")
add(609, "The retry helper treats `0` as falsy and skips backoff.\n\nWant me to replace `attempts ? delayMs : 0` with an explicit `attempts > 0` check?", [{"kind": "y", "propose": True, "prompt": "Want me to replace `attempts ? delayMs : 0` with an explicit `attempts > 0` check?"}], "The retry helper treats `0` as falsy and skips backoff.\n\nThe bug is the ternary `attempts ? delayMs : 0`, not the delay constant itself.", note_a="asks approval to fix falsy check -> yes_no/propose", note_b="hard: `?` inside ternary comparing numeric attempt count")
add(610, "Regex lint wants escaping on the optional group in the slug validator.\n\nShould I change `/^[-a-z0-9]+(?:\\.[a-z0-9]+)?$/i` to a possessive form?", [{"kind": "y", "propose": True, "prompt": "Should I change `/^[-a-z0-9]+(?:\\.[a-z0-9]+)?$/i` to a possessive form?"}], "Regex lint wants escaping on the optional group in the slug validator.\n\nThe pattern `/^[-a-z0-9]+(?:\\.[a-z0-9]+)?$/i` already allows an optional dotted suffix — we only need clearer comments, not a new engine feature.", note_a="asks approval to adjust regex -> yes_no/propose", note_b="hard: `?` only inside regex quantifier `(?:...)?`", da="m")

# --- rhetorical / quoted ---
add(611, "Hotfix branch is still open after the cherry-pick landed on `main`.\n\nDo you want me to delete `hotfix/rate-limit` now?", [{"kind": "y", "propose": True, "prompt": "Do you want me to delete `hotfix/rate-limit` now?"}], "Hotfix branch is still open after the cherry-pick landed on `main`.\n\nWhy keep `hotfix/rate-limit` around? The fix is already on `main` and CI is green.", note_a="asks approval to delete branch -> yes_no/propose", note_b="hard: rhetorical 'Why keep…?' answered in the same turn")
add(612, "Merge queue paused because the required check never went green.\n\nShould I squash the last three commits before retrying?", [{"kind": "y", "propose": True, "prompt": "Should I squash the last three commits before retrying?"}], "Merge queue paused because the required check never went green.\n\nDo we need three commits for a one-line fix? No — a single commit will re-run the same checks faster.", note_a="asks approval to squash -> yes_no/propose", note_b="hard: self-answered rhetorical question ('Do we need three commits…? No —')")
add(613, "Feature flag `billing_v2` is at 100% but code paths still read legacy tables.\n\nWant me to remove the legacy reader this week?", [{"kind": "y", "propose": True, "prompt": "Want me to remove the legacy reader this week?"}], "Feature flag `billing_v2` is at 100% but code paths still read legacy tables.\n\n**What's blocking cleanup?** Nothing technical — we simply haven't deleted the old adapter yet.", note_a="asks approval to remove legacy reader -> yes_no/propose", note_b="hard: bold heading question immediately answered by assistant")
add(614, "Pre-release build numbers drifted between Android and iOS.\n\nCan you confirm which build should be tagged `1.8.0-rc.1`?", [{"kind": "o", "prompt": "Can you confirm which build should be tagged `1.8.0-rc.1`?"}], "Pre-release build numbers drifted between Android and iOS.\n\nIs RC tagging urgent? Given store review lead time, yes — we should align both platforms today.", note_a="asks user to confirm tag target -> open", note_b="hard: rhetorical urgency question answered in same paragraph", da="m")
add(615, "Support pasted the customer thread; the last message reads:\n\n> Can you restore my deleted project by EOD?\n\nWhich restore path should I use — snapshot or point-in-time?", [{"kind": "e", "prompt": "Which restore path should I use \u2014 snapshot or point-in-time?", "opts": ["snapshot", "point-in-time"]}], "Support pasted the customer thread; the last message reads:\n\n> Can you restore my deleted project by EOD?\n\nSnapshots are faster; PITR covers edits after the snapshot window.", note_a="asks agent operator to pick restore path -> either_or", note_b="hard: `?` only inside quoted customer text", da="m")
add(616, "Slack thread from design:\n\n\"Should the modal dismiss on outside click?\"\n\nDo you want outside-click dismiss enabled in the web app?", [{"kind": "y", "prompt": "Do you want outside-click dismiss enabled in the web app?"}], "Slack thread from design:\n\n\"Should the modal dismiss on outside click?\"\n\nI'll match mobile behavior: no outside dismiss, only explicit Cancel.", note_a="asks user product decision -> yes_no", note_b="hard: `?` only inside quoted Slack message")
add(617, "Ticket repro steps include the user asking:\n\n`Why does export hang at 99%?`\n\nCould you paste the export job ID from that ticket?", [{"kind": "o", "prompt": "Could you paste the export job ID from that ticket?"}], "Ticket repro steps include the user asking:\n\n`Why does export hang at 99%?`\n\nThe hang is the chunked upload waiting on a missing `ETag`, not the progress bar itself.", note_a="asks user for job ID -> open", note_b="hard: `?` inside backtick user question in ticket text")
add(618, "PM left a voice-note transcript:\n\n\"Can we ship the dark theme next sprint?\"\n\nShould I create a tracking issue for dark theme now?", [{"kind": "y", "propose": True, "prompt": "Should I create a tracking issue for dark theme now?"}], "PM left a voice-note transcript:\n\n\"Can we ship the dark theme next sprint?\"\n\nI'll draft the issue and link the design tokens doc.", note_a="asks approval to create issue -> yes_no/propose", note_b="hard: `?` only in quoted PM transcript")
add(619, "Sample chatbot script in the spec shows:\n\n- Bot: \"Need help resetting your password?\"\n- User: \"Yes\"\n\nWant me to implement that exact copy in `HelpWidget`?", [{"kind": "y", "propose": True, "prompt": "Want me to implement that exact copy in `HelpWidget`?"}], "Sample chatbot script in the spec shows:\n\n- Bot: \"Need help resetting your password?\"\n- User: \"Yes\"\n\nProduction copy should be shorter; I'll trim the greeting unless you want verbatim spec text.", note_a="asks approval to implement sample copy -> yes_no/propose", note_b="hard: `?` inside sample dialogue, not addressed to user", da="m")
add(620, "Email draft quotes the customer:\n\n\"Is there a way to bulk-invite teammates?\"\n\nWhich bulk-invite UX should I build — CSV upload or domain allowlist?", [{"kind": "e", "prompt": "Which bulk-invite UX should I build \u2014 CSV upload or domain allowlist?", "opts": ["CSV upload", "domain allowlist"]}], "Email draft quotes the customer:\n\n\"Is there a way to bulk-invite teammates?\"\n\nCSV upload ships faster; domain allowlist is safer for enterprise tenants.", note_a="asks user to pick implementation path -> either_or", note_b="hard: `?` only in quoted customer email", da="m")

# --- checklists / open questions ---
add(621, "Before merging, sanity-check the edge cases:\n\n- Ask yourself: would a null `userId` slip through?\n- Ask yourself: does retry exhaust the budget?\n\nWant me to add guards for both cases?", [{"kind": "y", "propose": True, "prompt": "Want me to add guards for both cases?"}], "Before merging, sanity-check the edge cases:\n\n- Ask yourself: would a null `userId` slip through?\n- Ask yourself: does retry exhaust the budget?\n\nI'll add explicit null checks and cap retries at three attempts.", note_a="asks approval to add guards -> yes_no/propose", note_b="hard: 'Ask yourself:' checklist questions for reader, not agent")
add(622, "**Open questions** on the RFC:\n\n1. Do we need cross-region failover day one?\n2. Is 15-minute RPO acceptable?\n\nShould I schedule a review meeting with infra?", [{"kind": "y", "propose": True, "prompt": "Should I schedule a review meeting with infra?"}], "**Open questions** on the RFC:\n\n1. Do we need cross-region failover day one?\n2. Is 15-minute RPO acceptable?\n\nI'll circulate the RFC async and collect comments in the doc.", note_a="asks approval to schedule meeting -> yes_no/propose", note_b="hard: numbered open questions are RFC prompts, not to the user")
add(623, "Self-review before you hand this off:\n\n> Are migrations backward compatible?\n> Will rollbacks leave orphan rows?\n\nCan you confirm both are true for `202509_user_prefs`?", [{"kind": "o", "prompt": "Can you confirm both are true for `202509_user_prefs`?"}], "Self-review before you hand this off:\n\n> Are migrations backward compatible?\n> Will rollbacks leave orphan rows?\n\nThe migration is backward compatible; rollback leaves no orphans because we only add a nullable column.", note_a="asks user to confirm migration properties -> open", note_b="hard: blockquote checklist for author self-review, not user Q", da="m")
add(624, "PR description template ends with:\n\n**Ask yourself:** Does this change user-visible strings?\n\nDid you update snapshots if UI copy changed?", [{"kind": "y", "prompt": "Did you update snapshots if UI copy changed?"}], "PR description template ends with:\n\n**Ask yourself:** Does this change user-visible strings?\n\nI'll scan for string changes and refresh snapshots where needed.", note_a="asks author about snapshot updates -> yes_no", note_b="hard: 'Ask yourself' template line, not addressed question")
add(625, "Runbook draft includes a pre-flight list:\n\n- [ ] Is the maintenance window announced?\n- [ ] Are replicas caught up?\n\nWant me to post the window notice in `#status`?", [{"kind": "y", "propose": True, "prompt": "Want me to post the window notice in `#status`?"}], "Runbook draft includes a pre-flight list:\n\n- [ ] Is the maintenance window announced?\n- [ ] Are replicas caught up?\n\nI'll announce the window and verify replica lag before cutover.", note_a="asks approval to post notice -> yes_no/propose", note_b="hard: checklist questions are operational prompts, not to user")
add(626, "Design critique worksheet says:\n\n\"Does the empty state explain the next step?\"\n\nShould I rewrite the empty state copy in `ProjectsList`?", [{"kind": "y", "propose": True, "prompt": "Should I rewrite the empty state copy in `ProjectsList`?"}], "Design critique worksheet says:\n\n\"Does the empty state explain the next step?\"\n\nThe current empty state is vague; I'll add a primary CTA to create a project.", note_a="asks approval to rewrite copy -> yes_no/propose", note_b="hard: worksheet question for designer self-check")
add(627, "Incident retro template lists:\n\n**Questions for the on-call lead:** What broke detection? What broke mitigation?\n\nDo you want me to fill those sections from the timeline?", [{"kind": "y", "propose": True, "prompt": "Do you want me to fill those sections from the timeline?"}], "Incident retro template lists:\n\n**Questions for the on-call lead:** What broke detection? What broke mitigation?\n\nDetection lagged because alerts routed to a muted channel; mitigation waited on a manual failover.", note_a="asks approval to populate retro -> yes_no/propose", note_b="hard: template prompts for on-call lead, not current user", da="m")
add(628, "QA checklist for release:\n\n- Can a guest user reach billing?\n- Does logout clear refresh tokens?\n\nWhich item failed in staging — guest billing or logout?", [{"kind": "e", "prompt": "Which item failed in staging \u2014 guest billing or logout?", "opts": ["guest billing", "logout"]}], "QA checklist for release:\n\n- Can a guest user reach billing?\n- Does logout clear refresh tokens?\n\nGuest billing failed; logout token clearing passed on build 412.", note_a="asks user which checklist item failed -> either_or", note_b="hard: QA checklist questions are test prompts, not to user", da="m")
add(629, "Architecture review worksheet:\n\n\"Is this service stateless?\" \"Can it scale horizontally?\"\n\nWant me to add a `/healthz` probe and document scale-out?", [{"kind": "y", "propose": True, "prompt": "Want me to add a `/healthz` probe and document scale-out?"}], "Architecture review worksheet:\n\n\"Is this service stateless?\" \"Can it scale horizontally?\"\n\nThe worker is stateless; horizontal scale works once the queue consumer group is configured.", note_a="asks approval to add health probe -> yes_no/propose", note_b="hard: worksheet interrogatives for reviewers")
add(630, "Before enabling auto-merge, confirm:\n\n**Ask yourself:** Are feature flags off by default?\n\nShould I enable auto-merge on `dependabot/npm`?", [{"kind": "y", "propose": True, "prompt": "Should I enable auto-merge on `dependabot/npm`?"}], "Before enabling auto-merge, confirm:\n\n**Ask yourself:** Are feature flags off by default?\n\nDependabot PRs can auto-merge after CI passes; flags remain off by default.", note_a="asks approval for auto-merge -> yes_no/propose", note_b="hard: bold 'Ask yourself' line is author checklist")

# --- conditional offers (no `?`) ---
add(631, "The migration is ready on staging and tests are green.\n\nWant me to run it on production tonight?", [{"kind": "y", "propose": True, "prompt": "Want me to run it on production tonight?"}], "The migration is ready on staging and tests are green.\n\nIf you want, I can run it on production tonight during the low-traffic window.", note_a="asks approval to run prod migration -> yes_no/propose", note_b="hard: conditional offer without `?` ('If you want, I can…')")
add(632, "I fixed the race in `JobQueue` and added a regression test.\n\nShould I open the PR against `main`?", [{"kind": "y", "propose": True, "prompt": "Should I open the PR against `main`?"}], "I fixed the race in `JobQueue` and added a regression test.\n\nI can open a PR against `main` whenever you're ready.", note_a="asks approval to open PR -> yes_no/propose", note_b="hard: offer phrased without question mark")
add(633, "Cache invalidation hooks are wired; only the CDN purge remains.\n\nDo you want me to purge CloudFront after deploy?", [{"kind": "y", "propose": True, "prompt": "Do you want me to purge CloudFront after deploy?"}], "Cache invalidation hooks are wired; only the CDN purge remains.\n\nI can purge CloudFront right after deploy if that helps.", note_a="asks approval for CDN purge -> yes_no/propose", note_b="hard: trailing offer without `?`")
add(634, "Benchmarks show the JSON parser dominates CPU on large payloads.\n\nWant me to swap in `simdjson` behind a feature flag?", [{"kind": "y", "propose": True, "prompt": "Want me to swap in `simdjson` behind a feature flag?"}], "Benchmarks show the JSON parser dominates CPU on large payloads.\n\nSwapping in `simdjson` behind a flag is the next step when you want it.", note_a="asks approval to add simdjson -> yes_no/propose", note_b="hard: recommendation without interrogative", da="m")
add(635, "Docs for the webhook signature are drafted.\n\nShall I publish them to the public docs site?", [{"kind": "y", "propose": True, "prompt": "Shall I publish them to the public docs site?"}], "Docs for the webhook signature are drafted.\n\nPublishing to the public docs site is straightforward whenever you give the word.", note_a="asks approval to publish docs -> yes_no/propose", note_b="hard: invitation without `?`")
add(636, "Local repro matches CI: flaky test in `test_upload_chunked`.\n\nShould I mark it `@pytest.mark.flaky` and open a ticket?", [{"kind": "y", "propose": True, "prompt": "Should I mark it `@pytest.mark.flaky` and open a ticket?"}], "Local repro matches CI: flaky test in `test_upload_chunked`.\n\nI can mark it flaky and file a tracking ticket if you'd like.", note_a="asks approval to mark flaky + ticket -> yes_no/propose", note_b="hard: conditional offer without `?`")
add(637, "The dark-mode tokens compile but Storybook still forces light theme.\n\nWant me to flip the Storybook default to dark?", [{"kind": "y", "propose": True, "prompt": "Want me to flip the Storybook default to dark?"}], "The dark-mode tokens compile but Storybook still forces light theme.\n\nFlipping Storybook to dark default is a one-line change when you want it.", note_a="asks approval to change Storybook default -> yes_no/propose", note_b="hard: offer without `?`")
add(638, "Secrets scanner flagged an old API key in a gist link.\n\nDo you want me to rotate the key and revoke the old one?", [{"kind": "y", "propose": True, "prompt": "Do you want me to rotate the key and revoke the old one?"}], "Secrets scanner flagged an old API key in a gist link.\n\nRotating the key and revoking the old one is the safe move — say the word and I'll do it.", note_a="asks approval to rotate key -> yes_no/propose", note_b="hard: imperative invite ('say the word') without `?`")
add(639, "Load test hit 429s once we crossed 800 RPS.\n\nShould I raise the rate limit for the beta cohort only?", [{"kind": "y", "propose": True, "prompt": "Should I raise the rate limit for the beta cohort only?"}], "Load test hit 429s once we crossed 800 RPS.\n\nRaising limits for the beta cohort only is easy to roll out when you're ready.", note_a="asks approval to raise limit -> yes_no/propose", note_b="hard: conditional readiness offer, no `?`")
add(640, "Translation files for `fr-CA` are 98% complete.\n\nWant me to import the remaining strings and tag `v1.9`?", [{"kind": "y", "propose": True, "prompt": "Want me to import the remaining strings and tag `v1.9`?"}], "Translation files for `fr-CA` are 98% complete.\n\nI can import the remaining strings and tag `v1.9` after your sign-off.", note_a="asks approval to import + tag -> yes_no/propose", note_b="hard: offer contingent on sign-off, no `?`")

# --- FAQ in docs/code ---
add(641, "Generated README section for the CLI:\n\n### FAQ: How do I reset config?\n\nRun `mycli config reset`.\n\nWant me to commit this README block?", [{"kind": "y", "propose": True, "prompt": "Want me to commit this README block?"}], "Generated README section for the CLI:\n\n### FAQ: How do I reset config?\n\nRun `mycli config reset`.\n\nI'll commit the README block with the reset command documented.", note_a="asks approval to commit README -> yes_no/propose", note_b="hard: FAQ heading with `?` inside generated docs")
add(642, "API reference draft includes:\n\n**Q: Why do I get HTTP 409?** A: Version conflict on update.\n\nShould I publish this page to `/docs/api/errors`?", [{"kind": "y", "propose": True, "prompt": "Should I publish this page to `/docs/api/errors`?"}], "API reference draft includes:\n\n**Q: Why do I get HTTP 409?** A: Version conflict on update.\n\nThe 409 entry is accurate; I'll publish it under `/docs/api/errors`.", note_a="asks approval to publish error doc -> yes_no/propose", note_b="hard: FAQ Q/A line in reference, not user question")
add(643, "```markdown\n## Troubleshooting\n### Why is my webhook failing?\nCheck the signing secret.\n```\n\nWant me to add this troubleshooting section to the repo README?", [{"kind": "y", "propose": True, "prompt": "Want me to add this troubleshooting section to the repo README?"}], "```markdown\n## Troubleshooting\n### Why is my webhook failing?\nCheck the signing secret.\n```\n\nThe troubleshooting blurb is ready to paste into the README.", note_a="asks approval to add troubleshooting section -> yes_no/propose", note_b="hard: `?` inside markdown FAQ heading in code fence", da="m")
add(644, "Scaffolded plugin README lists:\n\n- **FAQ:** Where are logs written?\n- **FAQ:** Can I disable telemetry?\n\nWhich FAQ entry should I expand first — logs or telemetry?", [{"kind": "e", "prompt": "Which FAQ entry should I expand first \u2014 logs or telemetry?", "opts": ["logs", "telemetry"]}], "Scaffolded plugin README lists:\n\n- **FAQ:** Where are logs written?\n- **FAQ:** Can I disable telemetry?\n\nI'll expand the logs entry first because support asks about log paths daily.", note_a="asks user to pick FAQ to expand -> either_or", note_b="hard: FAQ bullet headings contain `?`", da="m")
add(645, "[CODE]\n// FAQ: Why does compile fail on M1?\n// Install the arm64 toolchain.\n[/CODE]\n\nShould I land this comment above the build script?", [{"kind": "y", "propose": True, "prompt": "Should I land this comment above the build script?"}], "[CODE]\n// FAQ: Why does compile fail on M1?\n// Install the arm64 toolchain.\n[/CODE]\n\nThe comment belongs above the build script to save the next M1 user an hour.", note_a="asks approval to add FAQ comment -> yes_no/propose", note_b="hard: `?` inside code comment FAQ")
add(646, "Help center article skeleton:\n\n> **How do I invite teammates?**\n> Open Settings → Team.\n\nWant me to push this article to the CMS draft?", [{"kind": "y", "propose": True, "prompt": "Want me to push this article to the CMS draft?"}], "Help center article skeleton:\n\n> **How do I invite teammates?**\n> Open Settings → Team.\n\nI'll push the draft to CMS once screenshots are attached.", note_a="asks approval to push CMS draft -> yes_no/propose", note_b="hard: help article heading with `?`")
add(647, "Onboarding email template includes:\n\nSubject: Ready to get started?\nBody: Click Activate below.\n\nShould I A/B test that subject line?", [{"kind": "y", "propose": True, "prompt": "Should I A/B test that subject line?"}], "Onboarding email template includes:\n\nSubject: Ready to get started?\nBody: Click Activate below.\n\nThe subject works; A/B testing can wait until after launch.", note_a="asks approval to A/B subject -> yes_no/propose", note_b="hard: marketing subject line contains `?`", da="m")
add(648, "Generated OpenAPI description field:\n\n\"Returns 404 when the resource is missing? See error schema.\"\n\nWant me to fix that description string?", [{"kind": "y", "propose": True, "prompt": "Want me to fix that description string?"}], "Generated OpenAPI description field:\n\n\"Returns 404 when the resource is missing? See error schema.\"\n\nThe description string is mangled; I'll rewrite it without the stray question mark.", note_a="asks approval to fix OpenAPI text -> yes_no/propose", note_b="hard: erroneous `?` inside schema description string")
add(649, "Static site FAQ page markup:\n\n`<h3>Can I use SSO?</h3><p>Yes, on Enterprise.</p>`\n\nShould I wire this page into the nav?", [{"kind": "y", "propose": True, "prompt": "Should I wire this page into the nav?"}], "Static site FAQ page markup:\n\n`<h3>Can I use SSO?</h3><p>Yes, on Enterprise.</p>`\n\nSSO FAQ belongs in the Enterprise nav group.", note_a="asks approval to add nav link -> yes_no/propose", note_b="hard: HTML FAQ heading with `?`")
add(650, "Changelog draft:\n\n**Breaking:** Removed legacy `/v1/search?` endpoint.\n\nDo you want a migration note calling out the `/v2/search` replacement?", [{"kind": "y", "prompt": "Do you want a migration note calling out the `/v2/search` replacement?"}], "Changelog draft:\n\n**Breaking:** Removed legacy `/v1/search?` endpoint.\n\nI'll add a migration note pointing teams at `/v2/search`.", note_a="asks user about migration note -> yes_no", note_b="hard: `?` inside deprecated URL in changelog", da="m")

# --- advice: ask someone else ---
add(651, "Connection pool sizing depends on DBA policy we don't control.\n\nWhich pool size should I put in the chart — 50 or 100?", [{"kind": "e", "prompt": "Which pool size should I put in the chart \u2014 50 or 100?", "opts": ["50", "100"]}], "Connection pool sizing depends on DBA policy we don't control.\n\nAsk your DBA: Is 100 connections acceptable on the primary during peak?", note_a="asks user to pick chart value -> either_or", note_b="hard: advice to ask DBA, not question to user", da="m")
add(652, "Legal needs to bless the new retention window.\n\nShould I enable 90-day log retention in prod?", [{"kind": "y", "propose": True, "prompt": "Should I enable 90-day log retention in prod?"}], "Legal needs to bless the new retention window.\n\nCheck with legal: Is 90-day retention approved for EU tenants?", note_a="asks approval to enable retention -> yes_no/propose", note_b="hard: 'Check with legal' advisory question")
add(653, "Security wants confirmation before we expose admin APIs publicly.\n\nWant me to keep admin routes private-network only?", [{"kind": "y", "propose": True, "prompt": "Want me to keep admin routes private-network only?"}], "Security wants confirmation before we expose admin APIs publicly.\n\nSecurity should confirm: Are admin APIs allowed on the public ingress at all?", note_a="asks approval to keep admin private -> yes_no/propose", note_b="hard: question directed at security team, not user")
add(654, "Finance owns the tax code mapping.\n\nCan you tell me which VAT code applies to digital services in DE?", [{"kind": "o", "prompt": "Can you tell me which VAT code applies to digital services in DE?"}], "Finance owns the tax code mapping.\n\nAsk finance: Which VAT code applies to digital services in DE?", note_a="asks user for VAT code -> open", note_b="hard: same question reframed as advice to ask finance", da="m")
add(655, "Ops maintains the maintenance calendar.\n\nDo you want the deploy scheduled for Saturday 02:00 UTC?", [{"kind": "y", "prompt": "Do you want the deploy scheduled for Saturday 02:00 UTC?"}], "Ops maintains the maintenance calendar.\n\nAsk ops: Is Saturday 02:00 UTC inside the approved maintenance window?", note_a="asks user about deploy time -> yes_no", note_b="hard: advisory question for ops team")
add(656, "Product marketing owns launch naming.\n\nWhat should the feature be called in the UI?", [{"kind": "o", "prompt": "What should the feature be called in the UI?"}], "Product marketing owns launch naming.\n\nAsk marketing: What customer-facing name do they want in the UI?", note_a="asks user for UI name -> open", note_b="hard: redirected question to marketing")
add(657, "Compliance must sign off before we turn on audit logging for PHI.\n\nShould I enable audit logs in staging first?", [{"kind": "y", "propose": True, "prompt": "Should I enable audit logs in staging first?"}], "Compliance must sign off before we turn on audit logging for PHI.\n\nCompliance needs to answer: Is staging sufficient for PHI audit validation?", note_a="asks approval for staging audit logs -> yes_no/propose", note_b="hard: question for compliance, not user")
add(658, "Platform SRE owns error budget policy.\n\nWant me to page on-call if error budget burn exceeds 25% this week?", [{"kind": "y", "propose": True, "prompt": "Want me to page on-call if error budget burn exceeds 25% this week?"}], "Platform SRE owns error budget policy.\n\nAsk SRE: At what burn rate should paging start this week?", note_a="asks approval to page on burn -> yes_no/propose", note_b="hard: SRE policy question not to user", da="m")
add(659, "Customer success maintains the escalation matrix.\n\nWhich tier should get the hotfix — Tier 1 or Tier 2?", [{"kind": "e", "prompt": "Which tier should get the hotfix \u2014 Tier 1 or Tier 2?", "opts": ["Tier 1", "Tier 2"]}], "Customer success maintains the escalation matrix.\n\nEscalations should ask CS: Which tier gets a same-day hotfix?", note_a="asks user to pick tier -> either_or", note_b="hard: CS escalation question directed elsewhere", da="m")
add(660, "Facilities controls badge access for the colo rack.\n\nCan you confirm someone will meet us at the datacenter Friday?", [{"kind": "o", "prompt": "Can you confirm someone will meet us at the datacenter Friday?"}], "Facilities controls badge access for the colo rack.\n\nAsk facilities: Will someone meet us at the datacenter Friday?", note_a="asks user to confirm datacenter escort -> open", note_b="hard: same ask reframed to facilities contact")

# --- headings answered ---
add(661, "**Why does the upload fail?** Multipart uploads abort when `Content-Length` mismatches the streamed bytes.\n\nWant me to patch the client to send accurate lengths?", [{"kind": "y", "propose": True, "prompt": "Want me to patch the client to send accurate lengths?"}], "**Why does the upload fail?** Multipart uploads abort when `Content-Length` mismatches the streamed bytes.\n\nI'll patch the client to send accurate lengths next.", note_a="asks approval to patch client -> yes_no/propose", note_b="hard: troubleshooting heading answered immediately")
add(662, "**What broke the deploy?** Helm left a stale ConfigMap reference.\n\nShould I delete the orphaned ConfigMap and redeploy?", [{"kind": "y", "propose": True, "prompt": "Should I delete the orphaned ConfigMap and redeploy?"}], "**What broke the deploy?** Helm left a stale ConfigMap reference.\n\nDeleting the orphaned ConfigMap and redeploying clears the error.", note_a="asks approval to delete + redeploy -> yes_no/propose", note_b="hard: diagnostic heading self-answered")
add(663, "**Why is latency spiking?** The new middleware logs every request body synchronously.\n\nDo you want me to switch that logger to async?", [{"kind": "y", "propose": True, "prompt": "Do you want me to switch that logger to async?"}], "**Why is latency spiking?** The new middleware logs every request body synchronously.\n\nAsync logging should restore p95 latency without losing events.", note_a="asks approval to async logger -> yes_no/propose", note_b="hard: 'Why is latency spiking?' answered in same turn")
add(664, "**How did we miss this bug?** Tests mocked the network layer entirely.\n\nWant me to add an integration test that hits the sandbox API?", [{"kind": "y", "propose": True, "prompt": "Want me to add an integration test that hits the sandbox API?"}], "**How did we miss this bug?** Tests mocked the network layer entirely.\n\nAn integration test against the sandbox API would have caught it.", note_a="asks approval to add integration test -> yes_no/propose", note_b="hard: retrospective heading answered by assistant", da="m")
add(665, "**Why does OAuth redirect fail?** Callback URL still uses `http://localhost:3000` in prod config.\n\nShould I update the prod callback to the HTTPS domain?", [{"kind": "y", "propose": True, "prompt": "Should I update the prod callback to the HTTPS domain?"}], "**Why does OAuth redirect fail?** Callback URL still uses `http://localhost:3000` in prod config.\n\nUpdating prod to the HTTPS callback fixes the redirect loop.", note_a="asks approval to update callback URL -> yes_no/propose", note_b="hard: FAQ-style heading immediately explained")
add(666, "**What's causing the 500s?** A nil pointer in the new feature flag middleware.\n\nWant me to ship a hotfix guard tonight?", [{"kind": "y", "propose": True, "prompt": "Want me to ship a hotfix guard tonight?"}], "**What's causing the 500s?** A nil pointer in the new feature flag middleware.\n\nA nil guard hotfix is ready to ship tonight.", note_a="asks approval for hotfix -> yes_no/propose", note_b="hard: incident heading answered inline")
add(667, "**Why aren't webhooks firing?** The signing secret rotated but the worker still reads the old env var.\n\nCan you confirm the new secret is in the deploy env?", [{"kind": "o", "prompt": "Can you confirm the new secret is in the deploy env?"}], "**Why aren't webhooks firing?** The signing secret rotated but the worker still reads the old env var.\n\nOnce the deploy env carries the new secret, deliveries should resume.", note_a="asks user to confirm env secret -> open", note_b="hard: diagnostic heading answered; no user Q in b")
add(668, "**What changed in v2?** We tightened default CSP and removed inline scripts.\n\nDo you want a temporary `'unsafe-inline'` escape hatch for legacy pages?", [{"kind": "y", "prompt": "Do you want a temporary `'unsafe-inline'` escape hatch for legacy pages?"}], "**What changed in v2?** We tightened default CSP and removed inline scripts.\n\nLegacy pages need a migration path; `'unsafe-inline'` is a short-term bridge.", note_a="asks user about CSP escape hatch -> yes_no", note_b="hard: release-notes style heading answered", da="m")
add(669, "**Why did CI fail?** `pnpm-lock.yaml` drifted from `package.json`.\n\nShould I regenerate the lockfile and push?", [{"kind": "y", "propose": True, "prompt": "Should I regenerate the lockfile and push?"}], "**Why did CI fail?** `pnpm-lock.yaml` drifted from `package.json`.\n\nRegenerating the lockfile locally reproduces the fix.", note_a="asks approval to regen lockfile -> yes_no/propose", note_b="hard: CI postmortem heading self-answered")
add(670, "**How do I fix the TLS error?** Install the intermediate cert bundle on the worker nodes.\n\nWant me to update the Ansible role to deploy the bundle?", [{"kind": "y", "propose": True, "prompt": "Want me to update the Ansible role to deploy the bundle?"}], "**How do I fix the TLS error?** Install the intermediate cert bundle on the worker nodes.\n\nThe Ansible role can deploy the bundle on the next play.", note_a="asks approval to update Ansible -> yes_no/propose", note_b="hard: how-to heading answered, not user question")

# --- mixed hard negatives ---
add(671, "GraphQL resolver returns partial data when `organization` is null.\n\n```ts\nreturn org?.members?.map((m) => m.id) ?? [];\n```\n\nWant me to add an explicit null guard before mapping?", [{"kind": "y", "propose": True, "prompt": "Want me to add an explicit null guard before mapping?"}], "GraphQL resolver returns partial data when `organization` is null.\n\n```ts\nreturn org?.members?.map((m) => m.id) ?? [];\n```\n\nOptional chaining already yields `[]` when `org` is null; explicit guards would duplicate that behavior.", note_a="asks approval to add null guard -> yes_no/propose", note_b="hard: `?` in optional chaining inside code fence")
add(672, "Shell probe in the health check:\n\n```bash\ncurl -sf \"https://api.example.com/health?verbose=1\" || echo \"curl failed: $?\"\n```\n\nShould I replace this with a native TCP check?", [{"kind": "y", "propose": True, "prompt": "Should I replace this with a native TCP check?"}], "Shell probe in the health check:\n\n```bash\ncurl -sf \"https://api.example.com/health?verbose=1\" || echo \"curl failed: $?\"\n```\n\nThe probe mixes query params and `$?` logging; a TCP check is simpler.", note_a="asks approval to change probe -> yes_no/propose", note_b="hard: `?` in URL query and `$?` in same script", da="m")
add(673, "User message in the ticket: \"Can you reset my 2FA?\"\n\nDo you want me to send them the self-serve reset link?", [{"kind": "y", "propose": True, "prompt": "Do you want me to send them the self-serve reset link?"}], "User message in the ticket: \"Can you reset my 2FA?\"\n\nSelf-serve reset is policy; I'll reply with the documented link template.", note_a="asks approval to send reset link -> yes_no/propose", note_b="hard: quoted ticket question not to agent operator")
add(674, "Draft PR checklist:\n\n- Does this need a feature flag?\n- Does this need docs?\n\nWhich item should I tackle first — flag or docs?", [{"kind": "e", "prompt": "Which item should I tackle first \u2014 flag or docs?", "opts": ["flag", "docs"]}], "Draft PR checklist:\n\n- Does this need a feature flag?\n- Does this need docs?\n\nFeature flag first; docs follow once behavior stabilizes.", note_a="asks user to prioritize checklist items -> either_or", note_b="hard: PR checklist questions not addressed to user", da="m")
add(675, "If you want, I can draft the rollback runbook — but I need your go-ahead on scope.\n\nShould the runbook cover database restore only, or app + database?", [{"kind": "e", "prompt": "Should the runbook cover database restore only, or app + database?", "opts": ["database restore only", "app + database"]}], "If you want, I can draft the rollback runbook — but I need your go-ahead on scope.\n\nI'll cover database restore only unless you prefer app + database steps too.", note_a="asks user to pick runbook scope -> either_or", note_b="hard: opening conditional offer; b continues without new `?` — scope stated as statement", da="m")
add(676, "Release notes snippet:\n\n`See also: /help?article=upgrade`\n\nWant me to fix the broken help link in `CHANGELOG.md`?", [{"kind": "y", "propose": True, "prompt": "Want me to fix the broken help link in `CHANGELOG.md`?"}], "Release notes snippet:\n\n`See also: /help?article=upgrade`\n\nThe help URL needs the correct article slug before we ship.", note_a="asks approval to fix link -> yes_no/propose", note_b="hard: `?` inside help URL in inline code")
add(677, "Pair programming note — mentor asked:\n\n\"Why not extract a service object here?\"\n\nDo you want me to extract `InvoiceCalculator` now?", [{"kind": "y", "propose": True, "prompt": "Do you want me to extract `InvoiceCalculator` now?"}], "Pair programming note — mentor asked:\n\n\"Why not extract a service object here?\"\n\nExtracting `InvoiceCalculator` keeps the controller thin.", note_a="asks approval to extract service -> yes_no/propose", note_b="hard: quoted mentor rhetorical question")
add(678, "Spec section **Open questions** (for future readers):\n\n- Should webhooks retry indefinitely?\n\nWant me to cap retries at five attempts?", [{"kind": "y", "propose": True, "prompt": "Want me to cap retries at five attempts?"}], "Spec section **Open questions** (for future readers):\n\n- Should webhooks retry indefinitely?\n\nCapping at five attempts balances delivery with load.", note_a="asks approval to cap retries -> yes_no/propose", note_b="hard: spec open question for readers, not user")
add(679, "Training slide bullet: \"Is your pipeline idempotent?\"\n\nShould I add an idempotency key to the deploy job?", [{"kind": "y", "propose": True, "prompt": "Should I add an idempotency key to the deploy job?"}], "Training slide bullet: \"Is your pipeline idempotent?\"\n\nDeploy jobs need idempotency keys to safely retry.", note_a="asks approval to add idempotency key -> yes_no/propose", note_b="hard: slide rhetorical/checklist question")
add(680, "Mock interview prompt in the doc:\n\n\"How would you debug a memory leak in Node?\"\n\nWant me to add heap snapshot steps to the runbook?", [{"kind": "y", "propose": True, "prompt": "Want me to add heap snapshot steps to the runbook?"}], "Mock interview prompt in the doc:\n\n\"How would you debug a memory leak in Node?\"\n\nHeap snapshots belong in the runbook under the Node troubleshooting section.", note_a="asks approval to extend runbook -> yes_no/propose", note_b="hard: interview prompt question in documentation")
add(681, "Two fixes are ready: patch prod now or wait for the weekly release train.\n\nWhich do you prefer — hotfix tonight or wait for Thursday's train?", [{"kind": "e", "prompt": "Which do you prefer \u2014 hotfix tonight or wait for Thursday's train?", "opts": ["hotfix tonight", "wait for Thursday's train"]}], "Two fixes are ready: patch prod now or wait for the weekly release train.\n\nHotfix tonight limits exposure; waiting for Thursday's train keeps change volume down.", note_a="asks user to choose release path -> either_or", note_b="hard: no addressed Q in b; contrast is offer/analysis without `?`", da="m")
add(682, "Staging reproduces the bug when `DEBUG` is unset.\n\nCan you export `DEBUG=app:*` and rerun the failing test?", [{"kind": "o", "prompt": "Can you export `DEBUG=app:*` and rerun the failing test?"}], "Staging reproduces the bug when `DEBUG` is unset.\n\nSet `DEBUG=app:*` locally and rerun — the verbose logs show the null dereference.", note_a="asks user to rerun with DEBUG -> open", note_b="hard: imperative instruction without `?` in b")
add(683, "The widget crashes on Safari 17 when `ResizeObserver` is polyfilled twice.\n\nWant me to drop the duplicate polyfill import?", [{"kind": "y", "propose": True, "prompt": "Want me to drop the duplicate polyfill import?"}], "The widget crashes on Safari 17 when `ResizeObserver` is polyfilled twice.\n\n```js\nconst h = window.innerWidth > 768 ? 'desktop' : 'mobile';\n```\n\nLayout code is unrelated; removing the duplicate polyfill fixes Safari.", note_a="asks approval to remove polyfill -> yes_no/propose", note_b="hard: ternary in unrelated layout snippet contains `?`")
add(684, "Metrics show elevated 499s from clients canceling slow queries.\n\nShould I add a server-side statement timeout of 30s?", [{"kind": "y", "propose": True, "prompt": "Should I add a server-side statement timeout of 30s?"}], "Metrics show elevated 499s from clients canceling slow queries.\n\n**Why are clients canceling?** Queries exceed 30s; a server-side timeout aligns abort behavior.", note_a="asks approval for statement timeout -> yes_no/propose", note_b="hard: bold diagnostic question answered inline")
add(685, "Copy deck includes FAQ: \"Can I export to PDF?\"\n\nDo you want PDF export in v1 or v2?", [{"kind": "e", "prompt": "Do you want PDF export in v1 or v2?", "opts": ["v1", "v2"]}], "Copy deck includes FAQ: \"Can I export to PDF?\"\n\nPDF export is slated for v2; v1 ships CSV only.", note_a="asks user release scope -> either_or", note_b="hard: product FAQ string with `?`", da="m")
add(686, "Lint rule demo in the docs uses:\n\n`foo?.bar?.baz ?? 'n/a'`\n\nWant me to enable that optional-chaining rule repo-wide?", [{"kind": "y", "propose": True, "prompt": "Want me to enable that optional-chaining rule repo-wide?"}], "Lint rule demo in the docs uses:\n\n`foo?.bar?.baz ?? 'n/a'`\n\nEnabling the rule repo-wide is a separate change from the demo snippet.", note_a="asks approval to enable lint rule -> yes_no/propose", note_b="hard: optional chaining demo contains `?`")
add(687, "Runbook says: \"If pager fires twice, escalate — ask: Is this a false positive?\"\n\nWant me to add that escalation block to `oncall.md`?", [{"kind": "y", "propose": True, "prompt": "Want me to add that escalation block to `oncall.md`?"}], "Runbook says: \"If pager fires twice, escalate — ask: Is this a false positive?\"\n\nThe escalation wording is for on-call, not a question to you right now.", note_a="asks approval to add escalation text -> yes_no/propose", note_b="hard: embedded runbook question for on-call", da="m")
add(688, "README quick start ends with:\n\n`npm init app@latest -- --template react-ts?`\n\nThat trailing `?` is a typo in our doc.\n\nShould I fix the command line in README?", [{"kind": "y", "propose": True, "prompt": "Should I fix the command line in README?"}], "README quick start ends with:\n\n`npm init app@latest -- --template react-ts?`\n\nThat trailing `?` is a typo in our doc.\n\nThe correct template flag has no question mark.", note_a="asks approval to fix README command -> yes_no/propose", note_b="hard: stray `?` in documented npm command")
add(689, "Beta survey question we must not store in tickets:\n\n\"Would you recommend us to a colleague?\"\n\nWant me to strip survey responses from webhook payloads?", [{"kind": "y", "propose": True, "prompt": "Want me to strip survey responses from webhook payloads?"}], "Beta survey question we must not store in tickets:\n\n\"Would you recommend us to a colleague?\"\n\nSurvey answers should never land in support tickets.", note_a="asks approval to strip survey fields -> yes_no/propose", note_b="hard: third-party survey question quoted")
add(690, "Generated test name: `should handle user?.settings?.theme when undefined?`\n\nRename it to drop the stray question mark?", [{"kind": "y", "prompt": "Rename it to drop the stray question mark?"}], "Generated test name: `should handle user?.settings?.theme when undefined?`\n\nThe test name accidentally includes `?`; I'll rename it without changing behavior.", note_a="asks user to approve rename -> yes_no", note_b="hard: `?` inside test title and optional chaining", da="m")
add(691, "Incident comms template:\n\n**Customer ask:** \"When will it be fixed?\"\n\nWhat ETA should I put in the status page — 30 minutes or 2 hours?", [{"kind": "e", "prompt": "What ETA should I put in the status page \u2014 30 minutes or 2 hours?", "opts": ["30 minutes", "2 hours"]}], "Incident comms template:\n\n**Customer ask:** \"When will it be fixed?\"\n\nStatus page ETA should reflect the rollback window, not a guess.", note_a="asks user for status ETA -> either_or", note_b="hard: customer question in template", da="m")
add(692, "Config comment:\n\n`# retry ? backoffMs : 0  (legacy)`\n\nWant me to delete that dead commented line?", [{"kind": "y", "propose": True, "prompt": "Want me to delete that dead commented line?"}], "Config comment:\n\n`# retry ? backoffMs : 0  (legacy)`\n\nThe commented ternary is obsolete noise.", note_a="asks approval to delete comment -> yes_no/propose", note_b="hard: ternary with `?` inside comment")
add(693, "Slide title: \"Ready for production?\"\n\nShould I move that checklist slide after the monitoring section?", [{"kind": "y", "propose": True, "prompt": "Should I move that checklist slide after the monitoring section?"}], "Slide title: \"Ready for production?\"\n\nDeck order is a presentation concern; monitoring should precede the go-live checklist.", note_a="asks approval to reorder slides -> yes_no/propose", note_b="hard: slide title question not to user")
add(694, "Parser test fixture includes URL `https://cdn.example/assets/logo.png?v=2?cache=bust`.\n\nWant me to fix the malformed query string in the fixture?", [{"kind": "y", "propose": True, "prompt": "Want me to fix the malformed query string in the fixture?"}], "Parser test fixture includes URL `https://cdn.example/assets/logo.png?v=2?cache=bust`.\n\nDouble `?` in the fixture is intentional to test bad URLs.", note_a="asks approval to fix fixture URL -> yes_no/propose", note_b="hard: multiple `?` in URL test data", da="m")
add(695, "Chat export shows the user typed: \"hello?\" as a greeting typo.\n\nCan you paste the full raw message log?", [{"kind": "o", "prompt": "Can you paste the full raw message log?"}], "Chat export shows the user typed: \"hello?\" as a greeting typo.\n\nThe stray `?` is noise; the useful part is the timestamped payload around the error.", note_a="asks user for raw log -> open", note_b="hard: `?` inside quoted user typo")
add(696, "Policy doc: employees must ask IT: \"May I install local admin tools?\"\n\nDo you want an exception ticket filed for this laptop?", [{"kind": "y", "prompt": "Do you want an exception ticket filed for this laptop?"}], "Policy doc: employees must ask IT: \"May I install local admin tools?\"\n\nLocal admin requires IT approval per policy.", note_a="asks user about exception ticket -> yes_no", note_b="hard: policy sample question to IT")
add(697, "Benchmark output line: `throughput (ops/s?)` is mislabeled.\n\nShould I rename the column to `throughput_ops_s` in the CSV?", [{"kind": "y", "propose": True, "prompt": "Should I rename the column to `throughput_ops_s` in the CSV?"}], "Benchmark output line: `throughput (ops/s?)` is mislabeled.\n\nColumn rename is cosmetic but helps downstream charts.", note_a="asks approval to rename CSV column -> yes_no/propose", note_b="hard: `?` inside benchmark column label")
add(698, "Three modules touch billing: `invoices`, `tax`, `dunning`.\n\nWhich module(s) should I patch first today?", [{"kind": "m", "multi": True, "prompt": "Which module(s) should I patch first today?", "opts": ["invoices", "tax", "dunning"]}], "Three modules touch billing: `invoices`, `tax`, `dunning`.\n\n**Where to start?** `invoices` first — tax depends on line items; dunning waits on invoice state.", note_a="asks user which modules to patch -> multi_choice", note_b="hard: heading question answered with recommendation, no user Q", da="m")
add(699, "VPN split-tunnel doc FAQ:\n\n> Q: Why can't I reach internal APIs?\n> A: Split tunnel excludes RFC1918 routes.\n\nWant me to add this FAQ to the onboarding PDF?", [{"kind": "y", "propose": True, "prompt": "Want me to add this FAQ to the onboarding PDF?"}], "VPN split-tunnel doc FAQ:\n\n> Q: Why can't I reach internal APIs?\n> A: Split tunnel excludes RFC1918 routes.\n\nOnboarding PDF should include the split-tunnel FAQ verbatim.", note_a="asks approval to add FAQ to PDF -> yes_no/propose", note_b="hard: blockquote FAQ with Q/A")
add(700, "I can push the branch, open the PR, and tag reviewers — just need your pick on scope.\n\nWant me to push and open the PR now?", [{"kind": "y", "propose": True, "prompt": "Want me to push and open the PR now?"}], "I can push the branch, open the PR, and tag reviewers — just need your pick on scope.\n\nPush and PR are ready whenever you say go.", note_a="asks approval to push + open PR -> yes_no/propose", note_b="hard: closing invitation without `?` ('whenever you say go')")

assert len(PAIRS) == 100
assert [p["n"] for p in PAIRS] == list(range(601, 701))

