# Hand-authored yes_no vs either_or pairs pa0201–pa0300.

PAIRS = [
  {
    'n': 201,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: Dockerfile vs compose file',
    'note_b': 'yes_no: one Dockerfile tweak (base or tag)',
    'text_a': 'I traced it through the handler and the repository layer. The bug is localized; the surrounding refactor can wait.\n\nThe API image builds fine locally but CI still pulls the old layer cache.\n\nWant me to rewrite the Dockerfile or add a `docker-compose.yml` for local parity?',
    'text_b': 'I traced it through the handler and the repository layer. The bug is localized; the surrounding refactor can wait.\n\nThe API image builds fine locally but CI still pulls the old layer cache.\n\nWant the Dockerfile to use a different base or tag?',
    'ann_a': ['Q e p :: Want me to rewrite the Dockerfile or add a `docker-compose.yml` for local parity?', 'O rewrite the Dockerfile', 'O add a `docker-compose.yml` for local parity'],
    'ann_b': ['Q y p :: Want the Dockerfile to use a different base or tag?'],
  },
  {
    'n': 202,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: Deployment manifest vs Helm values',
    'note_b': 'yes_no: tweak one Deployment field (replicas or resources)',
    'text_a': 'Here’s what changed in this pass:\n\n[CODE]\n\nLocally that compiles. Next step is up to you.\n\nCluster is on 1.29; the probe keeps failing on `/readyz`.\n\nShall I draft a Deployment manifest, or a Helm values overlay?',
    'text_b': "Here’s what changed in this pass:\n\n[CODE]\n\nLocally that compiles. Next step is up to you.\n\nCluster is on 1.29; the probe keeps failing on `/readyz`.\n\nShall I change the Deployment's replicas or resources?",
    'ann_a': ['Q e p :: Shall I draft a Deployment manifest, or a Helm values overlay?', 'O a Deployment manifest', 'O a Helm values overlay'],
    'ann_b': ["Q y p :: Shall I change the Deployment's replicas or resources?"],
  },
  {
    'n': 203,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: multi-stage Dockerfile vs BuildKit cache mount',
    'note_b': 'yes_no: adjust one cache setting (key or scope)',
    'text_a': 'Quick dump of the failing log tail:\n\n[CODE]\n\nNothing else looks related.\n\nBuild times jumped after we added Prisma generate.\n\nPrefer a multi-stage Dockerfile or a BuildKit cache mount?',
    'text_b': 'Quick dump of the failing log tail:\n\n[CODE]\n\nNothing else looks related.\n\nBuild times jumped after we added Prisma generate.\n\nPrefer a different cache key or scope?',
    'ann_a': ['Q e p :: Prefer a multi-stage Dockerfile or a BuildKit cache mount?', 'O a multi-stage Dockerfile', 'O a BuildKit cache mount'],
    'ann_b': ['Q y p :: Prefer a different cache key or scope?'],
  },
  {
    'n': 204,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: NetworkPolicy vs Ingress rule',
    'note_b': 'yes_no: one Ingress tweak (path or host)',
    'text_a': 'Compared against `main` — the delta is small. Docs still mention the old flag name in two places.\n\nStaging pods can still reach the payment sidecar on 8443.\n\nWant a NetworkPolicy or an Ingress rule that locks that down?',
    'text_b': 'Compared against `main` — the delta is small. Docs still mention the old flag name in two places.\n\nStaging pods can still reach the payment sidecar on 8443.\n\nWant a different Ingress path or host?',
    'ann_a': ['Q e p :: Want a NetworkPolicy or an Ingress rule that locks that down?', 'O a NetworkPolicy', 'O an Ingress rule that locks that down'],
    'ann_b': ['Q y p :: Want a different Ingress path or host?'],
  },
  {
    'n': 205,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: init container script vs Job',
    'note_b': 'yes_no: rename/retarget one Job attribute',
    'text_a': 'I held off committing. The working tree is dirty only in the files we discussed.\n\nMigrations need to run once before the new Deployment rolls.\n\nShould I add an init container, or a one-shot Job?',
    'text_b': 'I held off committing. The working tree is dirty only in the files we discussed.\n\nMigrations need to run once before the new Deployment rolls.\n\nShould I use a different Job name or backoff?',
    'ann_a': ['Q e p :: Should I add an init container, or a one-shot Job?', 'O an init container', 'O a one-shot Job'],
    'ann_b': ['Q y p :: Should I use a different Job name or backoff?'],
  },
  {
    'n': 206,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: .dockerignore vs slim base image',
    'note_b': 'yes_no: one ignore-list attribute change',
    'text_a': 'Notes from the review thread are in [URL]. I mirrored the agreed approach locally.\n\nContext is 1.2GB because `node_modules` keeps sneaking in.\n\nWant me to tighten `.dockerignore`, or switch to a slim base image?',
    'text_b': 'Notes from the review thread are in [URL]. I mirrored the agreed approach locally.\n\nContext is 1.2GB because `node_modules` keeps sneaking in.\n\nWant a different ignore pattern or comment style in `.dockerignore`?',
    'ann_a': ['Q e p :: Want me to tighten `.dockerignore`, or switch to a slim base image?', 'O tighten `.dockerignore`', 'O switch to a slim base image'],
    'ann_b': ['Q y p :: Want a different ignore pattern or comment style in `.dockerignore`?'],
  },
  {
    'n': 207,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: HPA yaml vs VPA recommendation dump',
    'note_b': 'yes_no: one HPA threshold attribute',
    'text_a': 'Benchmark before/after on my laptop (n=20):\n- p50: 112ms → 87ms\n- p95: 240ms → 190ms\n\nCPU sits at 85% during the noon spike.\n\nI can write an HPA, or dump a VPA recommendation — which do you want?',
    'text_b': 'Benchmark before/after on my laptop (n=20):\n- p50: 112ms → 87ms\n- p95: 240ms → 190ms\n\nCPU sits at 85% during the noon spike.\n\nWant a different HPA target or minReplicas?',
    'ann_a': ['Q e p :: I can write an HPA, or dump a VPA recommendation — which do you want?', 'O write an HPA', 'O dump a VPA recommendation'],
    'ann_b': ['Q y p :: Want a different HPA target or minReplicas?'],
  },
  {
    'n': 208,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: docker run snippet vs k8s PodSpec',
    'note_b': 'yes_no: tweak one env/port attribute on the run',
    'text_a': 'Status after the last push:\n- unit tests green\n- typecheck clean\n- one integration flake still open\n\nQuick check: redis from the laptop works with TLS off.\n\nWant a `docker run` snippet or a PodSpec that mirrors it?',
    'text_b': 'Status after the last push:\n- unit tests green\n- typecheck clean\n- one integration flake still open\n\nQuick check: redis from the laptop works with TLS off.\n\nWant a different port or env var on the run?',
    'ann_a': ['Q e p :: Want a `docker run` snippet or a PodSpec that mirrors it?', 'O a `docker run` snippet', 'O a PodSpec that mirrors it'],
    'ann_b': ['Q y p :: Want a different port or env var on the run?'],
  },
  {
    'n': 209,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: up migration vs rollback script',
    'note_b': 'yes_no: one migration naming/attribute choice',
    'text_a': 'I traced it through the handler and the repository layer. The bug is localized; the surrounding refactor can wait.\n\nColumn `status` needs to become an enum without locking the table forever.\n\nWant the forward migration or a rollback script first?',
    'text_b': 'I traced it through the handler and the repository layer. The bug is localized; the surrounding refactor can wait.\n\nColumn `status` needs to become an enum without locking the table forever.\n\nWant a different migration name or timestamp?',
    'ann_a': ['Q e p :: Want the forward migration or a rollback script first?', 'O the forward migration', 'O a rollback script'],
    'ann_b': ['Q y p :: Want a different migration name or timestamp?'],
  },
  {
    'n': 210,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: Alembic revision vs raw SQL file',
    'note_b': 'yes_no: tweak one revision message attribute',
    'text_a': "Here’s what changed in this pass:\n\n[CODE]\n\nLocally that compiles. Next step is up to you.\n\nWe're on Alembic 1.13; the index on `orders(user_id)` is still missing.\n\nShall I generate an Alembic revision, or drop a raw SQL file in `migrations/`?",
    'text_b': "Here’s what changed in this pass:\n\n[CODE]\n\nLocally that compiles. Next step is up to you.\n\nWe're on Alembic 1.13; the index on `orders(user_id)` is still missing.\n\nShall I use a different revision message or branch label?",
    'ann_a': ['Q e p :: Shall I generate an Alembic revision, or drop a raw SQL file in `migrations/`?', 'O generate an Alembic revision', 'O drop a raw SQL file in `migrations/`'],
    'ann_b': ['Q y p :: Shall I use a different revision message or branch label?'],
  },
  {
    'n': 211,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: expand-contract plan vs single ALTER',
    'note_b': 'yes_no: one naming attribute on the new column',
    'text_a': 'Quick dump of the failing log tail:\n\n[CODE]\n\nNothing else looks related.\n\nNeed to rename `customer_id` → `account_id` with zero downtime.\n\nPrefer an expand-contract plan, or a single ALTER with a maintenance window?',
    'text_b': 'Quick dump of the failing log tail:\n\n[CODE]\n\nNothing else looks related.\n\nNeed to rename `customer_id` → `account_id` with zero downtime.\n\nPrefer a different temporary column name or default?',
    'ann_a': ['Q e p :: Prefer an expand-contract plan, or a single ALTER with a maintenance window?', 'O an expand-contract plan', 'O a single ALTER with a maintenance window'],
    'ann_b': ['Q y p :: Prefer a different temporary column name or default?'],
  },
  {
    'n': 212,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: Prisma migrate diff vs SQL dump review',
    'note_b': 'yes_no: adjust one Prisma field attribute',
    'text_a': 'Compared against `main` — the delta is small. Docs still mention the old flag name in two places.\n\nSchema drift showed up after the hotfix.\n\nWant me to run `prisma migrate diff`, or review the SQL dump side by side?',
    'text_b': 'Compared against `main` — the delta is small. Docs still mention the old flag name in two places.\n\nSchema drift showed up after the hotfix.\n\nWant a different Prisma field name or type on that column?',
    'ann_a': ['Q e p :: Want me to run `prisma migrate diff`, or review the SQL dump side by side?', 'O run `prisma migrate diff`', 'O review the SQL dump side by side'],
    'ann_b': ['Q y p :: Want a different Prisma field name or type on that column?'],
  },
  {
    'n': 213,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: backfill job vs CHECK constraint',
    'note_b': 'yes_no: one constraint attribute tweak',
    'text_a': 'I held off committing. The working tree is dirty only in the files we discussed.\n\n`email` is nullable in prod but the app already assumes NOT NULL.\n\nShould I write a backfill job, or add a CHECK constraint and fail loud?',
    'text_b': 'I held off committing. The working tree is dirty only in the files we discussed.\n\n`email` is nullable in prod but the app already assumes NOT NULL.\n\nShould I use a different constraint name or deferral?',
    'ann_a': ['Q e p :: Should I write a backfill job, or add a CHECK constraint and fail loud?', 'O write a backfill job', 'O add a CHECK constraint and fail loud'],
    'ann_b': ['Q y p :: Should I use a different constraint name or deferral?'],
  },
  {
    'n': 214,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: goose migration vs Flyway placeholder',
    'note_b': 'yes_no: one filename/version attribute',
    'text_a': 'Notes from the review thread are in [URL]. I mirrored the agreed approach locally.\n\nTeam is split on tooling for the ledger DB.\n\nWant a goose migration skeleton, or a Flyway `V__` placeholder?',
    'text_b': 'Notes from the review thread are in [URL]. I mirrored the agreed approach locally.\n\nTeam is split on tooling for the ledger DB.\n\nWant a different migration filename or version prefix?',
    'ann_a': ['Q e p :: Want a goose migration skeleton, or a Flyway `V__` placeholder?', 'O a goose migration skeleton', 'O a Flyway `V__` placeholder'],
    'ann_b': ['Q y p :: Want a different migration filename or version prefix?'],
  },
  {
    'n': 215,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: index DDL vs EXPLAIN plan writeup',
    'note_b': 'yes_no: tweak one index attribute',
    'text_a': 'Benchmark before/after on my laptop (n=20):\n- p50: 112ms → 87ms\n- p95: 240ms → 190ms\n\nThat `WHERE deleted_at IS NULL` filter is sequential-scanning 40M rows.\n\nWant the CREATE INDEX DDL, or an EXPLAIN plan writeup first?',
    'text_b': 'Benchmark before/after on my laptop (n=20):\n- p50: 112ms → 87ms\n- p95: 240ms → 190ms\n\nThat `WHERE deleted_at IS NULL` filter is sequential-scanning 40M rows.\n\nWant a different index name or fillfactor?',
    'ann_a': ['Q e p :: Want the CREATE INDEX DDL, or an EXPLAIN plan writeup first?', 'O the CREATE INDEX DDL', 'O an EXPLAIN plan writeup'],
    'ann_b': ['Q y p :: Want a different index name or fillfactor?'],
  },
  {
    'n': 216,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: OpenAPI snippet vs prose contract',
    'note_b': 'yes_no: one response field attribute',
    'text_a': 'Status after the last push:\n- unit tests green\n- typecheck clean\n- one integration flake still open\n\nClients disagree on whether `POST /invoices` returns 201 or 202.\n\nWant an OpenAPI snippet or a short prose contract?',
    'text_b': 'Status after the last push:\n- unit tests green\n- typecheck clean\n- one integration flake still open\n\nClients disagree on whether `POST /invoices` returns 201 or 202.\n\nWant a different status code or response body field?',
    'ann_a': ['Q e p :: Want an OpenAPI snippet or a short prose contract?', 'O an OpenAPI snippet', 'O a short prose contract'],
    'ann_b': ['Q y p :: Want a different status code or response body field?'],
  },
  {
    'n': 217,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: cursor pagination schema vs page+limit',
    'note_b': 'yes_no: rename one pagination attribute',
    'text_a': 'I traced it through the handler and the repository layer. The bug is localized; the surrounding refactor can wait.\n\nList endpoint will grow past 10k rows this quarter.\n\nShall I design cursor pagination, or stick with page+limit?',
    'text_b': 'I traced it through the handler and the repository layer. The bug is localized; the surrounding refactor can wait.\n\nList endpoint will grow past 10k rows this quarter.\n\nShall I use a different cursor param name or limit default?',
    'ann_a': ['Q e p :: Shall I design cursor pagination, or stick with page+limit?', 'O design cursor pagination', 'O stick with page+limit'],
    'ann_b': ['Q y p :: Shall I use a different cursor param name or limit default?'],
  },
  {
    'n': 218,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: error envelope RFC draft vs example JSON',
    'note_b': 'yes_no: one error-code attribute change',
    'text_a': 'Here’s what changed in this pass:\n\n[CODE]\n\nLocally that compiles. Next step is up to you.\n\nFrontend keeps parsing `message` vs `error` inconsistently.\n\nPrefer a tiny RFC-style error envelope, or just an example JSON payload?',
    'text_b': 'Here’s what changed in this pass:\n\n[CODE]\n\nLocally that compiles. Next step is up to you.\n\nFrontend keeps parsing `message` vs `error` inconsistently.\n\nPrefer a different error code or message key?',
    'ann_a': ['Q e p :: Prefer a tiny RFC-style error envelope, or just an example JSON payload?', 'O a tiny RFC-style error envelope', 'O just an example JSON payload'],
    'ann_b': ['Q y p :: Prefer a different error code or message key?'],
  },
  {
    'n': 219,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: idempotency-key middleware vs docs-only note',
    'note_b': 'yes_no: one header name/TTL attribute',
    'text_a': 'Quick dump of the failing log tail:\n\n[CODE]\n\nNothing else looks related.\n\nDouble-charges showed up when mobile retries on flaky networks.\n\nWant idempotency-key middleware, or a docs-only note for now?',
    'text_b': 'Quick dump of the failing log tail:\n\n[CODE]\n\nNothing else looks related.\n\nDouble-charges showed up when mobile retries on flaky networks.\n\nWant a different header name or TTL for the key?',
    'ann_a': ['Q e p :: Want idempotency-key middleware, or a docs-only note for now?', 'O idempotency-key middleware', 'O a docs-only note for now'],
    'ann_b': ['Q y p :: Want a different header name or TTL for the key?'],
  },
  {
    'n': 220,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: versioned URL path vs Accept header strategy',
    'note_b': 'yes_no: tweak one version string attribute',
    'text_a': 'Compared against `main` — the delta is small. Docs still mention the old flag name in two places.\n\nBreaking change lands next sprint; clients need a migration path.\n\nShould we version via URL path, or via `Accept` header?',
    'text_b': 'Compared against `main` — the delta is small. Docs still mention the old flag name in two places.\n\nBreaking change lands next sprint; clients need a migration path.\n\nShould we use a different version string or date label?',
    'ann_a': ['Q e p :: Should we version via URL path, or via `Accept` header?', 'O via URL path', 'O via `Accept` header'],
    'ann_b': ['Q y p :: Should we use a different version string or date label?'],
  },
  {
    'n': 221,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: webhook retry table vs signed payload sketch',
    'note_b': 'yes_no: one signature attribute tweak',
    'text_a': 'I held off committing. The working tree is dirty only in the files we discussed.\n\nPartner callbacks are dropping under load.\n\nWant a webhook retry table design, or a signed payload sketch?',
    'text_b': 'I held off committing. The working tree is dirty only in the files we discussed.\n\nPartner callbacks are dropping under load.\n\nWant a different signature header or hash algo?',
    'ann_a': ['Q e p :: Want a webhook retry table design, or a signed payload sketch?', 'O a webhook retry table design', 'O a signed payload sketch'],
    'ann_b': ['Q y p :: Want a different signature header or hash algo?'],
  },
  {
    'n': 222,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: rate-limit headers writeup vs middleware stub',
    'note_b': 'yes_no: one limit attribute change',
    'text_a': "Notes from the review thread are in [URL]. I mirrored the agreed approach locally.\n\nWe're getting 429s from the public API during demos.\n\nWant a rate-limit headers writeup, or a middleware stub?",
    'text_b': "Notes from the review thread are in [URL]. I mirrored the agreed approach locally.\n\nWe're getting 429s from the public API during demos.\n\nWant a different burst size or window length?",
    'ann_a': ['Q e p :: Want a rate-limit headers writeup, or a middleware stub?', 'O a rate-limit headers writeup', 'O a middleware stub'],
    'ann_b': ['Q y p :: Want a different burst size or window length?'],
  },
  {
    'n': 223,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: eslint flat config vs prettierrc',
    'note_b': 'yes_no: one rule severity/attribute',
    'text_a': 'Benchmark before/after on my laptop (n=20):\n- p50: 112ms → 87ms\n- p95: 240ms → 190ms\n\n`no-unused-vars` is fighting Prettier on the shared UI package.\n\nWant an eslint flat config, or a `.prettierrc` that owns formatting?',
    'text_b': 'Benchmark before/after on my laptop (n=20):\n- p50: 112ms → 87ms\n- p95: 240ms → 190ms\n\n`no-unused-vars` is fighting Prettier on the shared UI package.\n\nWant a different rule severity or option for `no-unused-vars`?',
    'ann_a': ['Q e p :: Want an eslint flat config, or a `.prettierrc` that owns formatting?', 'O an eslint flat config', 'O a `.prettierrc` that owns formatting'],
    'ann_b': ['Q y p :: Want a different rule severity or option for `no-unused-vars`?'],
  },
  {
    'n': 224,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: ruff.toml vs black+isort duo',
    'note_b': 'yes_no: tweak one line-length attribute',
    'text_a': 'Status after the last push:\n- unit tests green\n- typecheck clean\n- one integration flake still open\n\nPython formatting is inconsistent across services.\n\nShall I add a `ruff.toml`, or wire black+isort?',
    'text_b': 'Status after the last push:\n- unit tests green\n- typecheck clean\n- one integration flake still open\n\nPython formatting is inconsistent across services.\n\nShall I use a different line length or quote style?',
    'ann_a': ['Q e p :: Shall I add a `ruff.toml`, or wire black+isort?', 'O add a `ruff.toml`', 'O wire black+isort'],
    'ann_b': ['Q y p :: Shall I use a different line length or quote style?'],
  },
  {
    'n': 225,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: biome.json vs keep eslint+prettier',
    'note_b': 'yes_no: one biome formatter attribute',
    'text_a': 'I traced it through the handler and the repository layer. The bug is localized; the surrounding refactor can wait.\n\nLint CI is the slowest step in the PR pipeline.\n\nPrefer migrating to Biome, or keeping eslint+prettier with caching?',
    'text_b': 'I traced it through the handler and the repository layer. The bug is localized; the surrounding refactor can wait.\n\nLint CI is the slowest step in the PR pipeline.\n\nPrefer a different Biome indent or lineWidth?',
    'ann_a': ['Q e p :: Prefer migrating to Biome, or keeping eslint+prettier with caching?', 'O migrating to Biome', 'O keeping eslint+prettier with caching'],
    'ann_b': ['Q y p :: Prefer a different Biome indent or lineWidth?'],
  },
  {
    'n': 226,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: editorconfig vs clang-format file',
    'note_b': 'yes_no: one indent attribute change',
    'text_a': 'Here’s what changed in this pass:\n\n[CODE]\n\nLocally that compiles. Next step is up to you.\n\nC++ and TS disagree on tabs in the same repo.\n\nWant an `.editorconfig`, or a `.clang-format` for the native bits?',
    'text_b': 'Here’s what changed in this pass:\n\n[CODE]\n\nLocally that compiles. Next step is up to you.\n\nC++ and TS disagree on tabs in the same repo.\n\nWant a different indent width or style?',
    'ann_a': ['Q e p :: Want an `.editorconfig`, or a `.clang-format` for the native bits?', 'O an `.editorconfig`', 'O a `.clang-format` for the native bits'],
    'ann_b': ['Q y p :: Want a different indent width or style?'],
  },
  {
    'n': 227,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: pre-commit hook list vs lefthook.yml',
    'note_b': 'yes_no: rename one hook attribute',
    'text_a': 'Quick dump of the failing log tail:\n\n[CODE]\n\nNothing else looks related.\n\nPeople keep pushing unformatted JS.\n\nShould I draft a pre-commit hook list, or a `lefthook.yml`?',
    'text_b': 'Quick dump of the failing log tail:\n\n[CODE]\n\nNothing else looks related.\n\nPeople keep pushing unformatted JS.\n\nShould I use a different hook name or stage?',
    'ann_a': ['Q e p :: Should I draft a pre-commit hook list, or a `lefthook.yml`?', 'O a pre-commit hook list', 'O a `lefthook.yml`'],
    'ann_b': ['Q y p :: Should I use a different hook name or stage?'],
  },
  {
    'n': 228,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: golangci-lint yaml vs make fmt target',
    'note_b': 'yes_no: one linter enable attribute',
    'text_a': 'Compared against `main` — the delta is small. Docs still mention the old flag name in two places.\n\nGo packages disagree on `gofumpt` vs `gofmt`.\n\nWant a `golangci-lint` config, or a `make fmt` target?',
    'text_b': 'Compared against `main` — the delta is small. Docs still mention the old flag name in two places.\n\nGo packages disagree on `gofumpt` vs `gofmt`.\n\nWant a different enabled linter or severity?',
    'ann_a': ['Q e p :: Want a `golangci-lint` config, or a `make fmt` target?', 'O a `golangci-lint` config', 'O a `make fmt` target'],
    'ann_b': ['Q y p :: Want a different enabled linter or severity?'],
  },
  {
    'n': 229,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: oxlint migrate plan vs keep eslint disables',
    'note_b': 'yes_no: one disable-comment attribute',
    'text_a': "I held off committing. The working tree is dirty only in the files we discussed.\n\nWe're drowning in `eslint-disable` noise.\n\nWant an oxlint migrate plan, or a pass that only cleans the disables?",
    'text_b': "I held off committing. The working tree is dirty only in the files we discussed.\n\nWe're drowning in `eslint-disable` noise.\n\nWant a different disable scope or rule id in the comments?",
    'ann_a': ['Q e p :: Want an oxlint migrate plan, or a pass that only cleans the disables?', 'O an oxlint migrate plan', 'O a pass that only cleans the disables'],
    'ann_b': ['Q y p :: Want a different disable scope or rule id in the comments?'],
  },
  {
    'n': 230,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: changelog.md entry vs GitHub release body',
    'note_b': 'yes_no: tweak one release title/tag attribute',
    'text_a': 'Notes from the review thread are in [URL]. I mirrored the agreed approach locally.\n\nv2.4.0 ships the billing rewrite tomorrow.\n\nWant a `CHANGELOG.md` entry or a GitHub release body?',
    'text_b': 'Notes from the review thread are in [URL]. I mirrored the agreed approach locally.\n\nv2.4.0 ships the billing rewrite tomorrow.\n\nWant a different release title or tag name?',
    'ann_a': ['Q e p :: Want a `CHANGELOG.md` entry or a GitHub release body?', 'O a `CHANGELOG.md` entry', 'O a GitHub release body'],
    'ann_b': ['Q y p :: Want a different release title or tag name?'],
  },
  {
    'n': 231,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: Keep a Changelog format vs tweet-length blurb',
    'note_b': 'yes_no: one section heading attribute',
    'text_a': 'Benchmark before/after on my laptop (n=20):\n- p50: 112ms → 87ms\n- p95: 240ms → 190ms\n\nMarketing wants user-facing notes; eng wants commit fidelity.\n\nPrefer Keep a Changelog format, or a tweet-length blurb?',
    'text_b': 'Benchmark before/after on my laptop (n=20):\n- p50: 112ms → 87ms\n- p95: 240ms → 190ms\n\nMarketing wants user-facing notes; eng wants commit fidelity.\n\nPrefer a different section heading or emoji?',
    'ann_a': ['Q e p :: Prefer Keep a Changelog format, or a tweet-length blurb?', 'O Keep a Changelog format', 'O a tweet-length blurb'],
    'ann_b': ['Q y p :: Prefer a different section heading or emoji?'],
  },
  {
    'n': 232,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: breaking-changes section vs migration guide',
    'note_b': 'yes_no: one callout label attribute',
    'text_a': 'Status after the last push:\n- unit tests green\n- typecheck clean\n- one integration flake still open\n\nThe SDK drops Node 16 support.\n\nShall I write a breaking-changes section, or a full migration guide?',
    'text_b': 'Status after the last push:\n- unit tests green\n- typecheck clean\n- one integration flake still open\n\nThe SDK drops Node 16 support.\n\nShall I use a different callout label or severity badge?',
    'ann_a': ['Q e p :: Shall I write a breaking-changes section, or a full migration guide?', 'O a breaking-changes section', 'O a full migration guide'],
    'ann_b': ['Q y p :: Shall I use a different callout label or severity badge?'],
  },
  {
    'n': 233,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: conventional-commit summary vs bullet list from PRs',
    'note_b': 'yes_no: one grouping attribute',
    'text_a': 'I traced it through the handler and the repository layer. The bug is localized; the surrounding refactor can wait.\n\nI scraped the merged PRs since `v1.9.0`.\n\nWant a conventional-commit summary, or a bullet list grouped by area?',
    'text_b': 'I traced it through the handler and the repository layer. The bug is localized; the surrounding refactor can wait.\n\nI scraped the merged PRs since `v1.9.0`.\n\nWant a different grouping key or sort order?',
    'ann_a': ['Q e p :: Want a conventional-commit summary, or a bullet list grouped by area?', 'O a conventional-commit summary', 'O a bullet list grouped by area'],
    'ann_b': ['Q y p :: Want a different grouping key or sort order?'],
  },
  {
    'n': 234,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: release notes draft vs upgrade checklist',
    'note_b': 'yes_no: one checklist item wording attribute',
    'text_a': 'Here’s what changed in this pass:\n\n[CODE]\n\nLocally that compiles. Next step is up to you.\n\nOps asked what they must do on deploy night.\n\nWant release notes for customers, or an internal upgrade checklist?',
    'text_b': 'Here’s what changed in this pass:\n\n[CODE]\n\nLocally that compiles. Next step is up to you.\n\nOps asked what they must do on deploy night.\n\nWant a different checklist wording or checkbox style?',
    'ann_a': ['Q e p :: Want release notes for customers, or an internal upgrade checklist?', 'O release notes for customers', 'O an internal upgrade checklist'],
    'ann_b': ['Q y p :: Want a different checklist wording or checkbox style?'],
  },
  {
    'n': 235,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: changesets file vs manually edited notes',
    'note_b': 'yes_no: one changeset type/summary attribute',
    'text_a': 'Quick dump of the failing log tail:\n\n[CODE]\n\nNothing else looks related.\n\nMonorepo packages bump independently.\n\nShould I add a changeset file, or edit the notes by hand?',
    'text_b': 'Quick dump of the failing log tail:\n\n[CODE]\n\nNothing else looks related.\n\nMonorepo packages bump independently.\n\nShould I use a different changeset type or summary line?',
    'ann_a': ['Q e p :: Should I add a changeset file, or edit the notes by hand?', 'O add a changeset file', 'O edit the notes by hand'],
    'ann_b': ['Q y p :: Should I use a different changeset type or summary line?'],
  },
  {
    'n': 236,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: HTML email blast vs markdown for Discord',
    'note_b': 'yes_no: one subject/tone attribute',
    'text_a': 'Compared against `main` — the delta is small. Docs still mention the old flag name in two places.\n\nAnnounce channel wants something pasteable tonight.\n\nPrefer an HTML email blast, or markdown for Discord?',
    'text_b': 'Compared against `main` — the delta is small. Docs still mention the old flag name in two places.\n\nAnnounce channel wants something pasteable tonight.\n\nPrefer a different subject line or tone?',
    'ann_a': ['Q e p :: Prefer an HTML email blast, or markdown for Discord?', 'O an HTML email blast', 'O markdown for Discord'],
    'ann_b': ['Q y p :: Prefer a different subject line or tone?'],
  },
  {
    'n': 237,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: pnpm workspace yaml vs nx project.json',
    'note_b': 'yes_no: one package name/path attribute',
    'text_a': "I held off committing. The working tree is dirty only in the files we discussed.\n\nWe're splitting `packages/ui` out of the app.\n\nWant a `pnpm-workspace.yaml` update, or an Nx `project.json`?",
    'text_b': "I held off committing. The working tree is dirty only in the files we discussed.\n\nWe're splitting `packages/ui` out of the app.\n\nWant a different package name or path?",
    'ann_a': ['Q e p :: Want a `pnpm-workspace.yaml` update, or an Nx `project.json`?', 'O a `pnpm-workspace.yaml` update', 'O an Nx `project.json`'],
    'ann_b': ['Q y p :: Want a different package name or path?'],
  },
  {
    'n': 238,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: turborepo pipeline vs Makefile orchestration',
    'note_b': 'yes_no: one pipeline task attribute',
    'text_a': 'Notes from the review thread are in [URL]. I mirrored the agreed approach locally.\n\nCI rebuilds everything on every push.\n\nShall I sketch a Turborepo pipeline, or a Makefile that orchestrates filters?',
    'text_b': 'Notes from the review thread are in [URL]. I mirrored the agreed approach locally.\n\nCI rebuilds everything on every push.\n\nShall I use a different task name or dependsOn list?',
    'ann_a': ['Q e p :: Shall I sketch a Turborepo pipeline, or a Makefile that orchestrates filters?', 'O a Turborepo pipeline', 'O a Makefile that orchestrates filters'],
    'ann_b': ['Q y p :: Shall I use a different task name or dependsOn list?'],
  },
  {
    'n': 239,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: shared tsconfig base vs per-package configs',
    'note_b': 'yes_no: one compilerOption attribute',
    'text_a': 'Benchmark before/after on my laptop (n=20):\n- p50: 112ms → 87ms\n- p95: 240ms → 190ms\n\nTypecheck is failing only in `packages/api`.\n\nPrefer a shared `tsconfig.base.json`, or per-package configs?',
    'text_b': 'Benchmark before/after on my laptop (n=20):\n- p50: 112ms → 87ms\n- p95: 240ms → 190ms\n\nTypecheck is failing only in `packages/api`.\n\nPrefer a different `compilerOptions` strictness or module setting?',
    'ann_a': ['Q e p :: Prefer a shared `tsconfig.base.json`, or per-package configs?', 'O a shared `tsconfig.base.json`', 'O per-package configs'],
    'ann_b': ['Q y p :: Prefer a different `compilerOptions` strictness or module setting?'],
  },
  {
    'n': 240,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: changesets versioning doc vs syncpack rules',
    'note_b': 'yes_no: one version pin attribute',
    'text_a': 'Status after the last push:\n- unit tests green\n- typecheck clean\n- one integration flake still open\n\nThree packages pin conflicting `zod` majors.\n\nWant a changesets versioning doc, or syncpack rules?',
    'text_b': 'Status after the last push:\n- unit tests green\n- typecheck clean\n- one integration flake still open\n\nThree packages pin conflicting `zod` majors.\n\nWant a different pin strategy or range?',
    'ann_a': ['Q e p :: Want a changesets versioning doc, or syncpack rules?', 'O a changesets versioning doc', 'O syncpack rules'],
    'ann_b': ['Q y p :: Want a different pin strategy or range?'],
  },
  {
    'n': 241,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: bazel BUILD stub vs keep npm workspaces',
    'note_b': 'yes_no: one target name attribute',
    'text_a': 'I traced it through the handler and the repository layer. The bug is localized; the surrounding refactor can wait.\n\nBuild hermeticity came up in the architecture review.\n\nShould I stub a Bazel `BUILD` file, or document staying on npm workspaces?',
    'text_b': 'I traced it through the handler and the repository layer. The bug is localized; the surrounding refactor can wait.\n\nBuild hermeticity came up in the architecture review.\n\nShould I use a different Bazel target name or visibility?',
    'ann_a': ['Q e p :: Should I stub a Bazel `BUILD` file, or document staying on npm workspaces?', 'O stub a Bazel `BUILD` file', 'O document staying on npm workspaces'],
    'ann_b': ['Q y p :: Should I use a different Bazel target name or visibility?'],
  },
  {
    'n': 242,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: affected-graph diagram vs CI filter script',
    'note_b': 'yes_no: one diagram label attribute',
    'text_a': "Here’s what changed in this pass:\n\n[CODE]\n\nLocally that compiles. Next step is up to you.\n\nPeople don't know which packages a PR touches.\n\nWant an affected-graph diagram, or a CI filter script?",
    'text_b': "Here’s what changed in this pass:\n\n[CODE]\n\nLocally that compiles. Next step is up to you.\n\nPeople don't know which packages a PR touches.\n\nWant a different diagram label or color?",
    'ann_a': ['Q e p :: Want an affected-graph diagram, or a CI filter script?', 'O an affected-graph diagram', 'O a CI filter script'],
    'ann_b': ['Q y p :: Want a different diagram label or color?'],
  },
  {
    'n': 243,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: catalog protocol table vs yarn resolutions block',
    'note_b': 'yes_no: one catalog entry attribute',
    'text_a': 'Quick dump of the failing log tail:\n\n[CODE]\n\nNothing else looks related.\n\npnpm catalogs could centralize React versions.\n\nPrefer a catalog protocol table, or a yarn `resolutions` block?',
    'text_b': 'Quick dump of the failing log tail:\n\n[CODE]\n\nNothing else looks related.\n\npnpm catalogs could centralize React versions.\n\nPrefer a different catalog key or semver range?',
    'ann_a': ['Q e p :: Prefer a catalog protocol table, or a yarn `resolutions` block?', 'O a catalog protocol table', 'O a yarn `resolutions` block'],
    'ann_b': ['Q y p :: Prefer a different catalog key or semver range?'],
  },
  {
    'n': 244,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: zod schema vs hand-written interface',
    'note_b': 'yes_no: one field name/type attribute',
    'text_a': 'Compared against `main` — the delta is small. Docs still mention the old flag name in two places.\n\nThe webhook payload still arrives as `any`.\n\nWant a zod schema, or a hand-written interface?',
    'text_b': 'Compared against `main` — the delta is small. Docs still mention the old flag name in two places.\n\nThe webhook payload still arrives as `any`.\n\nWant a different field name or optional marker?',
    'ann_a': ['Q e p :: Want a zod schema, or a hand-written interface?', 'O a zod schema', 'O a hand-written interface'],
    'ann_b': ['Q y p :: Want a different field name or optional marker?'],
  },
  {
    'n': 245,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: branded Id type vs plain string alias',
    'note_b': 'yes_no: tweak one brand string attribute',
    'text_a': 'I held off committing. The working tree is dirty only in the files we discussed.\n\n`userId` and `orgId` keep getting swapped at call sites.\n\nShall I introduce branded Id types, or plain string aliases with better names?',
    'text_b': 'I held off committing. The working tree is dirty only in the files we discussed.\n\n`userId` and `orgId` keep getting swapped at call sites.\n\nShall I use a different brand string or phantom field name?',
    'ann_a': ['Q e p :: Shall I introduce branded Id types, or plain string aliases with better names?', 'O branded Id types', 'O plain string aliases with better names'],
    'ann_b': ['Q y p :: Shall I use a different brand string or phantom field name?'],
  },
  {
    'n': 246,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: satisfies-based config typing vs as const object',
    'note_b': 'yes_no: one literal type attribute',
    'text_a': 'Notes from the review thread are in [URL]. I mirrored the agreed approach locally.\n\nConfig keys are drifting from the runtime shape.\n\nPrefer `satisfies`-based typing, or an `as const` object export?',
    'text_b': 'Notes from the review thread are in [URL]. I mirrored the agreed approach locally.\n\nConfig keys are drifting from the runtime shape.\n\nPrefer a different literal union member or default?',
    'ann_a': ['Q e p :: Prefer `satisfies`-based typing, or an `as const` object export?', 'O `satisfies`-based typing', 'O an `as const` object export'],
    'ann_b': ['Q y p :: Prefer a different literal union member or default?'],
  },
  {
    'n': 247,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: Discriminated union sketch vs overload signatures',
    'note_b': 'yes_no: one discriminant attribute',
    'text_a': 'Benchmark before/after on my laptop (n=20):\n- p50: 112ms → 87ms\n- p95: 240ms → 190ms\n\n`Result` helpers are inconsistent across packages.\n\nWant a discriminated union sketch, or overload signatures?',
    'text_b': 'Benchmark before/after on my laptop (n=20):\n- p50: 112ms → 87ms\n- p95: 240ms → 190ms\n\n`Result` helpers are inconsistent across packages.\n\nWant a different discriminant key or tag value?',
    'ann_a': ['Q e p :: Want a discriminated union sketch, or overload signatures?', 'O a discriminated union sketch', 'O overload signatures'],
    'ann_b': ['Q y p :: Want a different discriminant key or tag value?'],
  },
  {
    'n': 248,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: type-only import cleanup PR vs ts-expect-error audit',
    'note_b': 'yes_no: one directive message attribute',
    'text_a': 'Status after the last push:\n- unit tests green\n- typecheck clean\n- one integration flake still open\n\nBuild is clean but `tsc --noEmit` still warns in CI.\n\nShould I open a type-only import cleanup, or an `@ts-expect-error` audit?',
    'text_b': 'Status after the last push:\n- unit tests green\n- typecheck clean\n- one integration flake still open\n\nBuild is clean but `tsc --noEmit` still warns in CI.\n\nShould I use a different directive message or line span?',
    'ann_a': ['Q e p :: Should I open a type-only import cleanup, or an `@ts-expect-error` audit?', 'O a type-only import cleanup', 'O an `@ts-expect-error` audit'],
    'ann_b': ['Q y p :: Should I use a different directive message or line span?'],
  },
  {
    'n': 249,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: Generated OpenAPI types vs hand-maintained DTO',
    'note_b': 'yes_no: one export name attribute',
    'text_a': 'I traced it through the handler and the repository layer. The bug is localized; the surrounding refactor can wait.\n\nThe client types lag the server by two releases.\n\nWant generated OpenAPI types, or a hand-maintained DTO module?',
    'text_b': 'I traced it through the handler and the repository layer. The bug is localized; the surrounding refactor can wait.\n\nThe client types lag the server by two releases.\n\nWant a different export name or namespace?',
    'ann_a': ['Q e p :: Want generated OpenAPI types, or a hand-maintained DTO module?', 'O generated OpenAPI types', 'O a hand-maintained DTO module'],
    'ann_b': ['Q y p :: Want a different export name or namespace?'],
  },
  {
    'n': 250,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: Conditional type walkthrough vs simplified Mapped type',
    'note_b': 'yes_no: one utility type name attribute',
    'text_a': 'Here’s what changed in this pass:\n\n[CODE]\n\nLocally that compiles. Next step is up to you.\n\nThe `DeepPartial` helper is scaring newcomers.\n\nPrefer a conditional-type walkthrough, or a simplified mapped type?',
    'text_b': 'Here’s what changed in this pass:\n\n[CODE]\n\nLocally that compiles. Next step is up to you.\n\nThe `DeepPartial` helper is scaring newcomers.\n\nPrefer a different utility type name or generic parameter?',
    'ann_a': ['Q e p :: Prefer a conditional-type walkthrough, or a simplified mapped type?', 'O a conditional-type walkthrough', 'O a simplified mapped type'],
    'ann_b': ['Q y p :: Prefer a different utility type name or generic parameter?'],
  },
  {
    'n': 251,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: CSS module vs Tailwind utility block',
    'note_b': 'yes_no: one spacing/color attribute',
    'text_a': 'Quick dump of the failing log tail:\n\n[CODE]\n\nNothing else looks related.\n\nThe card hover state is fighting global styles.\n\nWant a CSS module, or a Tailwind utility block?',
    'text_b': 'Quick dump of the failing log tail:\n\n[CODE]\n\nNothing else looks related.\n\nThe card hover state is fighting global styles.\n\nWant a different spacing scale or color token?',
    'ann_a': ['Q e p :: Want a CSS module, or a Tailwind utility block?', 'O a CSS module', 'O a Tailwind utility block'],
    'ann_b': ['Q y p :: Want a different spacing scale or color token?'],
  },
  {
    'n': 252,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: container-query layout vs media-query rewrite',
    'note_b': 'yes_no: one breakpoint attribute',
    'text_a': 'Compared against `main` — the delta is small. Docs still mention the old flag name in two places.\n\nSidebar collapses too early on wide zoom levels.\n\nShall I switch to container queries, or rewrite the media queries?',
    'text_b': 'Compared against `main` — the delta is small. Docs still mention the old flag name in two places.\n\nSidebar collapses too early on wide zoom levels.\n\nShall I use a different breakpoint or min-width?',
    'ann_a': ['Q e p :: Shall I switch to container queries, or rewrite the media queries?', 'O switch to container queries', 'O rewrite the media queries'],
    'ann_b': ['Q y p :: Shall I use a different breakpoint or min-width?'],
  },
  {
    'n': 253,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: design-token JSON vs CSS variables sheet',
    'note_b': 'yes_no: one token name/value attribute',
    'text_a': 'I held off committing. The working tree is dirty only in the files we discussed.\n\nDark mode tokens are duplicated in three places.\n\nPrefer a design-token JSON, or a single CSS variables sheet?',
    'text_b': 'I held off committing. The working tree is dirty only in the files we discussed.\n\nDark mode tokens are duplicated in three places.\n\nPrefer a different token name or hex value?',
    'ann_a': ['Q e p :: Prefer a design-token JSON, or a single CSS variables sheet?', 'O a design-token JSON', 'O a single CSS variables sheet'],
    'ann_b': ['Q y p :: Prefer a different token name or hex value?'],
  },
  {
    'n': 254,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: @layer reset vs unlayered utilities',
    'note_b': 'yes_no: one specificity/selector attribute',
    'text_a': 'Notes from the review thread are in [URL]. I mirrored the agreed approach locally.\n\nSpecificity wars between reset and components.\n\nWant an `@layer` reset, or unlayered utilities with clearer names?',
    'text_b': 'Notes from the review thread are in [URL]. I mirrored the agreed approach locally.\n\nSpecificity wars between reset and components.\n\nWant a different selector or specificity strategy?',
    'ann_a': ['Q e p :: Want an `@layer` reset, or unlayered utilities with clearer names?', 'O an `@layer` reset', 'O unlayered utilities with clearer names'],
    'ann_b': ['Q y p :: Want a different selector or specificity strategy?'],
  },
  {
    'n': 255,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: animation keyframes file vs transition-only polish',
    'note_b': 'yes_no: one duration/easing attribute',
    'text_a': 'Benchmark before/after on my laptop (n=20):\n- p50: 112ms → 87ms\n- p95: 240ms → 190ms\n\nThe modal entrance feels abrupt.\n\nShould I add a keyframes file, or keep transition-only polish?',
    'text_b': 'Benchmark before/after on my laptop (n=20):\n- p50: 112ms → 87ms\n- p95: 240ms → 190ms\n\nThe modal entrance feels abrupt.\n\nShould I use a different duration or easing?',
    'ann_a': ['Q e p :: Should I add a keyframes file, or keep transition-only polish?', 'O add a keyframes file', 'O keep transition-only polish'],
    'ann_b': ['Q y p :: Should I use a different duration or easing?'],
  },
  {
    'n': 256,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: PostCSS nesting config vs plain SCSS partial',
    'note_b': 'yes_no: one nesting depth/name attribute',
    'text_a': 'Status after the last push:\n- unit tests green\n- typecheck clean\n- one integration flake still open\n\nNested selectors are getting hard to scan.\n\nWant a PostCSS nesting config, or a plain SCSS partial?',
    'text_b': 'Status after the last push:\n- unit tests green\n- typecheck clean\n- one integration flake still open\n\nNested selectors are getting hard to scan.\n\nWant a different nesting depth or BEM name?',
    'ann_a': ['Q e p :: Want a PostCSS nesting config, or a plain SCSS partial?', 'O a PostCSS nesting config', 'O a plain SCSS partial'],
    'ann_b': ['Q y p :: Want a different nesting depth or BEM name?'],
  },
  {
    'n': 257,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: fluid type scale calc vs fixed rem steps',
    'note_b': 'yes_no: one clamp min/max attribute',
    'text_a': 'I traced it through the handler and the repository layer. The bug is localized; the surrounding refactor can wait.\n\nHeadings look huge on ultrawide monitors.\n\nPrefer a fluid type scale with `clamp`, or fixed rem steps?',
    'text_b': 'I traced it through the handler and the repository layer. The bug is localized; the surrounding refactor can wait.\n\nHeadings look huge on ultrawide monitors.\n\nPrefer a different `clamp` min or max?',
    'ann_a': ['Q e p :: Prefer a fluid type scale with `clamp`, or fixed rem steps?', 'O a fluid type scale with `clamp`', 'O fixed rem steps'],
    'ann_b': ['Q y p :: Prefer a different `clamp` min or max?'],
  },
  {
    'n': 258,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: Playwright config vs first smoke spec',
    'note_b': 'yes_no: one timeout/project attribute',
    'text_a': 'Here’s what changed in this pass:\n\n[CODE]\n\nLocally that compiles. Next step is up to you.\n\nWe still have zero E2E coverage on checkout.\n\nWant a `playwright.config.ts`, or the first smoke spec?',
    'text_b': 'Here’s what changed in this pass:\n\n[CODE]\n\nLocally that compiles. Next step is up to you.\n\nWe still have zero E2E coverage on checkout.\n\nWant a different timeout or project name?',
    'ann_a': ['Q e p :: Want a `playwright.config.ts`, or the first smoke spec?', 'O a `playwright.config.ts`', 'O the first smoke spec'],
    'ann_b': ['Q y p :: Want a different timeout or project name?'],
  },
  {
    'n': 259,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: page-object helpers vs inline locators',
    'note_b': 'yes_no: one locator strategy attribute',
    'text_a': 'Quick dump of the failing log tail:\n\n[CODE]\n\nNothing else looks related.\n\nSelectors broke after the redesign.\n\nShall I introduce page-object helpers, or keep inline locators with `getByRole`?',
    'text_b': 'Quick dump of the failing log tail:\n\n[CODE]\n\nNothing else looks related.\n\nSelectors broke after the redesign.\n\nShall I use a different role name or test id?',
    'ann_a': ['Q e p :: Shall I introduce page-object helpers, or keep inline locators with `getByRole`?', 'O page-object helpers', 'O keep inline locators with `getByRole`'],
    'ann_b': ['Q y p :: Shall I use a different role name or test id?'],
  },
  {
    'n': 260,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: trace-on-retry setup vs video capture toggle',
    'note_b': 'yes_no: one artifact retention attribute',
    'text_a': 'Compared against `main` — the delta is small. Docs still mention the old flag name in two places.\n\nFlakes are impossible to debug without artifacts.\n\nPrefer trace-on-retry, or always-on video?',
    'text_b': 'Compared against `main` — the delta is small. Docs still mention the old flag name in two places.\n\nFlakes are impossible to debug without artifacts.\n\nPrefer a different artifact retention or path?',
    'ann_a': ['Q e p :: Prefer trace-on-retry, or always-on video?', 'O trace-on-retry', 'O always-on video'],
    'ann_b': ['Q y p :: Prefer a different artifact retention or path?'],
  },
  {
    'n': 261,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: auth storageState fixture vs login-per-test',
    'note_b': 'yes_no: one cookie/storage key attribute',
    'text_a': 'I held off committing. The working tree is dirty only in the files we discussed.\n\nLogin flow costs 8s per test.\n\nWant a `storageState` fixture, or login-per-test for isolation?',
    'text_b': 'I held off committing. The working tree is dirty only in the files we discussed.\n\nLogin flow costs 8s per test.\n\nWant a different storage key or cookie name?',
    'ann_a': ['Q e p :: Want a `storageState` fixture, or login-per-test for isolation?', 'O a `storageState` fixture', 'O login-per-test for isolation'],
    'ann_b': ['Q y p :: Want a different storage key or cookie name?'],
  },
  {
    'n': 262,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: API request fixture vs UI-only path',
    'note_b': 'yes_no: one baseURL/header attribute',
    'text_a': 'Notes from the review thread are in [URL]. I mirrored the agreed approach locally.\n\nSeeding via the UI is slow and brittle.\n\nShould I add an API request fixture, or keep a UI-only path?',
    'text_b': 'Notes from the review thread are in [URL]. I mirrored the agreed approach locally.\n\nSeeding via the UI is slow and brittle.\n\nShould I use a different baseURL or auth header?',
    'ann_a': ['Q e p :: Should I add an API request fixture, or keep a UI-only path?', 'O an API request fixture', 'O keep a UI-only path'],
    'ann_b': ['Q y p :: Should I use a different baseURL or auth header?'],
  },
  {
    'n': 263,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: visual snapshot suite vs axe accessibility scan',
    'note_b': 'yes_no: one snapshot threshold attribute',
    'text_a': 'Benchmark before/after on my laptop (n=20):\n- p50: 112ms → 87ms\n- p95: 240ms → 190ms\n\nDesign wants regression coverage before the brand refresh.\n\nWant a visual snapshot suite, or an axe accessibility scan?',
    'text_b': 'Benchmark before/after on my laptop (n=20):\n- p50: 112ms → 87ms\n- p95: 240ms → 190ms\n\nDesign wants regression coverage before the brand refresh.\n\nWant a different snapshot threshold or name?',
    'ann_a': ['Q e p :: Want a visual snapshot suite, or an axe accessibility scan?', 'O a visual snapshot suite', 'O an axe accessibility scan'],
    'ann_b': ['Q y p :: Want a different snapshot threshold or name?'],
  },
  {
    'n': 264,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: shard matrix for CI vs serial local script',
    'note_b': 'yes_no: one shard count/workers attribute',
    'text_a': 'Status after the last push:\n- unit tests green\n- typecheck clean\n- one integration flake still open\n\nThe suite takes 22 minutes unsharded.\n\nPrefer a shard matrix for CI, or a serial local script?',
    'text_b': 'Status after the last push:\n- unit tests green\n- typecheck clean\n- one integration flake still open\n\nThe suite takes 22 minutes unsharded.\n\nPrefer a different shard count or workers setting?',
    'ann_a': ['Q e p :: Prefer a shard matrix for CI, or a serial local script?', 'O a shard matrix for CI', 'O a serial local script'],
    'ann_b': ['Q y p :: Prefer a different shard count or workers setting?'],
  },
  {
    'n': 265,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: cache-aside wrapper vs read-through helper',
    'note_b': 'yes_no: one TTL/key attribute',
    'text_a': 'I traced it through the handler and the repository layer. The bug is localized; the surrounding refactor can wait.\n\nSession lookups hammer Postgres under load.\n\nWant a cache-aside wrapper, or a read-through helper?',
    'text_b': 'I traced it through the handler and the repository layer. The bug is localized; the surrounding refactor can wait.\n\nSession lookups hammer Postgres under load.\n\nWant a different TTL or key prefix?',
    'ann_a': ['Q e p :: Want a cache-aside wrapper, or a read-through helper?', 'O a cache-aside wrapper', 'O a read-through helper'],
    'ann_b': ['Q y p :: Want a different TTL or key prefix?'],
  },
  {
    'n': 266,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: Redis Streams consumer sketch vs pub/sub demo',
    'note_b': 'yes_no: one stream/group name attribute',
    'text_a': 'Here’s what changed in this pass:\n\n[CODE]\n\nLocally that compiles. Next step is up to you.\n\nWe need fan-out without Kafka for now.\n\nShall I sketch a Streams consumer, or a pub/sub demo?',
    'text_b': 'Here’s what changed in this pass:\n\n[CODE]\n\nLocally that compiles. Next step is up to you.\n\nWe need fan-out without Kafka for now.\n\nShall I use a different stream name or consumer group?',
    'ann_a': ['Q e p :: Shall I sketch a Streams consumer, or a pub/sub demo?', 'O a Streams consumer', 'O a pub/sub demo'],
    'ann_b': ['Q y p :: Shall I use a different stream name or consumer group?'],
  },
  {
    'n': 267,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: Lua rate-limit script vs sliding-window notes',
    'note_b': 'yes_no: one window size attribute',
    'text_a': 'Quick dump of the failing log tail:\n\n[CODE]\n\nNothing else looks related.\n\nNaive INCR counters reset awkwardly at midnight.\n\nPrefer a Lua rate-limit script, or sliding-window design notes?',
    'text_b': 'Quick dump of the failing log tail:\n\n[CODE]\n\nNothing else looks related.\n\nNaive INCR counters reset awkwardly at midnight.\n\nPrefer a different window size or counter key?',
    'ann_a': ['Q e p :: Prefer a Lua rate-limit script, or sliding-window design notes?', 'O a Lua rate-limit script', 'O sliding-window design notes'],
    'ann_b': ['Q y p :: Prefer a different window size or counter key?'],
  },
  {
    'n': 268,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: redis.conf snippet vs ElastiCache parameter group',
    'note_b': 'yes_no: one maxmemory policy attribute',
    'text_a': 'Compared against `main` — the delta is small. Docs still mention the old flag name in two places.\n\nOOM kills started after the catalog import.\n\nWant a `redis.conf` snippet, or an ElastiCache parameter group?',
    'text_b': 'Compared against `main` — the delta is small. Docs still mention the old flag name in two places.\n\nOOM kills started after the catalog import.\n\nWant a different `maxmemory` policy or limit?',
    'ann_a': ['Q e p :: Want a `redis.conf` snippet, or an ElastiCache parameter group?', 'O a `redis.conf` snippet', 'O an ElastiCache parameter group'],
    'ann_b': ['Q y p :: Want a different `maxmemory` policy or limit?'],
  },
  {
    'n': 269,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: SCAN-based cleanup job vs KEYS ban lint rule',
    'note_b': 'yes_no: one SCAN count attribute',
    'text_a': 'I held off committing. The working tree is dirty only in the files we discussed.\n\n`KEYS *` showed up in a debug script that hit prod.\n\nShould I write a SCAN-based cleanup job, or a lint rule that bans KEYS?',
    'text_b': 'I held off committing. The working tree is dirty only in the files we discussed.\n\n`KEYS *` showed up in a debug script that hit prod.\n\nShould I use a different SCAN count or match pattern?',
    'ann_a': ['Q e p :: Should I write a SCAN-based cleanup job, or a lint rule that bans KEYS?', 'O a SCAN-based cleanup job', 'O a lint rule that bans KEYS'],
    'ann_b': ['Q y p :: Should I use a different SCAN count or match pattern?'],
  },
  {
    'n': 270,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: Redlock notes vs DB advisory locks',
    'note_b': 'yes_no: one lock TTL/key attribute',
    'text_a': 'Notes from the review thread are in [URL]. I mirrored the agreed approach locally.\n\nTwo workers still race on invoice numbering.\n\nWant Redlock notes, or stick with DB advisory locks?',
    'text_b': 'Notes from the review thread are in [URL]. I mirrored the agreed approach locally.\n\nTwo workers still race on invoice numbering.\n\nWant a different lock TTL or key name?',
    'ann_a': ['Q e p :: Want Redlock notes, or stick with DB advisory locks?', 'O Redlock notes', 'O stick with DB advisory locks'],
    'ann_b': ['Q y p :: Want a different lock TTL or key name?'],
  },
  {
    'n': 271,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: redis-cli MONITOR walkthrough vs SLOWLOG dump',
    'note_b': 'yes_no: one latency threshold attribute',
    'text_a': 'Benchmark before/after on my laptop (n=20):\n- p50: 112ms → 87ms\n- p95: 240ms → 190ms\n\np99 latency spiked after the deploy.\n\nPrefer a MONITOR walkthrough, or a SLOWLOG dump?',
    'text_b': 'Benchmark before/after on my laptop (n=20):\n- p50: 112ms → 87ms\n- p95: 240ms → 190ms\n\np99 latency spiked after the deploy.\n\nPrefer a different latency threshold or sample size?',
    'ann_a': ['Q e p :: Prefer a MONITOR walkthrough, or a SLOWLOG dump?', 'O a MONITOR walkthrough', 'O a SLOWLOG dump'],
    'ann_b': ['Q y p :: Prefer a different latency threshold or sample size?'],
  },
  {
    'n': 272,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: schema SDL patch vs resolver stub',
    'note_b': 'yes_no: one field name/nullability attribute',
    'text_a': 'Status after the last push:\n- unit tests green\n- typecheck clean\n- one integration flake still open\n\n`User.profile` is still a nested N+1.\n\nWant a schema SDL patch, or a resolver stub with DataLoader?',
    'text_b': 'Status after the last push:\n- unit tests green\n- typecheck clean\n- one integration flake still open\n\n`User.profile` is still a nested N+1.\n\nWant a different field name or nullability?',
    'ann_a': ['Q e p :: Want a schema SDL patch, or a resolver stub with DataLoader?', 'O a schema SDL patch', 'O a resolver stub with DataLoader'],
    'ann_b': ['Q y p :: Want a different field name or nullability?'],
  },
  {
    'n': 273,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: persisted-query allowlist vs automatic persisted queries',
    'note_b': 'yes_no: one hash/version attribute',
    'text_a': "I traced it through the handler and the repository layer. The bug is localized; the surrounding refactor can wait.\n\nCDN can't cache POSTs to `/graphql` well.\n\nShall I add a persisted-query allowlist, or automatic persisted queries?",
    'text_b': "I traced it through the handler and the repository layer. The bug is localized; the surrounding refactor can wait.\n\nCDN can't cache POSTs to `/graphql` well.\n\nShall I use a different query hash or version?",
    'ann_a': ['Q e p :: Shall I add a persisted-query allowlist, or automatic persisted queries?', 'O a persisted-query allowlist', 'O automatic persisted queries'],
    'ann_b': ['Q y p :: Shall I use a different query hash or version?'],
  },
  {
    'n': 274,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: federation subgraph checklist vs monolith schema cut',
    'note_b': 'yes_no: one subgraph name attribute',
    'text_a': 'Here’s what changed in this pass:\n\n[CODE]\n\nLocally that compiles. Next step is up to you.\n\nTeam boundaries want ownership of Product vs Order.\n\nPrefer a federation subgraph checklist, or a monolith schema cut plan?',
    'text_b': 'Here’s what changed in this pass:\n\n[CODE]\n\nLocally that compiles. Next step is up to you.\n\nTeam boundaries want ownership of Product vs Order.\n\nPrefer a different subgraph name or key field?',
    'ann_a': ['Q e p :: Prefer a federation subgraph checklist, or a monolith schema cut plan?', 'O a federation subgraph checklist', 'O a monolith schema cut plan'],
    'ann_b': ['Q y p :: Prefer a different subgraph name or key field?'],
  },
  {
    'n': 275,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: GraphiQL embed vs Voyager diagram',
    'note_b': 'yes_no: one playground theme/path attribute',
    'text_a': 'Quick dump of the failing log tail:\n\n[CODE]\n\nNothing else looks related.\n\nOnboarding new FE folks is slow without a browseable schema.\n\nWant a GraphiQL embed, or a Voyager diagram?',
    'text_b': 'Quick dump of the failing log tail:\n\n[CODE]\n\nNothing else looks related.\n\nOnboarding new FE folks is slow without a browseable schema.\n\nWant a different playground theme or path?',
    'ann_a': ['Q e p :: Want a GraphiQL embed, or a Voyager diagram?', 'O a GraphiQL embed', 'O a Voyager diagram'],
    'ann_b': ['Q y p :: Want a different playground theme or path?'],
  },
  {
    'n': 276,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: @defer/@stream RFC notes vs client fragment strategy',
    'note_b': 'yes_no: one directive label attribute',
    'text_a': 'Compared against `main` — the delta is small. Docs still mention the old flag name in two places.\n\nHomepage query is 1.8s because of reviews.\n\nShould I draft `@defer`/`@stream` notes, or a client fragment strategy?',
    'text_b': 'Compared against `main` — the delta is small. Docs still mention the old flag name in two places.\n\nHomepage query is 1.8s because of reviews.\n\nShould I use a different defer label or fragment name?',
    'ann_a': ['Q e p :: Should I draft `@defer`/`@stream` notes, or a client fragment strategy?', 'O `@defer`/`@stream` notes', 'O a client fragment strategy'],
    'ann_b': ['Q y p :: Should I use a different defer label or fragment name?'],
  },
  {
    'n': 277,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: complexity limit plugin vs depth-limit only',
    'note_b': 'yes_no: one cost/depth attribute',
    'text_a': 'I held off committing. The working tree is dirty only in the files we discussed.\n\nA nested friends-of-friends query took down staging.\n\nWant a complexity limit plugin, or depth-limit only?',
    'text_b': 'I held off committing. The working tree is dirty only in the files we discussed.\n\nA nested friends-of-friends query took down staging.\n\nWant a different cost budget or max depth?',
    'ann_a': ['Q e p :: Want a complexity limit plugin, or depth-limit only?', 'O a complexity limit plugin', 'O depth-limit only'],
    'ann_b': ['Q y p :: Want a different cost budget or max depth?'],
  },
  {
    'n': 278,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: codegen.yml vs hand-written document types',
    'note_b': 'yes_no: one plugin/output path attribute',
    'text_a': 'Notes from the review thread are in [URL]. I mirrored the agreed approach locally.\n\nOperation types drift from the schema nightly.\n\nPrefer a `codegen.yml`, or hand-written document types?',
    'text_b': 'Notes from the review thread are in [URL]. I mirrored the agreed approach locally.\n\nOperation types drift from the schema nightly.\n\nPrefer a different codegen plugin or output path?',
    'ann_a': ['Q e p :: Prefer a `codegen.yml`, or hand-written document types?', 'O a `codegen.yml`', 'O hand-written document types'],
    'ann_b': ['Q y p :: Prefer a different codegen plugin or output path?'],
  },
  {
    'n': 279,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: Sentry init snippet vs source-map upload job',
    'note_b': 'yes_no: one DSN/environment attribute',
    'text_a': 'Benchmark before/after on my laptop (n=20):\n- p50: 112ms → 87ms\n- p95: 240ms → 190ms\n\nProduction errors lack stack frames after minify.\n\nWant a Sentry init snippet, or a source-map upload job?',
    'text_b': 'Benchmark before/after on my laptop (n=20):\n- p50: 112ms → 87ms\n- p95: 240ms → 190ms\n\nProduction errors lack stack frames after minify.\n\nWant a different DSN env var or environment tag?',
    'ann_a': ['Q e p :: Want a Sentry init snippet, or a source-map upload job?', 'O a Sentry init snippet', 'O a source-map upload job'],
    'ann_b': ['Q y p :: Want a different DSN env var or environment tag?'],
  },
  {
    'n': 280,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: beforeSend scrubber vs ignoreErrors list',
    'note_b': 'yes_no: one scrub field attribute',
    'text_a': 'Status after the last push:\n- unit tests green\n- typecheck clean\n- one integration flake still open\n\nPII is leaking into breadcrumbs on checkout.\n\nShall I write a `beforeSend` scrubber, or an `ignoreErrors` list?',
    'text_b': 'Status after the last push:\n- unit tests green\n- typecheck clean\n- one integration flake still open\n\nPII is leaking into breadcrumbs on checkout.\n\nShall I scrub a different field or cookie name?',
    'ann_a': ['Q e p :: Shall I write a `beforeSend` scrubber, or an `ignoreErrors` list?', 'O a `beforeSend` scrubber', 'O an `ignoreErrors` list'],
    'ann_b': ['Q y p :: Shall I scrub a different field or cookie name?'],
  },
  {
    'n': 281,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: performance tracing sample config vs replay setup',
    'note_b': 'yes_no: one sample rate attribute',
    'text_a': "I traced it through the handler and the repository layer. The bug is localized; the surrounding refactor can wait.\n\nWe can't tell if the spike is FE or API.\n\nPrefer performance tracing config, or Session Replay setup?",
    'text_b': "I traced it through the handler and the repository layer. The bug is localized; the surrounding refactor can wait.\n\nWe can't tell if the spike is FE or API.\n\nPrefer a different traces sample rate or replay rate?",
    'ann_a': ['Q e p :: Prefer performance tracing config, or Session Replay setup?', 'O performance tracing config', 'O Session Replay setup'],
    'ann_b': ['Q y p :: Prefer a different traces sample rate or replay rate?'],
  },
  {
    'n': 282,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: alert rule JSON vs Slack notification mapping',
    'note_b': 'yes_no: one threshold/channel attribute',
    'text_a': 'Here’s what changed in this pass:\n\n[CODE]\n\nLocally that compiles. Next step is up to you.\n\nOn-call wants noise down before the holiday freeze.\n\nWant alert rule JSON, or a Slack notification mapping?',
    'text_b': 'Here’s what changed in this pass:\n\n[CODE]\n\nLocally that compiles. Next step is up to you.\n\nOn-call wants noise down before the holiday freeze.\n\nWant a different alert threshold or channel?',
    'ann_a': ['Q e p :: Want alert rule JSON, or a Slack notification mapping?', 'O alert rule JSON', 'O a Slack notification mapping'],
    'ann_b': ['Q y p :: Want a different alert threshold or channel?'],
  },
  {
    'n': 283,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: release health dashboard notes vs commit linking guide',
    'note_b': 'yes_no: one release name attribute',
    'text_a': "Quick dump of the failing log tail:\n\n[CODE]\n\nNothing else looks related.\n\nWe can't see which deploy introduced the regression.\n\nShould I draft release health notes, or a commit linking guide?",
    'text_b': "Quick dump of the failing log tail:\n\n[CODE]\n\nNothing else looks related.\n\nWe can't see which deploy introduced the regression.\n\nShould I use a different release name or dist?",
    'ann_a': ['Q e p :: Should I draft release health notes, or a commit linking guide?', 'O release health notes', 'O a commit linking guide'],
    'ann_b': ['Q y p :: Should I use a different release name or dist?'],
  },
  {
    'n': 284,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: custom fingerprint rule vs issue merge script',
    'note_b': 'yes_no: one fingerprint component attribute',
    'text_a': 'Compared against `main` — the delta is small. Docs still mention the old flag name in two places.\n\nSame bug fans out into 40 issues by URL.\n\nWant a custom fingerprint rule, or an issue merge script?',
    'text_b': 'Compared against `main` — the delta is small. Docs still mention the old flag name in two places.\n\nSame bug fans out into 40 issues by URL.\n\nWant a different fingerprint component or separator?',
    'ann_a': ['Q e p :: Want a custom fingerprint rule, or an issue merge script?', 'O a custom fingerprint rule', 'O an issue merge script'],
    'ann_b': ['Q y p :: Want a different fingerprint component or separator?'],
  },
  {
    'n': 285,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: Sentry SDK upgrade changelog vs pin-and-wait note',
    'note_b': 'yes_no: one SDK version/tag attribute',
    'text_a': 'I held off committing. The working tree is dirty only in the files we discussed.\n\nv8 of the JS SDK deprecates our transport.\n\nPrefer an upgrade changelog, or a pin-and-wait note?',
    'text_b': 'I held off committing. The working tree is dirty only in the files we discussed.\n\nv8 of the JS SDK deprecates our transport.\n\nPrefer a different SDK version or npm tag?',
    'ann_a': ['Q e p :: Prefer an upgrade changelog, or a pin-and-wait note?', 'O an upgrade changelog', 'O a pin-and-wait note'],
    'ann_b': ['Q y p :: Prefer a different SDK version or npm tag?'],
  },
  {
    'n': 286,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: LaunchDarkly flag checklist vs homemade Redis toggle',
    'note_b': 'yes_no: one flag key/default attribute',
    'text_a': 'Notes from the review thread are in [URL]. I mirrored the agreed approach locally.\n\nBilling rewrite needs a kill switch.\n\nWant a LaunchDarkly flag checklist, or a homemade Redis toggle?',
    'text_b': 'Notes from the review thread are in [URL]. I mirrored the agreed approach locally.\n\nBilling rewrite needs a kill switch.\n\nWant a different flag key or default value?',
    'ann_a': ['Q e p :: Want a LaunchDarkly flag checklist, or a homemade Redis toggle?', 'O a LaunchDarkly flag checklist', 'O a homemade Redis toggle'],
    'ann_b': ['Q y p :: Want a different flag key or default value?'],
  },
  {
    'n': 287,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: percentage rollout plan vs cohort allowlist',
    'note_b': 'yes_no: one percentage/cohort attribute',
    'text_a': 'Benchmark before/after on my laptop (n=20):\n- p50: 112ms → 87ms\n- p95: 240ms → 190ms\n\nWe want 5% of orgs on the new nav first.\n\nShall I write a percentage rollout plan, or a cohort allowlist?',
    'text_b': 'Benchmark before/after on my laptop (n=20):\n- p50: 112ms → 87ms\n- p95: 240ms → 190ms\n\nWe want 5% of orgs on the new nav first.\n\nShall I use a different percentage or cohort id?',
    'ann_a': ['Q e p :: Shall I write a percentage rollout plan, or a cohort allowlist?', 'O a percentage rollout plan', 'O a cohort allowlist'],
    'ann_b': ['Q y p :: Shall I use a different percentage or cohort id?'],
  },
  {
    'n': 288,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: OpenFeature provider stub vs direct SDK calls',
    'note_b': 'yes_no: one evaluation context attribute',
    'text_a': 'Status after the last push:\n- unit tests green\n- typecheck clean\n- one integration flake still open\n\nVendors might change next year.\n\nPrefer an OpenFeature provider stub, or direct SDK calls for now?',
    'text_b': 'Status after the last push:\n- unit tests green\n- typecheck clean\n- one integration flake still open\n\nVendors might change next year.\n\nPrefer a different evaluation context key or targeting attribute?',
    'ann_a': ['Q e p :: Prefer an OpenFeature provider stub, or direct SDK calls for now?', 'O an OpenFeature provider stub', 'O direct SDK calls for now'],
    'ann_b': ['Q y p :: Prefer a different evaluation context key or targeting attribute?'],
  },
  {
    'n': 289,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: flag cleanup ticket template vs code-search ripgrep',
    'note_b': 'yes_no: one stale-after attribute',
    'text_a': 'I traced it through the handler and the repository layer. The bug is localized; the surrounding refactor can wait.\n\nStale flags stack up every quarter.\n\nWant a cleanup ticket template, or a ripgrep pass list?',
    'text_b': 'I traced it through the handler and the repository layer. The bug is localized; the surrounding refactor can wait.\n\nStale flags stack up every quarter.\n\nWant a different stale-after window or owner label?',
    'ann_a': ['Q e p :: Want a cleanup ticket template, or a ripgrep pass list?', 'O a cleanup ticket template', 'O a ripgrep pass list'],
    'ann_b': ['Q y p :: Want a different stale-after window or owner label?'],
  },
  {
    'n': 290,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: multivariate flag design vs boolean + config JSON',
    'note_b': 'yes_no: one variant name/weight attribute',
    'text_a': 'Here’s what changed in this pass:\n\n[CODE]\n\nLocally that compiles. Next step is up to you.\n\nCopy experiment needs three headlines.\n\nShould I design a multivariate flag, or boolean + config JSON?',
    'text_b': 'Here’s what changed in this pass:\n\n[CODE]\n\nLocally that compiles. Next step is up to you.\n\nCopy experiment needs three headlines.\n\nShould I use a different variant name or weight?',
    'ann_a': ['Q e p :: Should I design a multivariate flag, or boolean + config JSON?', 'O a multivariate flag', 'O boolean + config JSON'],
    'ann_b': ['Q y p :: Should I use a different variant name or weight?'],
  },
  {
    'n': 291,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: Unleash docker-compose vs Flagsmith saas note',
    'note_b': 'yes_no: one project/environment attribute',
    'text_a': 'Quick dump of the failing log tail:\n\n[CODE]\n\nNothing else looks related.\n\nSelf-host vs SaaS is still open for flags.\n\nWant an Unleash compose file, or a Flagsmith SaaS note?',
    'text_b': 'Quick dump of the failing log tail:\n\n[CODE]\n\nNothing else looks related.\n\nSelf-host vs SaaS is still open for flags.\n\nWant a different project name or environment slug?',
    'ann_a': ['Q e p :: Want an Unleash compose file, or a Flagsmith SaaS note?', 'O an Unleash compose file', 'O a Flagsmith SaaS note'],
    'ann_b': ['Q y p :: Want a different project name or environment slug?'],
  },
  {
    'n': 292,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: kill-switch runbook vs gradual dark-launch steps',
    'note_b': 'yes_no: one runbook severity attribute',
    'text_a': 'Compared against `main` — the delta is small. Docs still mention the old flag name in two places.\n\nIf checkout fails we need a rehearsed abort.\n\nPrefer a kill-switch runbook, or gradual dark-launch steps?',
    'text_b': 'Compared against `main` — the delta is small. Docs still mention the old flag name in two places.\n\nIf checkout fails we need a rehearsed abort.\n\nPrefer a different runbook severity or owner?',
    'ann_a': ['Q e p :: Prefer a kill-switch runbook, or gradual dark-launch steps?', 'O a kill-switch runbook', 'O gradual dark-launch steps'],
    'ann_b': ['Q y p :: Prefer a different runbook severity or owner?'],
  },
  {
    'n': 293,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: terraform module scaffold vs terragrunt wrapper',
    'note_b': 'yes_no: one module source/version attribute',
    'text_a': 'I held off committing. The working tree is dirty only in the files we discussed.\n\nVPC setup is copy-pasted across three envs.\n\nWant a Terraform module scaffold, or a Terragrunt wrapper?',
    'text_b': 'I held off committing. The working tree is dirty only in the files we discussed.\n\nVPC setup is copy-pasted across three envs.\n\nWant a different module source or version pin?',
    'ann_a': ['Q e p :: Want a Terraform module scaffold, or a Terragrunt wrapper?', 'O a Terraform module scaffold', 'O a Terragrunt wrapper'],
    'ann_b': ['Q y p :: Want a different module source or version pin?'],
  },
  {
    'n': 294,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: remote state backend HCL vs migration runbook',
    'note_b': 'yes_no: one bucket/key attribute',
    'text_a': 'Notes from the review thread are in [URL]. I mirrored the agreed approach locally.\n\nLocal state files keep getting lost on laptops.\n\nShall I write a remote state backend block, or a migration runbook?',
    'text_b': 'Notes from the review thread are in [URL]. I mirrored the agreed approach locally.\n\nLocal state files keep getting lost on laptops.\n\nShall I use a different state bucket or key prefix?',
    'ann_a': ['Q e p :: Shall I write a remote state backend block, or a migration runbook?', 'O a remote state backend block', 'O a migration runbook'],
    'ann_b': ['Q y p :: Shall I use a different state bucket or key prefix?'],
  },
  {
    'n': 295,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: aws_security_group resource vs AWS Network Firewall notes',
    'note_b': 'yes_no: one CIDR/port attribute',
    'text_a': 'Benchmark before/after on my laptop (n=20):\n- p50: 112ms → 87ms\n- p95: 240ms → 190ms\n\nSSH from `0.0.0.0/0` is still open in staging.\n\nPrefer an `aws_security_group` resource, or Network Firewall notes?',
    'text_b': 'Benchmark before/after on my laptop (n=20):\n- p50: 112ms → 87ms\n- p95: 240ms → 190ms\n\nSSH from `0.0.0.0/0` is still open in staging.\n\nPrefer a different CIDR or port?',
    'ann_a': ['Q e p :: Prefer an `aws_security_group` resource, or Network Firewall notes?', 'O an `aws_security_group` resource', 'O Network Firewall notes'],
    'ann_b': ['Q y p :: Prefer a different CIDR or port?'],
  },
  {
    'n': 296,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: plan JSON artifact pipeline vs human-readable summary',
    'note_b': 'yes_no: one output format attribute',
    'text_a': 'Status after the last push:\n- unit tests green\n- typecheck clean\n- one integration flake still open\n\nReviewers bounce off raw `terraform plan` walls of text.\n\nWant a plan JSON artifact pipeline, or a human-readable summary?',
    'text_b': 'Status after the last push:\n- unit tests green\n- typecheck clean\n- one integration flake still open\n\nReviewers bounce off raw `terraform plan` walls of text.\n\nWant a different output format or section order?',
    'ann_a': ['Q e p :: Want a plan JSON artifact pipeline, or a human-readable summary?', 'O a plan JSON artifact pipeline', 'O a human-readable summary'],
    'ann_b': ['Q y p :: Want a different output format or section order?'],
  },
  {
    'n': 297,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: tflint config vs checkov policy pack',
    'note_b': 'yes_no: one rule enable attribute',
    'text_a': 'I traced it through the handler and the repository layer. The bug is localized; the surrounding refactor can wait.\n\nIAM `*` actions keep sneaking into PRs.\n\nShould I add a `.tflint.hcl`, or a Checkov policy pack?',
    'text_b': 'I traced it through the handler and the repository layer. The bug is localized; the surrounding refactor can wait.\n\nIAM `*` actions keep sneaking into PRs.\n\nShould I enable a different rule or severity?',
    'ann_a': ['Q e p :: Should I add a `.tflint.hcl`, or a Checkov policy pack?', 'O a `.tflint.hcl`', 'O a Checkov policy pack'],
    'ann_b': ['Q y p :: Should I enable a different rule or severity?'],
  },
  {
    'n': 298,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: workspace-per-env layout vs directory-per-env',
    'note_b': 'yes_no: one workspace name attribute',
    'text_a': 'Here’s what changed in this pass:\n\n[CODE]\n\nLocally that compiles. Next step is up to you.\n\nProd almost got applied with staging vars once.\n\nWant a workspace-per-env layout, or directory-per-env?',
    'text_b': 'Here’s what changed in this pass:\n\n[CODE]\n\nLocally that compiles. Next step is up to you.\n\nProd almost got applied with staging vars once.\n\nWant a different workspace name or var-file?',
    'ann_a': ['Q e p :: Want a workspace-per-env layout, or directory-per-env?', 'O a workspace-per-env layout', 'O directory-per-env'],
    'ann_b': ['Q y p :: Want a different workspace name or var-file?'],
  },
  {
    'n': 299,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: import block examples vs moved blocks for rename',
    'note_b': 'yes_no: one address/id attribute',
    'text_a': 'Quick dump of the failing log tail:\n\n[CODE]\n\nNothing else looks related.\n\nResources were created by click-ops and need adoption.\n\nPrefer `import` block examples, or `moved` blocks for the rename?',
    'text_b': 'Quick dump of the failing log tail:\n\n[CODE]\n\nNothing else looks related.\n\nResources were created by click-ops and need adoption.\n\nPrefer a different resource address or import id?',
    'ann_a': ['Q e p :: Prefer `import` block examples, or `moved` blocks for the rename?', 'O `import` block examples', 'O `moved` blocks for the rename'],
    'ann_b': ['Q y p :: Prefer a different resource address or import id?'],
  },
  {
    'n': 300,
    'boundary': 'yes_no/either_or',
    'note_a': 'either_or: Atlantis server config vs GitHub Actions apply workflow',
    'note_b': 'yes_no: one workflow name/trigger attribute',
    'text_a': 'Compared against `main` — the delta is small. Docs still mention the old flag name in two places.\n\nApplies still happen from engineer laptops.\n\nWant an Atlantis server config, or a GitHub Actions apply workflow?\n\nRef: [URL]',
    'text_b': 'Compared against `main` — the delta is small. Docs still mention the old flag name in two places.\n\nApplies still happen from engineer laptops.\n\nWant a different workflow name or trigger?\n\nRef: [URL]',
    'ann_a': ['Q e p :: Want an Atlantis server config, or a GitHub Actions apply workflow?', 'O an Atlantis server config', 'O a GitHub Actions apply workflow'],
    'ann_b': ['Q y p :: Want a different workflow name or trigger?'],
  },
]
