# _batch_esc_701_800.py

PAIRS = [
  {
    'n': 701,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no',
    'note_b': 'concrete second option -> either_or',
    'text_a': 'Your branch is behind `origin/main` by 3 commits. Do you mean a git fast-forward merge, or something else?',
    'text_b': 'Your branch is behind `origin/main` by 3 commits. Do you mean a git fast-forward merge, or a rebase?',
    'ann_a': ['Q y :: Do you mean a git fast-forward merge, or something else?'],
    'ann_b': ['Q e :: Do you mean a git fast-forward merge, or a rebase?', 'O a git fast-forward merge', 'O a rebase'],
  },
  {
    'n': 702,
    'boundary': 'escape_hatch',
    'note_a': 'explain-or-adjust escape -> yes_no propose',
    'note_b': 'concrete second deliverable -> either_or propose',
    'text_a': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nThe flaky test failures cluster in `test_retry_loop.py`. Would you like me to explain the retry loop or make any adjustments?',
    'text_b': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nThe flaky test failures cluster in `test_retry_loop.py`. Would you like me to explain the retry loop or add monitoring details?',
    'ann_a': ['Q y p :: Would you like me to explain the retry loop or make any adjustments?'],
    'ann_b': ['Q e p :: Would you like me to explain the retry loop or add monitoring details?', 'O explain the retry loop', 'O add monitoring details'],
  },
  {
    'n': 703,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no',
    'note_b': 'concrete second option -> either_or',
    'text_a': 'CI is green on the feature branch. Want a full diff of `auth/` against main, or something else?',
    'text_b': 'CI is green on the feature branch. Want a full diff of `auth/` against main, or a walkthrough of the new middleware?',
    'ann_a': ['Q y p :: Want a full diff of `auth/` against main, or something else?'],
    'ann_b': ['Q e p :: Want a full diff of `auth/` against main, or a walkthrough of the new middleware?', 'O a full diff of `auth/` against main', 'O a walkthrough of the new middleware'],
  },
  {
    'n': 704,
    'boundary': 'escape_hatch',
    'note_a': 'one named + open preference escape -> yes_no',
    'note_b': 'concrete second option -> either_or',
    'text_a': 'I can squash these five WIP commits before opening the PR. Do you prefer a squash merge, or do you have a preference?',
    'text_b': 'I can squash these five WIP commits before opening the PR. Do you prefer a squash merge, or rebase-and-merge?',
    'ann_a': ['Q y :: Do you prefer a squash merge, or do you have a preference?'],
    'ann_b': ['Q e :: Do you prefer a squash merge, or rebase-and-merge?', 'O a squash merge', 'O rebase-and-merge'],
  },
  {
    'n': 705,
    'boundary': 'escape_hatch',
    'note_a': 'one named + adjust-anything escape -> yes_no propose',
    'note_b': 'concrete second option -> either_or propose',
    'text_a': 'Diff against HEAD is ready in the index; nothing pushed.\n\nDraft README update is ready covering install and the new `gq predict` flags. Want me to open the PR as-is, or adjust anything?',
    'text_b': 'Diff against HEAD is ready in the index; nothing pushed.\n\nDraft README update is ready covering install and the new `gq predict` flags. Want me to open the PR as-is, or add a troubleshooting section?',
    'ann_a': ['Q y p :: Want me to open the PR as-is, or adjust anything?'],
    'ann_b': ['Q e p :: Want me to open the PR as-is, or add a troubleshooting section?', 'O open the PR as-is', 'O add a troubleshooting section'],
  },
  {
    'n': 706,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no',
    'note_b': 'concrete second option -> either_or',
    'text_a': "The migration failed on `users.email` uniqueness. Is the blocker a duplicate-row cleanup, or something else you'd like me to dig into?",
    'text_b': 'The migration failed on `users.email` uniqueness. Is the blocker a duplicate-row cleanup, or a schema drift in staging?',
    'ann_a': ["Q y :: Is the blocker a duplicate-row cleanup, or something else you'd like me to dig into?"],
    'ann_b': ['Q e :: Is the blocker a duplicate-row cleanup, or a schema drift in staging?', 'O a duplicate-row cleanup', 'O a schema drift in staging'],
  },
  {
    'n': 707,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no propose',
    'note_b': 'concrete second option -> either_or propose',
    'text_a': 'I patched the off-by-one in `paginate()`. Shall I commit just that fix, or something else?',
    'text_b': 'I patched the off-by-one in `paginate()`. Shall I commit just that fix, or also bump the snapshot fixtures?',
    'ann_a': ['Q y p :: Shall I commit just that fix, or something else?'],
    'ann_b': ['Q e p :: Shall I commit just that fix, or also bump the snapshot fixtures?', 'O commit just that fix', 'O also bump the snapshot fixtures'],
  },
  {
    'n': 708,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no',
    'note_b': 'concrete second option -> either_or',
    'text_a': 'I finished the exploratory pass and stopped before writing files.\n\nLooking at the deploy log, the pod never became Ready. Do you want a deeper look at the readiness probe, or something else?',
    'text_b': 'I finished the exploratory pass and stopped before writing files.\n\nLooking at the deploy log, the pod never became Ready. Do you want a deeper look at the readiness probe, or the image pull secrets?',
    'ann_a': ['Q y :: Do you want a deeper look at the readiness probe, or something else?'],
    'ann_b': ['Q e :: Do you want a deeper look at the readiness probe, or the image pull secrets?', 'O a deeper look at the readiness probe', 'O the image pull secrets'],
  },
  {
    'n': 709,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no propose',
    'note_b': 'concrete second option -> either_or propose',
    'text_a': 'Refactored `CacheClient` to take an explicit TTL. Want me to update the call sites next, or make any adjustments?',
    'text_b': 'Refactored `CacheClient` to take an explicit TTL. Want me to update the call sites next, or write a migration guide?',
    'ann_a': ['Q y p :: Want me to update the call sites next, or make any adjustments?'],
    'ann_b': ['Q e p :: Want me to update the call sites next, or write a migration guide?', 'O update the call sites next', 'O write a migration guide'],
  },
  {
    'n': 710,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no',
    'note_b': 'concrete second option -> either_or',
    'text_a': 'Typecheck fails only under `strictNullChecks`. Is the intent to fix the nullability annotations, or something else?',
    'text_b': 'Typecheck fails only under `strictNullChecks`. Is the intent to fix the nullability annotations, or to turn the flag off in CI?',
    'ann_a': ['Q y :: Is the intent to fix the nullability annotations, or something else?'],
    'ann_b': ['Q e :: Is the intent to fix the nullability annotations, or to turn the flag off in CI?', 'O fix the nullability annotations', 'O to turn the flag off in CI'],
  },
  {
    'n': 711,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no propose',
    'note_b': 'concrete second option -> either_or propose',
    'text_a': "Snippet of the current config:\n\n[CODE]\n\nI have a minimal repro for the race in the worker pool:\n\n[CODE]\n\nWant me to file an issue with that snippet, or something else you'd like?",
    'text_b': 'Snippet of the current config:\n\n[CODE]\n\nI have a minimal repro for the race in the worker pool:\n\n[CODE]\n\nWant me to file an issue with that snippet, or open a draft PR with a lock?',
    'ann_a': ["Q y p :: Want me to file an issue with that snippet, or something else you'd like?"],
    'ann_b': ['Q e p :: Want me to file an issue with that snippet, or open a draft PR with a lock?', 'O file an issue with that snippet', 'O open a draft PR with a lock'],
  },
  {
    'n': 712,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no',
    'note_b': 'concrete second option -> either_or',
    'text_a': 'Docs mention the old `/v1/predict` path. Should we redirect it to `/v2/predict`, or do you have a preference?',
    'text_b': 'Docs mention the old `/v1/predict` path. Should we redirect it to `/v2/predict`, or remove `/v1` entirely?',
    'ann_a': ['Q y :: Should we redirect it to `/v2/predict`, or do you have a preference?'],
    'ann_b': ['Q e :: Should we redirect it to `/v2/predict`, or remove `/v1` entirely?', 'O redirect it to `/v2/predict`', 'O remove `/v1` entirely'],
  },
  {
    'n': 713,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no propose',
    'note_b': 'concrete second option -> either_or propose',
    'text_a': 'Benchmark numbers are in `bench/out.json`. Shall I summarize the p99 regression, or adjust anything?',
    'text_b': 'Benchmark numbers are in `bench/out.json`. Shall I summarize the p99 regression, or plot latency histograms?',
    'ann_a': ['Q y p :: Shall I summarize the p99 regression, or adjust anything?'],
    'ann_b': ['Q e p :: Shall I summarize the p99 regression, or plot latency histograms?', 'O summarize the p99 regression', 'O plot latency histograms'],
  },
  {
    'n': 714,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no',
    'note_b': 'concrete second option -> either_or',
    'text_a': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nThe lint rule `no-floating-promises` lights up in `jobs/`. Is the goal to await every call site, or something else?',
    'text_b': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nThe lint rule `no-floating-promises` lights up in `jobs/`. Is the goal to await every call site, or to void-and-log intentionally?',
    'ann_a': ['Q y :: Is the goal to await every call site, or something else?'],
    'ann_b': ['Q e :: Is the goal to await every call site, or to void-and-log intentionally?', 'O await every call site', 'O to void-and-log intentionally'],
  },
  {
    'n': 715,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no propose',
    'note_b': 'concrete second option -> either_or propose',
    'text_a': 'I can wire the new feature flag behind `ENABLE_STREAMING`. Want me to default it off in prod, or make any adjustments?',
    'text_b': 'I can wire the new feature flag behind `ENABLE_STREAMING`. Want me to default it off in prod, or gate it by tenant allowlist?',
    'ann_a': ['Q y p :: Want me to default it off in prod, or make any adjustments?'],
    'ann_b': ['Q e p :: Want me to default it off in prod, or gate it by tenant allowlist?', 'O default it off in prod', 'O gate it by tenant allowlist'],
  },
  {
    'n': 716,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no',
    'note_b': 'concrete second option -> either_or',
    'text_a': 'Upstream issue is tracked at [URL]. Are you asking about the workaround they merged, or something else?',
    'text_b': 'Upstream issue is tracked at [URL]. Are you asking about the workaround they merged, or the breaking API change in 3.2?',
    'ann_a': ['Q y :: Are you asking about the workaround they merged, or something else?'],
    'ann_b': ['Q e :: Are you asking about the workaround they merged, or the breaking API change in 3.2?', 'O the workaround they merged', 'O the breaking API change in 3.2'],
  },
  {
    'n': 717,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no propose',
    'note_b': 'concrete second option -> either_or propose',
    'text_a': "Diff against HEAD is ready in the index; nothing pushed.\n\nDockerfile now uses a multi-stage build. Want me to push the image to the registry next, or something else you'd like?",
    'text_b': 'Diff against HEAD is ready in the index; nothing pushed.\n\nDockerfile now uses a multi-stage build. Want me to push the image to the registry next, or trim the build context ignores?',
    'ann_a': ["Q y p :: Want me to push the image to the registry next, or something else you'd like?"],
    'ann_b': ['Q e p :: Want me to push the image to the registry next, or trim the build context ignores?', 'O push the image to the registry next', 'O trim the build context ignores'],
  },
  {
    'n': 718,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no',
    'note_b': 'concrete second option -> either_or',
    'text_a': 'The GraphQL schema change drops `User.legacyId`. Is the migration path a deprecation period, or do you have a preference?',
    'text_b': 'The GraphQL schema change drops `User.legacyId`. Is the migration path a deprecation period, or a hard cutover on Friday?',
    'ann_a': ['Q y :: Is the migration path a deprecation period, or do you have a preference?'],
    'ann_b': ['Q e :: Is the migration path a deprecation period, or a hard cutover on Friday?', 'O a deprecation period', 'O a hard cutover on Friday'],
  },
  {
    'n': 719,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no propose',
    'note_b': 'concrete second option -> either_or propose',
    'text_a': 'Coverage dropped 2% after deleting the dead helpers. Shall I restore the thin wrapper tests, or adjust anything?',
    'text_b': 'Coverage dropped 2% after deleting the dead helpers. Shall I restore the thin wrapper tests, or accept the coverage dip?',
    'ann_a': ['Q y p :: Shall I restore the thin wrapper tests, or adjust anything?'],
    'ann_b': ['Q e p :: Shall I restore the thin wrapper tests, or accept the coverage dip?', 'O restore the thin wrapper tests', 'O accept the coverage dip'],
  },
  {
    'n': 720,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no',
    'note_b': 'concrete second option -> either_or',
    'text_a': 'I finished the exploratory pass and stopped before writing files.\n\nSentry shows a spike on `CheckoutError`. Is the priority the null cart edge case, or something else?',
    'text_b': 'I finished the exploratory pass and stopped before writing files.\n\nSentry shows a spike on `CheckoutError`. Is the priority the null cart edge case, or the timeout on payment auth?',
    'ann_a': ['Q y :: Is the priority the null cart edge case, or something else?'],
    'ann_b': ['Q e :: Is the priority the null cart edge case, or the timeout on payment auth?', 'O the null cart edge case', 'O the timeout on payment auth'],
  },
  {
    'n': 721,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no propose',
    'note_b': 'concrete second option -> either_or propose',
    'text_a': 'I drafted a `CHANGELOG` entry for the breaking rename. Want me to also tag `v0.9.0`, or make any adjustments?',
    'text_b': 'I drafted a `CHANGELOG` entry for the breaking rename. Want me to also tag `v0.9.0`, or hold the tag until docs land?',
    'ann_a': ['Q y p :: Want me to also tag `v0.9.0`, or make any adjustments?'],
    'ann_b': ['Q e p :: Want me to also tag `v0.9.0`, or hold the tag until docs land?', 'O also tag `v0.9.0`', 'O hold the tag until docs land'],
  },
  {
    'n': 722,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no',
    'note_b': 'concrete second option -> either_or',
    'text_a': "Redis memory is at 92%. Are you mainly worried about eviction policy, or something else you'd like checked?",
    'text_b': 'Redis memory is at 92%. Are you mainly worried about eviction policy, or key cardinality growth?',
    'ann_a': ["Q y :: Are you mainly worried about eviction policy, or something else you'd like checked?"],
    'ann_b': ['Q e :: Are you mainly worried about eviction policy, or key cardinality growth?', 'O eviction policy', 'O key cardinality growth'],
  },
  {
    'n': 723,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no propose',
    'note_b': 'concrete second option -> either_or propose',
    'text_a': 'Snippet of the current config:\n\n[CODE]\n\nThe flake reproduces under `--runs-per-test=50`. Want me to quarantine it with `@pytest.mark.flaky`, or something else?',
    'text_b': 'Snippet of the current config:\n\n[CODE]\n\nThe flake reproduces under `--runs-per-test=50`. Want me to quarantine it with `@pytest.mark.flaky`, or dig into the shared fixture state?',
    'ann_a': ['Q y p :: Want me to quarantine it with `@pytest.mark.flaky`, or something else?'],
    'ann_b': ['Q e p :: Want me to quarantine it with `@pytest.mark.flaky`, or dig into the shared fixture state?', 'O quarantine it with `@pytest.mark.flaky`', 'O dig into the shared fixture state'],
  },
  {
    'n': 724,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no',
    'note_b': 'concrete second option -> either_or',
    'text_a': 'CSS tokens still use hex for brand colors. Should we move them to OKLCH, or do you have a preference?',
    'text_b': 'CSS tokens still use hex for brand colors. Should we move them to OKLCH, or keep hex and add a dark-mode map?',
    'ann_a': ['Q y :: Should we move them to OKLCH, or do you have a preference?'],
    'ann_b': ['Q e :: Should we move them to OKLCH, or keep hex and add a dark-mode map?', 'O move them to OKLCH', 'O keep hex and add a dark-mode map'],
  },
  {
    'n': 725,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no propose',
    'note_b': 'concrete second option -> either_or propose',
    'text_a': 'I can collapse the three similar copy blocks into one component. Shall I do that refactor now, or adjust anything?',
    'text_b': 'I can collapse the three similar copy blocks into one component. Shall I do that refactor now, or leave them until the design freeze?',
    'ann_a': ['Q y p :: Shall I do that refactor now, or adjust anything?'],
    'ann_b': ['Q e p :: Shall I do that refactor now, or leave them until the design freeze?', 'O do that refactor now', 'O leave them until the design freeze'],
  },
  {
    'n': 726,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no',
    'note_b': 'concrete second option -> either_or',
    'text_a': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nThe API returns 429 under load. Is the ask to raise the rate limit, or something else?',
    'text_b': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nThe API returns 429 under load. Is the ask to raise the rate limit, or add client-side backoff?',
    'ann_a': ['Q y :: Is the ask to raise the rate limit, or something else?'],
    'ann_b': ['Q e :: Is the ask to raise the rate limit, or add client-side backoff?', 'O raise the rate limit', 'O add client-side backoff'],
  },
  {
    'n': 727,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no propose',
    'note_b': 'concrete second option -> either_or propose',
    'text_a': "Secret scan found a sample token in `fixtures/`. Want me to scrub it and force-push the branch, or something else you'd like?",
    'text_b': 'Secret scan found a sample token in `fixtures/`. Want me to scrub it and force-push the branch, or rotate the real credential first?',
    'ann_a': ["Q y p :: Want me to scrub it and force-push the branch, or something else you'd like?"],
    'ann_b': ['Q e p :: Want me to scrub it and force-push the branch, or rotate the real credential first?', 'O scrub it and force-push the branch', 'O rotate the real credential first'],
  },
  {
    'n': 728,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no',
    'note_b': 'concrete second option -> either_or',
    'text_a': 'Postgres plan shows a sequential scan on `events`. Are you aiming for a composite index, or something else?',
    'text_b': 'Postgres plan shows a sequential scan on `events`. Are you aiming for a composite index, or a partitioned table?',
    'ann_a': ['Q y :: Are you aiming for a composite index, or something else?'],
    'ann_b': ['Q e :: Are you aiming for a composite index, or a partitioned table?', 'O a composite index', 'O a partitioned table'],
  },
  {
    'n': 729,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no propose',
    'note_b': 'concrete second option -> either_or propose',
    'text_a': 'Diff against HEAD is ready in the index; nothing pushed.\n\nStorybook stories compile again after the prop rename. Want me to regenerate the chromatic baselines, or make any adjustments?',
    'text_b': 'Diff against HEAD is ready in the index; nothing pushed.\n\nStorybook stories compile again after the prop rename. Want me to regenerate the chromatic baselines, or skip visual review this cycle?',
    'ann_a': ['Q y p :: Want me to regenerate the chromatic baselines, or make any adjustments?'],
    'ann_b': ['Q e p :: Want me to regenerate the chromatic baselines, or skip visual review this cycle?', 'O regenerate the chromatic baselines', 'O skip visual review this cycle'],
  },
  {
    'n': 730,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no',
    'note_b': 'concrete second option -> either_or',
    'text_a': 'The webhook signature check uses HMAC-SHA256. Is the concern clock skew, or do you have a preference for what to inspect?',
    'text_b': 'The webhook signature check uses HMAC-SHA256. Is the concern clock skew, or a mismatched signing secret?',
    'ann_a': ['Q y :: Is the concern clock skew, or do you have a preference for what to inspect?'],
    'ann_b': ['Q e :: Is the concern clock skew, or a mismatched signing secret?', 'O clock skew', 'O a mismatched signing secret'],
  },
  {
    'n': 731,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no propose',
    'note_b': 'concrete second option -> either_or propose',
    'text_a': 'I can replace the hand-rolled mock with `respx`. Shall I convert the remaining HTTP tests, or adjust anything?',
    'text_b': 'I can replace the hand-rolled mock with `respx`. Shall I convert the remaining HTTP tests, or leave the older suite alone?',
    'ann_a': ['Q y p :: Shall I convert the remaining HTTP tests, or adjust anything?'],
    'ann_b': ['Q e p :: Shall I convert the remaining HTTP tests, or leave the older suite alone?', 'O convert the remaining HTTP tests', 'O leave the older suite alone'],
  },
  {
    'n': 732,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no',
    'note_b': 'concrete second option -> either_or',
    'text_a': 'I finished the exploratory pass and stopped before writing files.\n\nTerraform plan wants to recreate the load balancer. Is the plan intentional downtime, or something else?',
    'text_b': 'I finished the exploratory pass and stopped before writing files.\n\nTerraform plan wants to recreate the load balancer. Is the plan intentional downtime, or a create-before-destroy swap?',
    'ann_a': ['Q y :: Is the plan intentional downtime, or something else?'],
    'ann_b': ['Q e :: Is the plan intentional downtime, or a create-before-destroy swap?', 'O intentional downtime', 'O a create-before-destroy swap'],
  },
  {
    'n': 733,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no propose',
    'note_b': 'concrete second option -> either_or propose',
    'text_a': "I extracted shared parsers into `lib/parse`. Want me to re-export the old paths for a release, or something else you'd like?",
    'text_b': 'I extracted shared parsers into `lib/parse`. Want me to re-export the old paths for a release, or break them with a major bump?',
    'ann_a': ["Q y p :: Want me to re-export the old paths for a release, or something else you'd like?"],
    'ann_b': ['Q e p :: Want me to re-export the old paths for a release, or break them with a major bump?', 'O re-export the old paths for a release', 'O break them with a major bump'],
  },
  {
    'n': 734,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no',
    'note_b': 'concrete second option -> either_or',
    'text_a': 'Mobile layout clips the CTA below 360px. Is the fix a smaller type scale, or something else?',
    'text_b': 'Mobile layout clips the CTA below 360px. Is the fix a smaller type scale, or stacking the button full-width?',
    'ann_a': ['Q y :: Is the fix a smaller type scale, or something else?'],
    'ann_b': ['Q e :: Is the fix a smaller type scale, or stacking the button full-width?', 'O a smaller type scale', 'O stacking the button full-width'],
  },
  {
    'n': 735,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no propose',
    'note_b': 'concrete second option -> either_or propose',
    'text_a': 'Snippet of the current config:\n\n[CODE]\n\nLog sample from prod:\n\n[CODE]\n\nWant me to add structured fields around that error, or make any adjustments?',
    'text_b': 'Snippet of the current config:\n\n[CODE]\n\nLog sample from prod:\n\n[CODE]\n\nWant me to add structured fields around that error, or raise a metric counter instead?',
    'ann_a': ['Q y p :: Want me to add structured fields around that error, or make any adjustments?'],
    'ann_b': ['Q e p :: Want me to add structured fields around that error, or raise a metric counter instead?', 'O add structured fields around that error', 'O raise a metric counter instead'],
  },
  {
    'n': 736,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no',
    'note_b': 'concrete second option -> either_or',
    'text_a': 'Dependabot opened a major bump for `react-router`. Are you planning to take it this sprint, or do you have a preference?',
    'text_b': 'Dependabot opened a major bump for `react-router`. Are you planning to take it this sprint, or pin and revisit next quarter?',
    'ann_a': ['Q y :: Are you planning to take it this sprint, or do you have a preference?'],
    'ann_b': ['Q e :: Are you planning to take it this sprint, or pin and revisit next quarter?', 'O take it this sprint', 'O pin and revisit next quarter'],
  },
  {
    'n': 737,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no propose',
    'note_b': 'concrete second option -> either_or propose',
    'text_a': 'I can seed a demo tenant via `scripts/seed_demo.py`. Shall I run that against staging, or adjust anything?',
    'text_b': 'I can seed a demo tenant via `scripts/seed_demo.py`. Shall I run that against staging, or generate a smaller fixture set?',
    'ann_a': ['Q y p :: Shall I run that against staging, or adjust anything?'],
    'ann_b': ['Q e p :: Shall I run that against staging, or generate a smaller fixture set?', 'O run that against staging', 'O generate a smaller fixture set'],
  },
  {
    'n': 738,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no',
    'note_b': 'concrete second option -> either_or',
    'text_a': "Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nThe OpenAPI diff is only in response examples. Is the review about the examples, or something else you'd like explained?",
    'text_b': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nThe OpenAPI diff is only in response examples. Is the review about the examples, or the new required query param?',
    'ann_a': ["Q y :: Is the review about the examples, or something else you'd like explained?"],
    'ann_b': ['Q e :: Is the review about the examples, or the new required query param?', 'O the examples', 'O the new required query param'],
  },
  {
    'n': 739,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no propose',
    'note_b': 'concrete second option -> either_or propose',
    'text_a': 'ESLint flat config is migrated. Want me to delete `.eslintrc.js` now, or something else?',
    'text_b': 'ESLint flat config is migrated. Want me to delete `.eslintrc.js` now, or keep it as a shim for one release?',
    'ann_a': ['Q y p :: Want me to delete `.eslintrc.js` now, or something else?'],
    'ann_b': ['Q e p :: Want me to delete `.eslintrc.js` now, or keep it as a shim for one release?', 'O delete `.eslintrc.js` now', 'O keep it as a shim for one release'],
  },
  {
    'n': 740,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no',
    'note_b': 'concrete second option -> either_or',
    'text_a': 'Kafka consumer lag jumped after the deploy. Is the suspect the new deserializer, or something else?',
    'text_b': 'Kafka consumer lag jumped after the deploy. Is the suspect the new deserializer, or the reduced partition count?',
    'ann_a': ['Q y :: Is the suspect the new deserializer, or something else?'],
    'ann_b': ['Q e :: Is the suspect the new deserializer, or the reduced partition count?', 'O the new deserializer', 'O the reduced partition count'],
  },
  {
    'n': 741,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no propose',
    'note_b': 'concrete second option -> either_or propose',
    'text_a': 'Diff against HEAD is ready in the index; nothing pushed.\n\nI drafted the ADR for switching to SQLite in tests. Want me to circulate it for review, or make any adjustments?',
    'text_b': 'Diff against HEAD is ready in the index; nothing pushed.\n\nI drafted the ADR for switching to SQLite in tests. Want me to circulate it for review, or expand the rollback section?',
    'ann_a': ['Q y p :: Want me to circulate it for review, or make any adjustments?'],
    'ann_b': ['Q e p :: Want me to circulate it for review, or expand the rollback section?', 'O circulate it for review', 'O expand the rollback section'],
  },
  {
    'n': 742,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no',
    'note_b': 'concrete second option -> either_or',
    'text_a': 'The crash dump points at `libuv` thread pool exhaustion. Are you chasing a higher `UV_THREADPOOL_SIZE`, or do you have a preference?',
    'text_b': 'The crash dump points at `libuv` thread pool exhaustion. Are you chasing a higher `UV_THREADPOOL_SIZE`, or offloading the work to a worker process?',
    'ann_a': ['Q y :: Are you chasing a higher `UV_THREADPOOL_SIZE`, or do you have a preference?'],
    'ann_b': ['Q e :: Are you chasing a higher `UV_THREADPOOL_SIZE`, or offloading the work to a worker process?', 'O a higher `UV_THREADPOOL_SIZE`', 'O offloading the work to a worker process'],
  },
  {
    'n': 743,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no propose',
    'note_b': 'concrete second option -> either_or propose',
    'text_a': 'Accessibility audit flags missing labels on the filter chips. Shall I add `aria-label`s across the set, or adjust anything?',
    'text_b': 'Accessibility audit flags missing labels on the filter chips. Shall I add `aria-label`s across the set, or switch to visible text labels?',
    'ann_a': ['Q y p :: Shall I add `aria-label`s across the set, or adjust anything?'],
    'ann_b': ['Q e p :: Shall I add `aria-label`s across the set, or switch to visible text labels?', 'O add `aria-label`s across the set', 'O switch to visible text labels'],
  },
  {
    'n': 744,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no',
    'note_b': 'concrete second option -> either_or',
    'text_a': "I finished the exploratory pass and stopped before writing files.\n\nRelease notes link to [URL]. Is the ask to rewrite the upgrade steps, or something else you'd like?",
    'text_b': 'I finished the exploratory pass and stopped before writing files.\n\nRelease notes link to [URL]. Is the ask to rewrite the upgrade steps, or add a breaking-changes callout?',
    'ann_a': ["Q y :: Is the ask to rewrite the upgrade steps, or something else you'd like?"],
    'ann_b': ['Q e :: Is the ask to rewrite the upgrade steps, or add a breaking-changes callout?', 'O rewrite the upgrade steps', 'O add a breaking-changes callout'],
  },
  {
    'n': 745,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no propose',
    'note_b': 'concrete second option -> either_or propose',
    'text_a': 'I can move the cron from Cloud Scheduler into the app. Want me to land that cutover, or something else?',
    'text_b': 'I can move the cron from Cloud Scheduler into the app. Want me to land that cutover, or keep Scheduler and only document it?',
    'ann_a': ['Q y p :: Want me to land that cutover, or something else?'],
    'ann_b': ['Q e p :: Want me to land that cutover, or keep Scheduler and only document it?', 'O land that cutover', 'O keep Scheduler and only document it'],
  },
  {
    'n': 746,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no',
    'note_b': 'concrete second option -> either_or',
    'text_a': 'The flake is timing-dependent in CI only. Is the preferred fix a longer wait, or something else?',
    'text_b': 'The flake is timing-dependent in CI only. Is the preferred fix a longer wait, or a deterministic fake clock?',
    'ann_a': ['Q y :: Is the preferred fix a longer wait, or something else?'],
    'ann_b': ['Q e :: Is the preferred fix a longer wait, or a deterministic fake clock?', 'O a longer wait', 'O a deterministic fake clock'],
  },
  {
    'n': 747,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no propose',
    'note_b': 'concrete second option -> either_or propose',
    'text_a': 'Snippet of the current config:\n\n[CODE]\n\nHelm values for staging now mirror prod except replicas. Shall I apply the chart, or make any adjustments?',
    'text_b': 'Snippet of the current config:\n\n[CODE]\n\nHelm values for staging now mirror prod except replicas. Shall I apply the chart, or diff against the last known-good release first?',
    'ann_a': ['Q y p :: Shall I apply the chart, or make any adjustments?'],
    'ann_b': ['Q e p :: Shall I apply the chart, or diff against the last known-good release first?', 'O apply the chart', 'O diff against the last known-good release first'],
  },
  {
    'n': 748,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no',
    'note_b': 'concrete second option -> either_or',
    'text_a': 'The CSV export truncates long cells. Are you looking for a quoted-field fix, or do you have a preference?',
    'text_b': 'The CSV export truncates long cells. Are you looking for a quoted-field fix, or switching to parquet?',
    'ann_a': ['Q y :: Are you looking for a quoted-field fix, or do you have a preference?'],
    'ann_b': ['Q e :: Are you looking for a quoted-field fix, or switching to parquet?', 'O a quoted-field fix', 'O switching to parquet'],
  },
  {
    'n': 749,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no propose',
    'note_b': 'concrete second option -> either_or propose',
    'text_a': "I rewrote the onboarding checklist as a single markdown file. Want me to drop it into `docs/`, or something else you'd like?",
    'text_b': 'I rewrote the onboarding checklist as a single markdown file. Want me to drop it into `docs/`, or turn it into a Notion page outline?',
    'ann_a': ["Q y p :: Want me to drop it into `docs/`, or something else you'd like?"],
    'ann_b': ['Q e p :: Want me to drop it into `docs/`, or turn it into a Notion page outline?', 'O drop it into `docs/`', 'O turn it into a Notion page outline'],
  },
  {
    'n': 750,
    'boundary': 'escape_hatch',
    'note_a': 'one named + escape -> yes_no',
    'note_b': 'concrete second option -> either_or',
    'text_a': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nSSL cert renews in 9 days via cert-manager. Is the worry the DNS-01 challenge, or something else?',
    'text_b': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nSSL cert renews in 9 days via cert-manager. Is the worry the DNS-01 challenge, or the ClusterIssuer secret rotation?',
    'ann_a': ['Q y :: Is the worry the DNS-01 challenge, or something else?'],
    'ann_b': ['Q e :: Is the worry the DNS-01 challenge, or the ClusterIssuer secret rotation?', 'O the DNS-01 challenge', 'O the ClusterIssuer secret rotation'],
  },
  {
    'n': 751,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or (escape ignored)',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': 'Which git operation do you want—fast-forward merge, pull with `--ff-only`, or something else?',
    'text_b': 'Which git operation do you want—fast-forward merge, pull with `--ff-only`, or a rebase?',
    'ann_a': ['Q e :: Which git operation do you want—fast-forward merge, pull with `--ff-only`, or something else?', 'O fast-forward merge', 'O pull with `--ff-only`'],
    'ann_b': ['Q m :: Which git operation do you want—fast-forward merge, pull with `--ff-only`, or a rebase?', 'O fast-forward merge', 'O pull with `--ff-only`', 'O a rebase'],
  },
  {
    'n': 752,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or (escape ignored)',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': "What's your sense of the root cause — follow-through, safety, or something else?",
    'text_b': "What's your sense of the root cause — follow-through, safety, or capacity planning?",
    'ann_a': ["Q e :: What's your sense of the root cause — follow-through, safety, or something else?", 'O follow-through', 'O safety'],
    'ann_b': ["Q m :: What's your sense of the root cause — follow-through, safety, or capacity planning?", 'O follow-through', 'O safety', 'O capacity planning'],
  },
  {
    'n': 753,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or propose',
    'note_b': 'third concrete option -> multi_choice propose',
    'text_a': 'Diff against HEAD is ready in the index; nothing pushed.\n\nWould you like me to draft a unit test, add an integration test, or make any adjustments?',
    'text_b': 'Diff against HEAD is ready in the index; nothing pushed.\n\nWould you like me to draft a unit test, add an integration test, or update the golden fixtures?',
    'ann_a': ['Q e p :: Would you like me to draft a unit test, add an integration test, or make any adjustments?', 'O draft a unit test', 'O add an integration test'],
    'ann_b': ['Q m p :: Would you like me to draft a unit test, add an integration test, or update the golden fixtures?', 'O draft a unit test', 'O add an integration test', 'O update the golden fixtures'],
  },
  {
    'n': 754,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': "What's your specific interest here - policy evaluation, research design, or something else?",
    'text_b': "What's your specific interest here - policy evaluation, research design, or instrumentation?",
    'ann_a': ["Q e :: What's your specific interest here - policy evaluation, research design, or something else?", 'O policy evaluation', 'O research design'],
    'ann_b': ["Q m :: What's your specific interest here - policy evaluation, research design, or instrumentation?", 'O policy evaluation', 'O research design', 'O instrumentation'],
  },
  {
    'n': 755,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': "Deploy failed mid-rollout. What's the next step — roll back the canary, freeze traffic, or something else?",
    'text_b': "Deploy failed mid-rollout. What's the next step — roll back the canary, freeze traffic, or promote the previous revision?",
    'ann_a': ["Q e :: What's the next step — roll back the canary, freeze traffic, or something else?", 'O roll back the canary', 'O freeze traffic'],
    'ann_b': ["Q m :: What's the next step — roll back the canary, freeze traffic, or promote the previous revision?", 'O roll back the canary', 'O freeze traffic', 'O promote the previous revision'],
  },
  {
    'n': 756,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or propose',
    'note_b': 'third concrete option -> multi_choice propose',
    'text_a': 'I finished the exploratory pass and stopped before writing files.\n\nWant me to fix the flaky assertion, skip the test in CI, or adjust anything?',
    'text_b': 'I finished the exploratory pass and stopped before writing files.\n\nWant me to fix the flaky assertion, skip the test in CI, or rewrite it as a property test?',
    'ann_a': ['Q e p :: Want me to fix the flaky assertion, skip the test in CI, or adjust anything?', 'O fix the flaky assertion', 'O skip the test in CI'],
    'ann_b': ['Q m p :: Want me to fix the flaky assertion, skip the test in CI, or rewrite it as a property test?', 'O fix the flaky assertion', 'O skip the test in CI', 'O rewrite it as a property test'],
  },
  {
    'n': 757,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': 'Which storage backend should we target first—S3, GCS, or do you have a preference?',
    'text_b': 'Which storage backend should we target first—S3, GCS, or Azure Blob?',
    'ann_a': ['Q e :: Which storage backend should we target first—S3, GCS, or do you have a preference?', 'O S3', 'O GCS'],
    'ann_b': ['Q m :: Which storage backend should we target first—S3, GCS, or Azure Blob?', 'O S3', 'O GCS', 'O Azure Blob'],
  },
  {
    'n': 758,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': "Auth regression: is it session cookies, JWT expiry, or something else you'd like investigated?",
    'text_b': 'Auth regression: is it session cookies, JWT expiry, or CSRF token mismatch?',
    'ann_a': ["Q e :: is it session cookies, JWT expiry, or something else you'd like investigated?", 'O session cookies', 'O JWT expiry'],
    'ann_b': ['Q m :: is it session cookies, JWT expiry, or CSRF token mismatch?', 'O session cookies', 'O JWT expiry', 'O CSRF token mismatch'],
  },
  {
    'n': 759,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or propose',
    'note_b': 'third concrete option -> multi_choice propose',
    'text_a': 'Snippet of the current config:\n\n[CODE]\n\nShall I bump the Node image, pin transitive deps, or make any adjustments?',
    'text_b': 'Snippet of the current config:\n\n[CODE]\n\nShall I bump the Node image, pin transitive deps, or regenerate the lockfile only?',
    'ann_a': ['Q e p :: Shall I bump the Node image, pin transitive deps, or make any adjustments?', 'O bump the Node image', 'O pin transitive deps'],
    'ann_b': ['Q m p :: Shall I bump the Node image, pin transitive deps, or regenerate the lockfile only?', 'O bump the Node image', 'O pin transitive deps', 'O regenerate the lockfile only'],
  },
  {
    'n': 760,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': 'What kind of app is it — web service, batch jobs, or something else?',
    'text_b': 'What kind of app is it — web service, batch jobs, or a CLI tool?',
    'ann_a': ['Q e :: What kind of app is it — web service, batch jobs, or something else?', 'O web service', 'O batch jobs'],
    'ann_b': ['Q m :: What kind of app is it — web service, batch jobs, or a CLI tool?', 'O web service', 'O batch jobs', 'O a CLI tool'],
  },
  {
    'n': 761,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': 'DB pool errors spike at night. Prefer connection limits, statement timeouts, or something else?',
    'text_b': 'DB pool errors spike at night. Prefer connection limits, statement timeouts, or read replicas?',
    'ann_a': ['Q e :: Prefer connection limits, statement timeouts, or something else?', 'O connection limits', 'O statement timeouts'],
    'ann_b': ['Q m :: Prefer connection limits, statement timeouts, or read replicas?', 'O connection limits', 'O statement timeouts', 'O read replicas'],
  },
  {
    'n': 762,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or propose',
    'note_b': 'third concrete option -> multi_choice propose',
    'text_a': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nWant me to open a tracking issue, draft a mitigation PR, or adjust anything?',
    'text_b': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nWant me to open a tracking issue, draft a mitigation PR, or page on-call with a summary?',
    'ann_a': ['Q e p :: Want me to open a tracking issue, draft a mitigation PR, or adjust anything?', 'O open a tracking issue', 'O draft a mitigation PR'],
    'ann_b': ['Q m p :: Want me to open a tracking issue, draft a mitigation PR, or page on-call with a summary?', 'O open a tracking issue', 'O draft a mitigation PR', 'O page on-call with a summary'],
  },
  {
    'n': 763,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': 'Which CI cache strategy—actions/cache, sccache, or something else?',
    'text_b': 'Which CI cache strategy—actions/cache, sccache, or Bazel remote cache?',
    'ann_a': ['Q e :: Which CI cache strategy—actions/cache, sccache, or something else?', 'O actions/cache', 'O sccache'],
    'ann_b': ['Q m :: Which CI cache strategy—actions/cache, sccache, or Bazel remote cache?', 'O actions/cache', 'O sccache', 'O Bazel remote cache'],
  },
  {
    'n': 764,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': 'Frontend bundle is overweight. Cut icons, lazy-load routes, or do you have a preference?',
    'text_b': 'Frontend bundle is overweight. Cut icons, lazy-load routes, or split the vendor chunk?',
    'ann_a': ['Q e :: Cut icons, lazy-load routes, or do you have a preference?', 'O Cut icons', 'O lazy-load routes'],
    'ann_b': ['Q m :: Cut icons, lazy-load routes, or split the vendor chunk?', 'O Cut icons', 'O lazy-load routes', 'O split the vendor chunk'],
  },
  {
    'n': 765,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or propose',
    'note_b': 'third concrete option -> multi_choice propose',
    'text_a': 'Diff against HEAD is ready in the index; nothing pushed.\n\nWould you like me to explain the backoff schedule, document the retry metrics, or make any adjustments?',
    'text_b': 'Diff against HEAD is ready in the index; nothing pushed.\n\nWould you like me to explain the backoff schedule, document the retry metrics, or add a circuit breaker?',
    'ann_a': ['Q e p :: Would you like me to explain the backoff schedule, document the retry metrics, or make any adjustments?', 'O explain the backoff schedule', 'O document the retry metrics'],
    'ann_b': ['Q m p :: Would you like me to explain the backoff schedule, document the retry metrics, or add a circuit breaker?', 'O explain the backoff schedule', 'O document the retry metrics', 'O add a circuit breaker'],
  },
  {
    'n': 766,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': "Schema migration strategy—expand/contract, big bang, or something else you'd like?",
    'text_b': 'Schema migration strategy—expand/contract, big bang, or dual-write for a week?',
    'ann_a': ["Q e :: Schema migration strategy—expand/contract, big bang, or something else you'd like?", 'O expand/contract', 'O big bang'],
    'ann_b': ['Q m :: Schema migration strategy—expand/contract, big bang, or dual-write for a week?', 'O expand/contract', 'O big bang', 'O dual-write for a week'],
  },
  {
    'n': 767,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': 'Logging format for the service: JSON lines, logfmt, or something else?',
    'text_b': 'Logging format for the service: JSON lines, logfmt, or plain text with levels?',
    'ann_a': ['Q e :: Logging format for the service: JSON lines, logfmt, or something else?', 'O JSON lines', 'O logfmt'],
    'ann_b': ['Q m :: Logging format for the service: JSON lines, logfmt, or plain text with levels?', 'O JSON lines', 'O logfmt', 'O plain text with levels'],
  },
  {
    'n': 768,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or propose',
    'note_b': 'third concrete option -> multi_choice propose',
    'text_a': 'I finished the exploratory pass and stopped before writing files.\n\nWant me to redraft the PR description, rebase onto main, or adjust anything?',
    'text_b': 'I finished the exploratory pass and stopped before writing files.\n\nWant me to redraft the PR description, rebase onto main, or squash into one commit?',
    'ann_a': ['Q e p :: Want me to redraft the PR description, rebase onto main, or adjust anything?', 'O redraft the PR description', 'O rebase onto main'],
    'ann_b': ['Q m p :: Want me to redraft the PR description, rebase onto main, or squash into one commit?', 'O redraft the PR description', 'O rebase onto main', 'O squash into one commit'],
  },
  {
    'n': 769,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': 'Which queue broker—RabbitMQ, SQS, or do you have a preference?',
    'text_b': 'Which queue broker—RabbitMQ, SQS, or Redis Streams?',
    'ann_a': ['Q e :: Which queue broker—RabbitMQ, SQS, or do you have a preference?', 'O RabbitMQ', 'O SQS'],
    'ann_b': ['Q m :: Which queue broker—RabbitMQ, SQS, or Redis Streams?', 'O RabbitMQ', 'O SQS', 'O Redis Streams'],
  },
  {
    'n': 770,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': 'Perf win options: memoize the selector, virtualize the list, or something else?',
    'text_b': 'Perf win options: memoize the selector, virtualize the list, or paginate server-side?',
    'ann_a': ['Q e :: Perf win options: memoize the selector, virtualize the list, or something else?', 'O memoize the selector', 'O virtualize the list'],
    'ann_b': ['Q m :: Perf win options: memoize the selector, virtualize the list, or paginate server-side?', 'O memoize the selector', 'O virtualize the list', 'O paginate server-side'],
  },
  {
    'n': 771,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or propose',
    'note_b': 'third concrete option -> multi_choice propose',
    'text_a': 'Snippet of the current config:\n\n[CODE]\n\nShall I migrate the remaining modules to ESM, dual-publish CJS, or make any adjustments?',
    'text_b': 'Snippet of the current config:\n\n[CODE]\n\nShall I migrate the remaining modules to ESM, dual-publish CJS, or keep CJS until major 2.0?',
    'ann_a': ['Q e p :: Shall I migrate the remaining modules to ESM, dual-publish CJS, or make any adjustments?', 'O migrate the remaining modules to ESM', 'O dual-publish CJS'],
    'ann_b': ['Q m p :: Shall I migrate the remaining modules to ESM, dual-publish CJS, or keep CJS until major 2.0?', 'O migrate the remaining modules to ESM', 'O dual-publish CJS', 'O keep CJS until major 2.0'],
  },
  {
    'n': 772,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': "Incident status page: post a partial outage, mark monitoring, or something else you'd like?",
    'text_b': 'Incident status page: post a partial outage, mark monitoring, or resolve as false alarm?',
    'ann_a': ["Q e :: Incident status page: post a partial outage, mark monitoring, or something else you'd like?", 'O post a partial outage', 'O mark monitoring'],
    'ann_b': ['Q m :: Incident status page: post a partial outage, mark monitoring, or resolve as false alarm?', 'O post a partial outage', 'O mark monitoring', 'O resolve as false alarm'],
  },
  {
    'n': 773,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': 'Which test runner going forward—pytest, unittest, or something else?',
    'text_b': 'Which test runner going forward—pytest, unittest, or nose2?',
    'ann_a': ['Q e :: Which test runner going forward—pytest, unittest, or something else?', 'O pytest', 'O unittest'],
    'ann_b': ['Q m :: Which test runner going forward—pytest, unittest, or nose2?', 'O pytest', 'O unittest', 'O nose2'],
  },
  {
    'n': 774,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or propose',
    'note_b': 'third concrete option -> multi_choice propose',
    'text_a': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nWant me to tighten the CSP, add Trusted Types, or adjust anything?',
    'text_b': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nWant me to tighten the CSP, add Trusted Types, or defer both until the audit?',
    'ann_a': ['Q e p :: Want me to tighten the CSP, add Trusted Types, or adjust anything?', 'O tighten the CSP', 'O add Trusted Types'],
    'ann_b': ['Q m p :: Want me to tighten the CSP, add Trusted Types, or defer both until the audit?', 'O tighten the CSP', 'O add Trusted Types', 'O defer both until the audit'],
  },
  {
    'n': 775,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': 'Data export path: nightly dump, on-demand API, or do you have a preference?',
    'text_b': 'Data export path: nightly dump, on-demand API, or CDC into the warehouse?',
    'ann_a': ['Q e :: Data export path: nightly dump, on-demand API, or do you have a preference?', 'O nightly dump', 'O on-demand API'],
    'ann_b': ['Q m :: Data export path: nightly dump, on-demand API, or CDC into the warehouse?', 'O nightly dump', 'O on-demand API', 'O CDC into the warehouse'],
  },
  {
    'n': 776,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': 'Feature flag rollout: 5% canary, full internal, or something else?',
    'text_b': 'Feature flag rollout: 5% canary, full internal, or region-by-region?',
    'ann_a': ['Q e :: Feature flag rollout: 5% canary, full internal, or something else?', 'O 5% canary', 'O full internal'],
    'ann_b': ['Q m :: Feature flag rollout: 5% canary, full internal, or region-by-region?', 'O 5% canary', 'O full internal', 'O region-by-region'],
  },
  {
    'n': 777,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or propose',
    'note_b': 'third concrete option -> multi_choice propose',
    'text_a': 'Diff against HEAD is ready in the index; nothing pushed.\n\nWould you like me to add OpenTelemetry spans, wire Prometheus metrics, or make any adjustments?',
    'text_b': 'Diff against HEAD is ready in the index; nothing pushed.\n\nWould you like me to add OpenTelemetry spans, wire Prometheus metrics, or ship a Grafana dashboard?',
    'ann_a': ['Q e p :: Would you like me to add OpenTelemetry spans, wire Prometheus metrics, or make any adjustments?', 'O add OpenTelemetry spans', 'O wire Prometheus metrics'],
    'ann_b': ['Q m p :: Would you like me to add OpenTelemetry spans, wire Prometheus metrics, or ship a Grafana dashboard?', 'O add OpenTelemetry spans', 'O wire Prometheus metrics', 'O ship a Grafana dashboard'],
  },
  {
    'n': 778,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': "Docs home: keep the wiki, move to MkDocs, or something else you'd like?",
    'text_b': 'Docs home: keep the wiki, move to MkDocs, or publish to the portal at [URL]?',
    'ann_a': ["Q e :: Docs home: keep the wiki, move to MkDocs, or something else you'd like?", 'O keep the wiki', 'O move to MkDocs'],
    'ann_b': ['Q m :: Docs home: keep the wiki, move to MkDocs, or publish to the portal at [URL]?', 'O keep the wiki', 'O move to MkDocs', 'O publish to the portal at [URL]'],
  },
  {
    'n': 779,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': 'Error budget burn: tighten SLOs, add alerts, or something else?',
    'text_b': 'Error budget burn: tighten SLOs, add alerts, or pause feature launches?',
    'ann_a': ['Q e :: Error budget burn: tighten SLOs, add alerts, or something else?', 'O tighten SLOs', 'O add alerts'],
    'ann_b': ['Q m :: Error budget burn: tighten SLOs, add alerts, or pause feature launches?', 'O tighten SLOs', 'O add alerts', 'O pause feature launches'],
  },
  {
    'n': 780,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or propose',
    'note_b': 'third concrete option -> multi_choice propose',
    'text_a': 'I finished the exploratory pass and stopped before writing files.\n\nWant me to delete the dead CSS, convert to CSS modules, or adjust anything?',
    'text_b': 'I finished the exploratory pass and stopped before writing files.\n\nWant me to delete the dead CSS, convert to CSS modules, or introduce a design-token layer?',
    'ann_a': ['Q e p :: Want me to delete the dead CSS, convert to CSS modules, or adjust anything?', 'O delete the dead CSS', 'O convert to CSS modules'],
    'ann_b': ['Q m p :: Want me to delete the dead CSS, convert to CSS modules, or introduce a design-token layer?', 'O delete the dead CSS', 'O convert to CSS modules', 'O introduce a design-token layer'],
  },
  {
    'n': 781,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': 'Backup cadence for the primary DB—hourly, daily, or do you have a preference?',
    'text_b': 'Backup cadence for the primary DB—hourly, daily, or continuous WAL shipping?',
    'ann_a': ['Q e :: Backup cadence for the primary DB—hourly, daily, or do you have a preference?', 'O hourly', 'O daily'],
    'ann_b': ['Q m :: Backup cadence for the primary DB—hourly, daily, or continuous WAL shipping?', 'O hourly', 'O daily', 'O continuous WAL shipping'],
  },
  {
    'n': 782,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': 'API versioning style: URL path, header, or something else?',
    'text_b': 'API versioning style: URL path, header, or query parameter?',
    'ann_a': ['Q e :: API versioning style: URL path, header, or something else?', 'O URL path', 'O header'],
    'ann_b': ['Q m :: API versioning style: URL path, header, or query parameter?', 'O URL path', 'O header', 'O query parameter'],
  },
  {
    'n': 783,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or propose',
    'note_b': 'third concrete option -> multi_choice propose',
    'text_a': 'Snippet of the current config:\n\n[CODE]\n\nShall I stub the third-party SDK, record a VCR cassette, or make any adjustments?',
    'text_b': 'Snippet of the current config:\n\n[CODE]\n\nShall I stub the third-party SDK, record a VCR cassette, or hit a sandbox endpoint live?',
    'ann_a': ['Q e p :: Shall I stub the third-party SDK, record a VCR cassette, or make any adjustments?', 'O stub the third-party SDK', 'O record a VCR cassette'],
    'ann_b': ['Q m p :: Shall I stub the third-party SDK, record a VCR cassette, or hit a sandbox endpoint live?', 'O stub the third-party SDK', 'O record a VCR cassette', 'O hit a sandbox endpoint live'],
  },
  {
    'n': 784,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': "Search backend: Elasticsearch, Typesense, or something else you'd like?",
    'text_b': 'Search backend: Elasticsearch, Typesense, or Postgres `tsvector`?',
    'ann_a': ["Q e :: Search backend: Elasticsearch, Typesense, or something else you'd like?", 'O Elasticsearch', 'O Typesense'],
    'ann_b': ['Q m :: Search backend: Elasticsearch, Typesense, or Postgres `tsvector`?', 'O Elasticsearch', 'O Typesense', 'O Postgres `tsvector`'],
  },
  {
    'n': 785,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': 'Release channel for the desktop app—stable, beta, or something else?',
    'text_b': 'Release channel for the desktop app—stable, beta, or nightly?',
    'ann_a': ['Q e :: Release channel for the desktop app—stable, beta, or something else?', 'O stable', 'O beta'],
    'ann_b': ['Q m :: Release channel for the desktop app—stable, beta, or nightly?', 'O stable', 'O beta', 'O nightly'],
  },
  {
    'n': 786,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or propose',
    'note_b': 'third concrete option -> multi_choice propose',
    'text_a': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nWant me to flatten the nested folders, rename packages, or adjust anything?',
    'text_b': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nWant me to flatten the nested folders, rename packages, or leave layout and only update imports?',
    'ann_a': ['Q e p :: Want me to flatten the nested folders, rename packages, or adjust anything?', 'O flatten the nested folders', 'O rename packages'],
    'ann_b': ['Q m p :: Want me to flatten the nested folders, rename packages, or leave layout and only update imports?', 'O flatten the nested folders', 'O rename packages', 'O leave layout and only update imports'],
  },
  {
    'n': 787,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': 'Secret storage: env files, Vault, or do you have a preference?',
    'text_b': 'Secret storage: env files, Vault, or cloud KMS?',
    'ann_a': ['Q e :: Secret storage: env files, Vault, or do you have a preference?', 'O env files', 'O Vault'],
    'ann_b': ['Q m :: Secret storage: env files, Vault, or cloud KMS?', 'O env files', 'O Vault', 'O cloud KMS'],
  },
  {
    'n': 788,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': 'Monorepo tooling—pnpm workspaces, Nx, or something else?',
    'text_b': 'Monorepo tooling—pnpm workspaces, Nx, or Turborepo?',
    'ann_a': ['Q e :: Monorepo tooling—pnpm workspaces, Nx, or something else?', 'O pnpm workspaces', 'O Nx'],
    'ann_b': ['Q m :: Monorepo tooling—pnpm workspaces, Nx, or Turborepo?', 'O pnpm workspaces', 'O Nx', 'O Turborepo'],
  },
  {
    'n': 789,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or propose',
    'note_b': 'third concrete option -> multi_choice propose',
    'text_a': 'Diff against HEAD is ready in the index; nothing pushed.\n\nWould you like me to regenerate the OpenAPI client, update the Postman collection, or make any adjustments?',
    'text_b': 'Diff against HEAD is ready in the index; nothing pushed.\n\nWould you like me to regenerate the OpenAPI client, update the Postman collection, or publish a changelog snippet?',
    'ann_a': ['Q e p :: Would you like me to regenerate the OpenAPI client, update the Postman collection, or make any adjustments?', 'O regenerate the OpenAPI client', 'O update the Postman collection'],
    'ann_b': ['Q m p :: Would you like me to regenerate the OpenAPI client, update the Postman collection, or publish a changelog snippet?', 'O regenerate the OpenAPI client', 'O update the Postman collection', 'O publish a changelog snippet'],
  },
  {
    'n': 790,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': "Idle timeout for sessions: 15 minutes, 1 hour, or something else you'd like?",
    'text_b': 'Idle timeout for sessions: 15 minutes, 1 hour, or no idle logout?',
    'ann_a': ["Q e :: Idle timeout for sessions: 15 minutes, 1 hour, or something else you'd like?", 'O 15 minutes', 'O 1 hour'],
    'ann_b': ['Q m :: Idle timeout for sessions: 15 minutes, 1 hour, or no idle logout?', 'O 15 minutes', 'O 1 hour', 'O no idle logout'],
  },
  {
    'n': 791,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': 'Image build: multi-stage Docker, BuildKit cache mounts, or something else?',
    'text_b': 'Image build: multi-stage Docker, BuildKit cache mounts, or a remote build farm?',
    'ann_a': ['Q e :: Image build: multi-stage Docker, BuildKit cache mounts, or something else?', 'O multi-stage Docker', 'O BuildKit cache mounts'],
    'ann_b': ['Q m :: Image build: multi-stage Docker, BuildKit cache mounts, or a remote build farm?', 'O multi-stage Docker', 'O BuildKit cache mounts', 'O a remote build farm'],
  },
  {
    'n': 792,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or propose',
    'note_b': 'third concrete option -> multi_choice propose',
    'text_a': 'I finished the exploratory pass and stopped before writing files.\n\nWant me to add a smoke test job, gate merges on coverage, or adjust anything?',
    'text_b': 'I finished the exploratory pass and stopped before writing files.\n\nWant me to add a smoke test job, gate merges on coverage, or require two reviewers?',
    'ann_a': ['Q e p :: Want me to add a smoke test job, gate merges on coverage, or adjust anything?', 'O add a smoke test job', 'O gate merges on coverage'],
    'ann_b': ['Q m p :: Want me to add a smoke test job, gate merges on coverage, or require two reviewers?', 'O add a smoke test job', 'O gate merges on coverage', 'O require two reviewers'],
  },
  {
    'n': 793,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': 'Localization approach: in-house strings, Crowdin, or do you have a preference?',
    'text_b': 'Localization approach: in-house strings, Crowdin, or Phrase?',
    'ann_a': ['Q e :: Localization approach: in-house strings, Crowdin, or do you have a preference?', 'O in-house strings', 'O Crowdin'],
    'ann_b': ['Q m :: Localization approach: in-house strings, Crowdin, or Phrase?', 'O in-house strings', 'O Crowdin', 'O Phrase'],
  },
  {
    'n': 794,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': 'Cache invalidation: TTL only, event-driven purge, or something else?',
    'text_b': 'Cache invalidation: TTL only, event-driven purge, or versioned keys?',
    'ann_a': ['Q e :: Cache invalidation: TTL only, event-driven purge, or something else?', 'O TTL only', 'O event-driven purge'],
    'ann_b': ['Q m :: Cache invalidation: TTL only, event-driven purge, or versioned keys?', 'O TTL only', 'O event-driven purge', 'O versioned keys'],
  },
  {
    'n': 795,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or propose',
    'note_b': 'third concrete option -> multi_choice propose',
    'text_a': 'Snippet of the current config:\n\n[CODE]\n\nShall I draft the runbook, record a loom walkthrough, or make any adjustments?',
    'text_b': 'Snippet of the current config:\n\n[CODE]\n\nShall I draft the runbook, record a loom walkthrough, or schedule a live drill?',
    'ann_a': ['Q e p :: Shall I draft the runbook, record a loom walkthrough, or make any adjustments?', 'O draft the runbook', 'O record a loom walkthrough'],
    'ann_b': ['Q m p :: Shall I draft the runbook, record a loom walkthrough, or schedule a live drill?', 'O draft the runbook', 'O record a loom walkthrough', 'O schedule a live drill'],
  },
  {
    'n': 796,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': "Tracing sample rate: 1%, 10%, or something else you'd like?",
    'text_b': 'Tracing sample rate: 1%, 10%, or always-on for errors only?',
    'ann_a': ["Q e :: Tracing sample rate: 1%, 10%, or something else you'd like?", 'O 1%', 'O 10%'],
    'ann_b': ['Q m :: Tracing sample rate: 1%, 10%, or always-on for errors only?', 'O 1%', 'O 10%', 'O always-on for errors only'],
  },
  {
    'n': 797,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': 'Which lint baseline—Airbnb, Standard, or something else?',
    'text_b': 'Which lint baseline—Airbnb, Standard, or a custom shareable config?',
    'ann_a': ['Q e :: Which lint baseline—Airbnb, Standard, or something else?', 'O Airbnb', 'O Standard'],
    'ann_b': ['Q m :: Which lint baseline—Airbnb, Standard, or a custom shareable config?', 'O Airbnb', 'O Standard', 'O a custom shareable config'],
  },
  {
    'n': 798,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or propose',
    'note_b': 'third concrete option -> multi_choice propose',
    'text_a': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nWant me to archive the legacy repo, transfer ownership, or adjust anything?',
    'text_b': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nWant me to archive the legacy repo, transfer ownership, or mirror it read-only?',
    'ann_a': ['Q e p :: Want me to archive the legacy repo, transfer ownership, or adjust anything?', 'O archive the legacy repo', 'O transfer ownership'],
    'ann_b': ['Q m p :: Want me to archive the legacy repo, transfer ownership, or mirror it read-only?', 'O archive the legacy repo', 'O transfer ownership', 'O mirror it read-only'],
  },
  {
    'n': 799,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': 'GPU pool sizing for training: spot instances, reserved capacity, or do you have a preference?',
    'text_b': 'GPU pool sizing for training: spot instances, reserved capacity, or a hybrid with fallback?',
    'ann_a': ['Q e :: GPU pool sizing for training: spot instances, reserved capacity, or do you have a preference?', 'O spot instances', 'O reserved capacity'],
    'ann_b': ['Q m :: GPU pool sizing for training: spot instances, reserved capacity, or a hybrid with fallback?', 'O spot instances', 'O reserved capacity', 'O a hybrid with fallback'],
  },
  {
    'n': 800,
    'boundary': 'escape_hatch',
    'note_a': 'two named + escape -> either_or',
    'note_b': 'third concrete option -> multi_choice',
    'text_a': 'Final cut for the demo video—screen capture, animated diagrams, or something else?\n\nRough cut notes are in [CODE] if that helps.',
    'text_b': 'Final cut for the demo video—screen capture, animated diagrams, or a live walkthrough?\n\nRough cut notes are in [CODE] if that helps.',
    'ann_a': ['Q e :: Final cut for the demo video—screen capture, animated diagrams, or something else?', 'O screen capture', 'O animated diagrams'],
    'ann_b': ['Q m :: Final cut for the demo video—screen capture, animated diagrams, or a live walkthrough?', 'O screen capture', 'O animated diagrams', 'O a live walkthrough'],
  },
]
