# Hand-authored examples vs options pairs pa0601–pa0700.
# a = open with e.g./such as illustrations; b = real choice among same items.

PAIRS = [
  {
    'n': 601,
    'boundary': 'examples/options',
    'note_a': 'e.g. list illustrates -> open',
    'note_b': 'same items as real choice -> multi_choice',
    'text_a': 'Could you clarify what "this" is—e.g., a specific file, directory, error message, or something else you\'d like explained?',
    'text_b': 'Which should I look at first — a specific file, a directory, or an error message?',
    'ann_a': ['Q o :: Could you clarify what "this" is—e.g., a specific file, directory, error message, or something else you\'d like explained?'],
    'ann_b': ['Q m :: Which should I look at first — a specific file, a directory, or an error message?', 'O a specific file', 'O a directory', 'O an error message'],
  },
  {
    'n': 602,
    'boundary': 'examples/options',
    'note_a': 'e.g. CI artifact kinds -> open',
    'note_b': 'same artifacts as choice -> multi_choice',
    'text_a': 'The job failed after the build step. Could you share what failed—e.g., the lint log, the test summary, or the uploaded artifact name?',
    'text_b': 'The job failed after the build step. Which should I pull first — the lint log, the test summary, or the uploaded artifact name?',
    'ann_a': ['Q o :: Could you share what failed—e.g., the lint log, the test summary, or the uploaded artifact name?'],
    'ann_b': ['Q m :: Which should I pull first — the lint log, the test summary, or the uploaded artifact name?', 'O the lint log', 'O the test summary', 'O the uploaded artifact name'],
  },
  {
    'n': 603,
    'boundary': 'examples/options',
    'note_a': 'e.g. list illustrates -> open',
    'note_b': 'same targets as preference -> multi_choice',
    'text_a': "I'm not sure which schema change you mean. Could you spell it out—e.g., adding a `tenant_id` column, splitting `users` into auth vs profile, or dropping the legacy `prefs` JSON?",
    'text_b': 'Which schema change should I draft first — adding a `tenant_id` column, splitting `users` into auth vs profile, or dropping the legacy `prefs` JSON?',
    'ann_a': ['Q o :: Could you spell it out—e.g., adding a `tenant_id` column, splitting `users` into auth vs profile, or dropping the legacy `prefs` JSON?'],
    'ann_b': ['Q m :: Which schema change should I draft first — adding a `tenant_id` column, splitting `users` into auth vs profile, or dropping the legacy `prefs` JSON?', 'O adding a `tenant_id` column', 'O splitting `users` into auth vs profile', 'O dropping the legacy `prefs` JSON'],
  },
  {
    'n': 604,
    'boundary': 'examples/options',
    'note_a': 'such as auth mechanisms -> open',
    'note_b': 'same mechanisms as choose -> multi_choice',
    'text_a': 'Before I touch the gateway, what auth path are you aiming for—such as API keys, OAuth2 client credentials, or session cookies?',
    'text_b': 'Before I touch the gateway, which auth path should I implement — API keys, OAuth2 client credentials, or session cookies?',
    'ann_a': ['Q o :: Before I touch the gateway, what auth path are you aiming for—such as API keys, OAuth2 client credentials, or session cookies?'],
    'ann_b': ['Q m :: Before I touch the gateway, which auth path should I implement — API keys, OAuth2 client credentials, or session cookies?', 'O API keys', 'O OAuth2 client credentials', 'O session cookies'],
  },
  {
    'n': 605,
    'boundary': 'examples/options',
    'note_a': 'e.g. two flake symptoms -> open',
    'note_b': 'same two as either_or',
    'text_a': 'The suite is flaky on main. Could you say what you saw—e.g. a timeout in `test_checkout` or an assertion in `test_cart`?',
    'text_b': 'The suite is flaky on main. Which failure should I chase — a timeout in `test_checkout` or an assertion in `test_cart`?',
    'ann_a': ['Q o :: Could you say what you saw—e.g. a timeout in `test_checkout` or an assertion in `test_cart`?'],
    'ann_b': ['Q e :: Which failure should I chase — a timeout in `test_checkout` or an assertion in `test_cart`?', 'O a timeout in `test_checkout`', 'O an assertion in `test_cart`'],
  },
  {
    'n': 606,
    'boundary': 'examples/options',
    'note_a': 'e.g. UI states illustrate -> open',
    'note_b': 'same states as multi_choice preference',
    'text_a': 'The empty-state mock looks fine locally. What still feels off—e.g., spacing, copy tone, or the CTA placement—or something else?',
    'text_b': 'The empty-state mock looks fine locally. Which should we tweak next — spacing, copy tone, or the CTA placement?',
    'ann_a': ['Q o :: What still feels off—e.g., spacing, copy tone, or the CTA placement—or something else?'],
    'ann_b': ['Q m :: Which should we tweak next — spacing, copy tone, or the CTA placement?', 'O spacing', 'O copy tone', 'O the CTA placement'],
  },
  {
    'n': 607,
    'boundary': 'examples/options',
    'note_a': 'e.g. list illustrates -> open',
    'note_b': 'agent offers action among same -> multi_choice propose',
    'text_a': 'The image recipe is still fuzzy. Could you say what matters in the Dockerfile—e.g., the runtime base (`alpine` vs `distroless`), the non-root user, or the healthcheck?',
    'text_b': 'Image build succeeded. Want me to harden the runtime base (`alpine` vs `distroless`), the non-root user, or the healthcheck next?',
    'ann_a': ['Q o :: Could you say what matters in the Dockerfile—e.g., the runtime base (`alpine` vs `distroless`), the non-root user, or the healthcheck?'],
    'ann_b': ['Q m p :: Want me to harden the runtime base (`alpine` vs `distroless`), the non-root user, or the healthcheck next?', 'O the runtime base (`alpine` vs `distroless`)', 'O the non-root user', 'O the healthcheck'],
  },
  {
    'n': 608,
    'boundary': 'examples/options',
    'note_a': 'such as redis keys -> open',
    'note_b': 'same keys as multi_choice',
    'text_a': 'Cache miss rate spiked. Could you point me at the hot key pattern—such as `sess:*`, `rate:*`, or `feed:{user}`?',
    'text_b': 'Cache miss rate spiked. Which key pattern should I sample first — `sess:*`, `rate:*`, or `feed:{user}`?',
    'ann_a': ['Q o :: Could you point me at the hot key pattern—such as `sess:*`, `rate:*`, or `feed:{user}`?'],
    'ann_b': ['Q m :: Which key pattern should I sample first — `sess:*`, `rate:*`, or `feed:{user}`?', 'O `sess:*`', 'O `rate:*`', 'O `feed:{user}`'],
  },
  {
    'n': 609,
    'boundary': 'examples/options',
    'note_a': 'e.g. git ops illustrate -> open',
    'note_b': 'same ops as either_or preference',
    'text_a': 'Branch is 3 commits behind origin/main. What did you have in mind—e.g. a rebase onto main or a merge commit?',
    'text_b': 'Branch is 3 commits behind origin/main. Which do you prefer — a rebase onto main or a merge commit?',
    'ann_a': ['Q o :: What did you have in mind—e.g. a rebase onto main or a merge commit?'],
    'ann_b': ['Q e :: Which do you prefer — a rebase onto main or a merge commit?', 'O a rebase onto main', 'O a merge commit'],
  },
  {
    'n': 610,
    'boundary': 'examples/options',
    'note_a': 'e.g. doc sections -> open',
    'note_b': 'Shall I among same sections -> multi_choice propose',
    'text_a': 'README is sparse on ops. Could you say which gap matters—e.g. local setup, env vars, or the deploy runbook—or something else?',
    'text_b': 'README is sparse on ops. Shall I expand local setup, env vars, or the deploy runbook first?',
    'ann_a': ['Q o :: Could you say which gap matters—e.g. local setup, env vars, or the deploy runbook—or something else?'],
    'ann_b': ['Q m p :: Shall I expand local setup, env vars, or the deploy runbook first?', 'O local setup', 'O env vars', 'O the deploy runbook'],
  },
  {
    'n': 611,
    'boundary': 'examples/options',
    'note_a': 'e.g. list illustrates -> open',
    'note_b': 'same sites as multi_choice',
    'text_a': 'I need a breadcrumb from the crash. Could you paste something useful—e.g., the top frame in `worker.py`, the SQL that ran, or the request id?',
    'text_b': 'Stack dump is truncated in the ticket. Which should I ask for in the follow-up — the top frame in `worker.py`, the SQL that ran, or the request id?',
    'ann_a': ['Q o :: Could you paste something useful—e.g., the top frame in `worker.py`, the SQL that ran, or the request id?'],
    'ann_b': ['Q m :: Which should I ask for in the follow-up — the top frame in `worker.py`, the SQL that ran, or the request id?', 'O the top frame in `worker.py`', 'O the SQL that ran', 'O the request id'],
  },
  {
    'n': 612,
    'boundary': 'examples/options',
    'note_a': 'such as GraphQL ops -> open',
    'note_b': 'same ops as multi_choice',
    'text_a': 'Schema compile is green. What still worries you—such as the `User` type, the `search` query, or the mutation error union?',
    'text_b': 'Schema compile is green. Which should we review next — the `User` type, the `search` query, or the mutation error union?',
    'ann_a': ['Q o :: What still worries you—such as the `User` type, the `search` query, or the mutation error union?'],
    'ann_b': ['Q m :: Which should we review next — the `User` type, the `search` query, or the mutation error union?', 'O the `User` type', 'O the `search` query', 'O the mutation error union'],
  },
  {
    'n': 613,
    'boundary': 'examples/options',
    'note_a': 'e.g. k8s objects -> open',
    'note_b': 'Want me among same -> multi_choice propose',
    'text_a': 'Cluster apply failed mid-rollout. Could you tell me what you saw—e.g. a CrashLoop on the web Deployment, a pending PVC, or an Ingress 404?',
    'text_b': 'Cluster apply failed mid-rollout. Want me to inspect a CrashLoop on the web Deployment, a pending PVC, or an Ingress 404 first?',
    'ann_a': ['Q o :: Could you tell me what you saw—e.g. a CrashLoop on the web Deployment, a pending PVC, or an Ingress 404?'],
    'ann_b': ['Q m p :: Want me to inspect a CrashLoop on the web Deployment, a pending PVC, or an Ingress 404 first?', 'O a CrashLoop on the web Deployment', 'O a pending PVC', 'O an Ingress 404'],
  },
  {
    'n': 614,
    'boundary': 'examples/options',
    'note_a': 'e.g. two perf knobs -> open',
    'note_b': 'same knobs as either_or',
    'text_a': 'p95 climbed after the release. What are you suspecting—e.g. N+1 queries in the list endpoint or lock contention in the writer?',
    'text_b': 'p95 climbed after the release. Which should I profile — N+1 queries in the list endpoint or lock contention in the writer?',
    'ann_a': ['Q o :: What are you suspecting—e.g. N+1 queries in the list endpoint or lock contention in the writer?'],
    'ann_b': ['Q e :: Which should I profile — N+1 queries in the list endpoint or lock contention in the writer?', 'O N+1 queries in the list endpoint', 'O lock contention in the writer'],
  },
  {
    'n': 615,
    'boundary': 'examples/options',
    'note_a': 'e.g. list illustrates -> open',
    'note_b': 'same entrypoints as multi_choice',
    'text_a': 'The CSS regression is vague so far. What looks off in the UI—e.g., the layout in `AppShell`, the token scale, or a media-query breakpoint?',
    'text_b': 'Styles look wrong on mobile. Which should I open first — the layout in `AppShell`, the token scale, or a media-query breakpoint?',
    'ann_a': ['Q o :: What looks off in the UI—e.g., the layout in `AppShell`, the token scale, or a media-query breakpoint?'],
    'ann_b': ['Q m :: Which should I open first — the layout in `AppShell`, the token scale, or a media-query breakpoint?', 'O the layout in `AppShell`', 'O the token scale', 'O a media-query breakpoint'],
  },
  {
    'n': 616,
    'boundary': 'examples/options',
    'note_a': 'such as parquet partitions -> open',
    'note_b': 'same partitions as multi_choice',
    'text_a': 'Job wrote zero rows. Could you narrow the slice—such as `dt=2026-09-24`, `region=eu`, or `source=billing`?',
    'text_b': 'Job wrote zero rows. Which partition should I re-run — `dt=2026-09-24`, `region=eu`, or `source=billing`?',
    'ann_a': ['Q o :: Could you narrow the slice—such as `dt=2026-09-24`, `region=eu`, or `source=billing`?'],
    'ann_b': ['Q m :: Which partition should I re-run — `dt=2026-09-24`, `region=eu`, or `source=billing`?', 'O `dt=2026-09-24`', 'O `region=eu`', 'O `source=billing`'],
  },
  {
    'n': 617,
    'boundary': 'examples/options',
    'note_a': 'e.g. typescript fixes -> open',
    'note_b': 'Shall I among same -> multi_choice propose',
    'text_a': '`tsc` reports 12 errors. What kind of fix are you after—e.g. tightening the `User` type, adding a type guard, or suppressing with a comment—or something else?',
    'text_b': '`tsc` reports 12 errors. Shall I start by tightening the `User` type, adding a type guard, or suppressing with a comment?',
    'ann_a': ['Q o :: What kind of fix are you after—e.g. tightening the `User` type, adding a type guard, or suppressing with a comment—or something else?'],
    'ann_b': ['Q m p :: Shall I start by tightening the `User` type, adding a type guard, or suppressing with a comment?', 'O tightening the `User` type', 'O adding a type guard', 'O suppressing with a comment'],
  },
  {
    'n': 618,
    'boundary': 'examples/options',
    'note_a': 'e.g. two terraform scopes -> open',
    'note_b': 'same scopes as either_or',
    'text_a': 'Plan shows drift. Could you say which stack you mean—e.g. the networking module or the RDS instance?',
    'text_b': 'Plan shows drift. Which stack should I reconcile — the networking module or the RDS instance?',
    'ann_a': ['Q o :: Could you say which stack you mean—e.g. the networking module or the RDS instance?'],
    'ann_b': ['Q e :: Which stack should I reconcile — the networking module or the RDS instance?', 'O the networking module', 'O the RDS instance'],
  },
  {
    'n': 619,
    'boundary': 'examples/options',
    'note_a': 'e.g. list illustrates -> open',
    'note_b': 'same issues as multi_choice',
    'text_a': 'A11y findings are broad. Could you say what you noticed—e.g., missing form labels, low contrast on the sidebar, or skipped heading levels?',
    'text_b': 'Lighthouse a11y score dipped. Which should we fix first — missing form labels, low contrast on the sidebar, or skipped heading levels?',
    'ann_a': ['Q o :: Could you say what you noticed—e.g., missing form labels, low contrast on the sidebar, or skipped heading levels?'],
    'ann_b': ['Q m :: Which should we fix first — missing form labels, low contrast on the sidebar, or skipped heading levels?', 'O missing form labels', 'O low contrast on the sidebar', 'O skipped heading levels'],
  },
  {
    'n': 620,
    'boundary': 'examples/options',
    'note_a': 'such as Sentry filters -> open',
    'note_b': 'Want me among same -> multi_choice propose',
    'text_a': 'Error volume is noisy. What filter would help—such as by release, by `user.id`, or by transaction name?',
    'text_b': 'Error volume is noisy. Want me to filter by release, by `user.id`, or by transaction name?',
    'ann_a': ['Q o :: What filter would help—such as by release, by `user.id`, or by transaction name?'],
    'ann_b': ['Q m p :: Want me to filter by release, by `user.id`, or by transaction name?', 'O by release', 'O by `user.id`', 'O by transaction name'],
  },
  {
    'n': 621,
    'boundary': 'examples/options',
    'note_a': 'e.g. with CODE block then open ask',
    'note_b': 'same items as multi_choice after CODE',
    'text_a': 'Diff so far:\n[CODE]\nCould you say what still needs work—e.g. the retry backoff, the idempotency key, or the dead-letter topic—or something else?',
    'text_b': 'Diff so far:\n[CODE]\nWhich piece should I finish next — the retry backoff, the idempotency key, or the dead-letter topic?',
    'ann_a': ['Q o :: Could you say what still needs work—e.g. the retry backoff, the idempotency key, or the dead-letter topic—or something else?'],
    'ann_b': ['Q m :: Which piece should I finish next — the retry backoff, the idempotency key, or the dead-letter topic?', 'O the retry backoff', 'O the idempotency key', 'O the dead-letter topic'],
  },
  {
    'n': 622,
    'boundary': 'examples/options',
    'note_a': 'e.g. list illustrates -> open',
    'note_b': 'same scripts as multi_choice',
    'text_a': '`package.json` has overlapping scripts. When you say "checks", what did you have in mind—e.g., `lint`, `typecheck`, or `test:unit`?',
    'text_b': '`package.json` has overlapping scripts. Which check should the CI gate run — `lint`, `typecheck`, or `test:unit`?',
    'ann_a': ['Q o :: When you say "checks", what did you have in mind—e.g., `lint`, `typecheck`, or `test:unit`?'],
    'ann_b': ['Q m :: Which check should the CI gate run — `lint`, `typecheck`, or `test:unit`?', 'O `lint`', 'O `typecheck`', 'O `test:unit`'],
  },
  {
    'n': 623,
    'boundary': 'examples/options',
    'note_a': 'such as two API shapes -> open',
    'note_b': 'same shapes as either_or',
    'text_a': 'Pagination is underspecified. What did you want—such as cursor-based pages or offset/limit?',
    'text_b': 'Pagination is underspecified. Which do you prefer — cursor-based pages or offset/limit?',
    'ann_a': ['Q o :: What did you want—such as cursor-based pages or offset/limit?'],
    'ann_b': ['Q e :: Which do you prefer — cursor-based pages or offset/limit?', 'O cursor-based pages', 'O offset/limit'],
  },
  {
    'n': 624,
    'boundary': 'examples/options',
    'note_a': 'e.g. secrets locations -> open',
    'note_b': 'same locations as multi_choice',
    'text_a': "I won't invent credentials. Could you point me where they live—e.g. `.env.local`, 1Password, or the CI secrets store—or something else?",
    'text_b': "I won't invent credentials. Which store should I wire to — `.env.local`, 1Password, or the CI secrets store?",
    'ann_a': ['Q o :: Could you point me where they live—e.g. `.env.local`, 1Password, or the CI secrets store—or something else?'],
    'ann_b': ['Q m :: Which store should I wire to — `.env.local`, 1Password, or the CI secrets store?', 'O `.env.local`', 'O 1Password', 'O the CI secrets store'],
  },
  {
    'n': 625,
    'boundary': 'examples/options',
    'note_a': 'e.g. rust clippy groups -> open',
    'note_b': 'Shall I among same -> multi_choice propose',
    'text_a': 'Clippy is loud on this crate. What severity do you care about—e.g. `correctness`, `perf`, or `style`?',
    'text_b': 'Clippy is loud on this crate. Shall I silence `correctness`, `perf`, or `style` warnings first?',
    'ann_a': ['Q o :: What severity do you care about—e.g. `correctness`, `perf`, or `style`?'],
    'ann_b': ['Q m p :: Shall I silence `correctness`, `perf`, or `style` warnings first?', 'O `correctness`', 'O `perf`', 'O `style`'],
  },
  {
    'n': 626,
    'boundary': 'examples/options',
    'note_a': 'e.g. list illustrates -> open',
    'note_b': 'same flags as multi_choice',
    'text_a': 'Several flags could explain the behavior. Could you say which one you meant—e.g., `checkout_v2`, `pay_retry`, or `edge_cache`?',
    'text_b': 'Rollout looks partial. Which flag should I flip next — `checkout_v2`, `pay_retry`, or `edge_cache`?',
    'ann_a': ['Q o :: Could you say which one you meant—e.g., `checkout_v2`, `pay_retry`, or `edge_cache`?'],
    'ann_b': ['Q m :: Which flag should I flip next — `checkout_v2`, `pay_retry`, or `edge_cache`?', 'O `checkout_v2`', 'O `pay_retry`', 'O `edge_cache`'],
  },
  {
    'n': 627,
    'boundary': 'examples/options',
    'note_a': 'such as log levels -> open',
    'note_b': 'same levels as multi_choice',
    'text_a': 'Noise in prod logs. What level should we keep—such as `error`, `warn`, or `info` for the payment path?',
    'text_b': 'Noise in prod logs. Which level should the payment path keep — `error`, `warn`, or `info`?',
    'ann_a': ['Q o :: What level should we keep—such as `error`, `warn`, or `info` for the payment path?'],
    'ann_b': ['Q m :: Which level should the payment path keep — `error`, `warn`, or `info`?', 'O `error`', 'O `warn`', 'O `info`'],
  },
  {
    'n': 628,
    'boundary': 'examples/options',
    'note_a': 'e.g. two merge strategies -> open',
    'note_b': 'same strategies as either_or',
    'text_a': 'PR has conflicts in `Cargo.lock`. What approach did you want—e.g. accept theirs for the lockfile or regenerate after resolving sources?',
    'text_b': 'PR has conflicts in `Cargo.lock`. Which approach do you want — accept theirs for the lockfile or regenerate after resolving sources?',
    'ann_a': ['Q o :: What approach did you want—e.g. accept theirs for the lockfile or regenerate after resolving sources?'],
    'ann_b': ['Q e :: Which approach do you want — accept theirs for the lockfile or regenerate after resolving sources?', 'O accept theirs for the lockfile', 'O regenerate after resolving sources'],
  },
  {
    'n': 629,
    'boundary': 'examples/options',
    'note_a': 'e.g. URL doc links illustrate -> open',
    'note_b': 'same doc areas as multi_choice',
    'text_a': 'I found the vendor notes at [URL]. Could you say which part you need—e.g. the auth section, the rate-limit table, or the webhook payload—or something else?',
    'text_b': 'I found the vendor notes at [URL]. Which part should I extract — the auth section, the rate-limit table, or the webhook payload?',
    'ann_a': ['Q o :: Could you say which part you need—e.g. the auth section, the rate-limit table, or the webhook payload—or something else?'],
    'ann_b': ['Q m :: Which part should I extract — the auth section, the rate-limit table, or the webhook payload?', 'O the auth section', 'O the rate-limit table', 'O the webhook payload'],
  },
  {
    'n': 630,
    'boundary': 'examples/options',
    'note_a': 'e.g. list illustrates -> open',
    'note_b': 'Want me among same -> multi_choice propose',
    'text_a': 'Celery lag showed up. Could you say which queue felt slow—e.g., `default`, `email`, or `billing`?',
    'text_b': 'Workers are backed up. Want me to drain `default`, `email`, or `billing` first?',
    'ann_a': ['Q o :: Could you say which queue felt slow—e.g., `default`, `email`, or `billing`?'],
    'ann_b': ['Q m p :: Want me to drain `default`, `email`, or `billing` first?', 'O `default`', 'O `email`', 'O `billing`'],
  },
  {
    'n': 631,
    'boundary': 'examples/options',
    'note_a': 'such as pytest markers -> open',
    'note_b': 'same markers as multi_choice',
    'text_a': 'Selecting tests is unclear. What marker set should I use—such as `unit`, `integration`, or `slow`?',
    'text_b': 'Selecting tests is unclear. Which marker set should CI run — `unit`, `integration`, or `slow`?',
    'ann_a': ['Q o :: What marker set should I use—such as `unit`, `integration`, or `slow`?'],
    'ann_b': ['Q m :: Which marker set should CI run — `unit`, `integration`, or `slow`?', 'O `unit`', 'O `integration`', 'O `slow`'],
  },
  {
    'n': 632,
    'boundary': 'examples/options',
    'note_a': 'e.g. two CSS approaches -> open',
    'note_b': 'same approaches as either_or',
    'text_a': 'Sidebar animation is janky. What fix are you leaning toward—e.g. CSS transitions or a Framer Motion spring?',
    'text_b': 'Sidebar animation is janky. Which fix do you prefer — CSS transitions or a Framer Motion spring?',
    'ann_a': ['Q o :: What fix are you leaning toward—e.g. CSS transitions or a Framer Motion spring?'],
    'ann_b': ['Q e :: Which fix do you prefer — CSS transitions or a Framer Motion spring?', 'O CSS transitions', 'O a Framer Motion spring'],
  },
  {
    'n': 633,
    'boundary': 'examples/options',
    'note_a': 'e.g. Postgres indexes -> open',
    'note_b': 'same indexes as multi_choice',
    'text_a': "`EXPLAIN` is ugly on `orders`. Could you say which index idea matches—e.g. `(user_id, created_at)`, a partial on `status='open'`, or a GIN on `meta`—or something else?",
    'text_b': "`EXPLAIN` is ugly on `orders`. Which index should I add — `(user_id, created_at)`, a partial on `status='open'`, or a GIN on `meta`?",
    'ann_a': ["Q o :: Could you say which index idea matches—e.g. `(user_id, created_at)`, a partial on `status='open'`, or a GIN on `meta`—or something else?"],
    'ann_b': ["Q m :: Which index should I add — `(user_id, created_at)`, a partial on `status='open'`, or a GIN on `meta`?", 'O `(user_id, created_at)`', "O a partial on `status='open'`", 'O a GIN on `meta`'],
  },
  {
    'n': 634,
    'boundary': 'examples/options',
    'note_a': 'e.g. list illustrates -> open',
    'note_b': 'same packages as multi_choice',
    'text_a': 'Monorepo touchpoints are wide. What package did you mean—e.g., `@app/web`, `@app/api`, or `@lib/ui`?',
    'text_b': 'Build graph is huge. Which package should I build — `@app/web`, `@app/api`, or `@lib/ui`?',
    'ann_a': ['Q o :: What package did you mean—e.g., `@app/web`, `@app/api`, or `@lib/ui`?'],
    'ann_b': ['Q m :: Which package should I build — `@app/web`, `@app/api`, or `@lib/ui`?', 'O `@app/web`', 'O `@app/api`', 'O `@lib/ui`'],
  },
  {
    'n': 635,
    'boundary': 'examples/options',
    'note_a': 'such as CDN behaviors -> open',
    'note_b': 'Shall I among same -> multi_choice propose',
    'text_a': 'Cache headers look wrong at the edge. What behavior did you want—such as `s-maxage`, stale-while-revalidate, or a hard purge path?',
    'text_b': 'Cache headers look wrong at the edge. Shall I adjust `s-maxage`, stale-while-revalidate, or a hard purge path?',
    'ann_a': ['Q o :: What behavior did you want—such as `s-maxage`, stale-while-revalidate, or a hard purge path?'],
    'ann_b': ['Q m p :: Shall I adjust `s-maxage`, stale-while-revalidate, or a hard purge path?', 'O `s-maxage`', 'O stale-while-revalidate', 'O a hard purge path'],
  },
  {
    'n': 636,
    'boundary': 'examples/options',
    'note_a': 'e.g. two SQLite modes -> open',
    'note_b': 'same modes as either_or',
    'text_a': 'Local DB is locking under write load. What mode are you aiming for—e.g. WAL journaling or a single-writer queue?',
    'text_b': 'Local DB is locking under write load. Which mode should I enable — WAL journaling or a single-writer queue?',
    'ann_a': ['Q o :: What mode are you aiming for—e.g. WAL journaling or a single-writer queue?'],
    'ann_b': ['Q e :: Which mode should I enable — WAL journaling or a single-writer queue?', 'O WAL journaling', 'O a single-writer queue'],
  },
  {
    'n': 637,
    'boundary': 'examples/options',
    'note_a': 'e.g. OpenAPI gaps -> open',
    'note_b': 'same gaps as multi_choice',
    'text_a': 'Spec drift vs implementation. Could you point at the mismatch—e.g. missing `401` responses, wrong path params, or an undeclared header—or something else?',
    'text_b': 'Spec drift vs implementation. Which mismatch should I reconcile first — missing `401` responses, wrong path params, or an undeclared header?',
    'ann_a': ['Q o :: Could you point at the mismatch—e.g. missing `401` responses, wrong path params, or an undeclared header—or something else?'],
    'ann_b': ['Q m :: Which mismatch should I reconcile first — missing `401` responses, wrong path params, or an undeclared header?', 'O missing `401` responses', 'O wrong path params', 'O an undeclared header'],
  },
  {
    'n': 638,
    'boundary': 'examples/options',
    'note_a': 'e.g. list illustrates -> open',
    'note_b': 'Want me among same -> multi_choice propose',
    'text_a': 'Bundle size jumped. Any sense what landed—e.g., `moment`, `lodash` full import, or a heavy icon pack?',
    'text_b': 'Bundle size jumped 180KB. Want me to trim `moment`, `lodash` full import, or a heavy icon pack?',
    'ann_a': ['Q o :: Any sense what landed—e.g., `moment`, `lodash` full import, or a heavy icon pack?'],
    'ann_b': ['Q m p :: Want me to trim `moment`, `lodash` full import, or a heavy icon pack?', 'O `moment`', 'O `lodash` full import', 'O a heavy icon pack'],
  },
  {
    'n': 639,
    'boundary': 'examples/options',
    'note_a': 'such as email templates -> open',
    'note_b': 'same templates as multi_choice',
    'text_a': 'Copy review is vague. Which template are we talking about—such as welcome, password reset, or invoice receipt?',
    'text_b': 'Copy review is vague. Which template should I edit — welcome, password reset, or invoice receipt?',
    'ann_a': ['Q o :: Which template are we talking about—such as welcome, password reset, or invoice receipt?'],
    'ann_b': ['Q m :: Which template should I edit — welcome, password reset, or invoice receipt?', 'O welcome', 'O password reset', 'O invoice receipt'],
  },
  {
    'n': 640,
    'boundary': 'examples/options',
    'note_a': 'e.g. two Helm values -> open',
    'note_b': 'same values as either_or',
    'text_a': 'Chart install needs a values override. What should I set—e.g. `replicaCount=3` or `resources.limits.memory=1Gi`?',
    'text_b': 'Chart install needs a values override. Which should I set — `replicaCount=3` or `resources.limits.memory=1Gi`?',
    'ann_a': ['Q o :: What should I set—e.g. `replicaCount=3` or `resources.limits.memory=1Gi`?'],
    'ann_b': ['Q e :: Which should I set — `replicaCount=3` or `resources.limits.memory=1Gi`?', 'O `replicaCount=3`', 'O `resources.limits.memory=1Gi`'],
  },
  {
    'n': 641,
    'boundary': 'examples/options',
    'note_a': 'e.g. flake flake causes -> open',
    'note_b': 'same causes as multi_choice',
    'text_a': 'Nightly is red again. Could you describe the failure mode—e.g. race in the fixture, clock skew, or a leaked temp dir—or something else?',
    'text_b': 'Nightly is red again. Which failure mode should I harden against — race in the fixture, clock skew, or a leaked temp dir?',
    'ann_a': ['Q o :: Could you describe the failure mode—e.g. race in the fixture, clock skew, or a leaked temp dir—or something else?'],
    'ann_b': ['Q m :: Which failure mode should I harden against — race in the fixture, clock skew, or a leaked temp dir?', 'O race in the fixture', 'O clock skew', 'O a leaked temp dir'],
  },
  {
    'n': 642,
    'boundary': 'examples/options',
    'note_a': 'e.g. list illustrates -> open',
    'note_b': 'same locales as multi_choice',
    'text_a': 'i18n gaps remain. What locale are we prioritizing in your head—e.g., `de`, `fr`, or `ja`?',
    'text_b': 'String extraction found gaps. Which locale should I fill first — `de`, `fr`, or `ja`?',
    'ann_a': ['Q o :: What locale are we prioritizing in your head—e.g., `de`, `fr`, or `ja`?'],
    'ann_b': ['Q m :: Which locale should I fill first — `de`, `fr`, or `ja`?', 'O `de`', 'O `fr`', 'O `ja`'],
  },
  {
    'n': 643,
    'boundary': 'examples/options',
    'note_a': 'such as gRPC statuses -> open',
    'note_b': 'same statuses as multi_choice',
    'text_a': 'Client retries look wrong. What status should map to retry—such as `UNAVAILABLE`, `DEADLINE_EXCEEDED`, or `RESOURCE_EXHAUSTED`?',
    'text_b': 'Client retries look wrong. Which status should trigger retry — `UNAVAILABLE`, `DEADLINE_EXCEEDED`, or `RESOURCE_EXHAUSTED`?',
    'ann_a': ['Q o :: What status should map to retry—such as `UNAVAILABLE`, `DEADLINE_EXCEEDED`, or `RESOURCE_EXHAUSTED`?'],
    'ann_b': ['Q m :: Which status should trigger retry — `UNAVAILABLE`, `DEADLINE_EXCEEDED`, or `RESOURCE_EXHAUSTED`?', 'O `UNAVAILABLE`', 'O `DEADLINE_EXCEEDED`', 'O `RESOURCE_EXHAUSTED`'],
  },
  {
    'n': 644,
    'boundary': 'examples/options',
    'note_a': 'e.g. two lint rule severities -> open',
    'note_b': 'same severities as either_or',
    'text_a': '`no-floating-promises` is noisy. What severity do you want—e.g. error or warn?',
    'text_b': '`no-floating-promises` is noisy. Which severity do you want — error or warn?',
    'ann_a': ['Q o :: What severity do you want—e.g. error or warn?'],
    'ann_b': ['Q e :: Which severity do you want — error or warn?', 'O error', 'O warn'],
  },
  {
    'n': 645,
    'boundary': 'examples/options',
    'note_a': 'e.g. with preamble + CODE -> open',
    'note_b': 'same items as multi_choice after status',
    'text_a': 'Migrated the hook; smoke test output:\n[CODE]\nWhat still looks wrong on your side—e.g. the loading spinner, the empty list, or the error toast—or something else?',
    'text_b': 'Migrated the hook; smoke test output:\n[CODE]\nWhich UI state should I polish next — the loading spinner, the empty list, or the error toast?',
    'ann_a': ['Q o :: What still looks wrong on your side—e.g. the loading spinner, the empty list, or the error toast—or something else?'],
    'ann_b': ['Q m :: Which UI state should I polish next — the loading spinner, the empty list, or the error toast?', 'O the loading spinner', 'O the empty list', 'O the error toast'],
  },
  {
    'n': 646,
    'boundary': 'examples/options',
    'note_a': 'e.g. list illustrates -> open',
    'note_b': 'Shall I among same -> multi_choice propose',
    'text_a': "S3 layout isn't settled. Where should objects land for you—e.g., `raw/`, `staging/`, or `public/`?",
    'text_b': 'Upload path is ambiguous. Shall I write objects under `raw/`, `staging/`, or `public/`?',
    'ann_a': ["Q o :: S3 layout isn't settled. Where should objects land for you—e.g., `raw/`, `staging/`, or `public/`?"],
    'ann_b': ['Q m p :: Shall I write objects under `raw/`, `staging/`, or `public/`?', 'O `raw/`', 'O `staging/`', 'O `public/`'],
  },
  {
    'n': 647,
    'boundary': 'examples/options',
    'note_a': 'such as cron schedules -> open',
    'note_b': 'same schedules as multi_choice',
    'text_a': "Job frequency isn't specified. What cadence did you mean—such as hourly, daily at 02:00 UTC, or weekly on Monday?",
    'text_b': "Job frequency isn't specified. Which cadence should I configure — hourly, daily at 02:00 UTC, or weekly on Monday?",
    'ann_a': ['Q o :: What cadence did you mean—such as hourly, daily at 02:00 UTC, or weekly on Monday?'],
    'ann_b': ['Q m :: Which cadence should I configure — hourly, daily at 02:00 UTC, or weekly on Monday?', 'O hourly', 'O daily at 02:00 UTC', 'O weekly on Monday'],
  },
  {
    'n': 648,
    'boundary': 'examples/options',
    'note_a': 'e.g. two Zustand stores -> open',
    'note_b': 'same stores as either_or',
    'text_a': 'State is split oddly. Which store holds cart lines—e.g. `useCartStore` or `useCheckoutStore`?',
    'text_b': 'State is split oddly. Which store should hold cart lines — `useCartStore` or `useCheckoutStore`?',
    'ann_a': ['Q o :: Which store holds cart lines—e.g. `useCartStore` or `useCheckoutStore`?'],
    'ann_b': ['Q e :: Which store should hold cart lines — `useCartStore` or `useCheckoutStore`?', 'O `useCartStore`', 'O `useCheckoutStore`'],
  },
  {
    'n': 649,
    'boundary': 'examples/options',
    'note_a': 'e.g. DNS record types -> open',
    'note_b': 'same record types as multi_choice',
    'text_a': 'Domain cutover needs clarity. Could you say which record to change—e.g. the apex `A`, the `www` CNAME, or the MX set—or something else?',
    'text_b': 'Domain cutover needs clarity. Which record should I change — the apex `A`, the `www` CNAME, or the MX set?',
    'ann_a': ['Q o :: Could you say which record to change—e.g. the apex `A`, the `www` CNAME, or the MX set—or something else?'],
    'ann_b': ['Q m :: Which record should I change — the apex `A`, the `www` CNAME, or the MX set?', 'O the apex `A`', 'O the `www` CNAME', 'O the MX set'],
  },
  {
    'n': 650,
    'boundary': 'examples/options',
    'note_a': 'e.g. list illustrates -> open',
    'note_b': 'Want me among same -> multi_choice propose',
    'text_a': 'Playwright matrix is large. Which browser were you watching—e.g., chromium, firefox, or webkit?',
    'text_b': 'E2E suite has three projects. Want me to run chromium, firefox, or webkit first?',
    'ann_a': ['Q o :: Which browser were you watching—e.g., chromium, firefox, or webkit?'],
    'ann_b': ['Q m p :: Want me to run chromium, firefox, or webkit first?', 'O chromium', 'O firefox', 'O webkit'],
  },
  {
    'n': 651,
    'boundary': 'examples/options',
    'note_a': 'such as Kafka topics -> open',
    'note_b': 'same topics as multi_choice',
    'text_a': 'Consumer lag is uneven. Which topic is the one you care about—such as `orders.created`, `orders.paid`, or `orders.shipped`?',
    'text_b': 'Consumer lag is uneven. Which topic should I rebalance — `orders.created`, `orders.paid`, or `orders.shipped`?',
    'ann_a': ['Q o :: Which topic is the one you care about—such as `orders.created`, `orders.paid`, or `orders.shipped`?'],
    'ann_b': ['Q m :: Which topic should I rebalance — `orders.created`, `orders.paid`, or `orders.shipped`?', 'O `orders.created`', 'O `orders.paid`', 'O `orders.shipped`'],
  },
  {
    'n': 652,
    'boundary': 'examples/options',
    'note_a': 'e.g. two Vite plugins -> open',
    'note_b': 'same plugins as either_or',
    'text_a': 'Dev server startup is slow. What are you suspecting—e.g. the SVG plugin or the legacy browser plugin?',
    'text_b': 'Dev server startup is slow. Which plugin should I disable to test — the SVG plugin or the legacy browser plugin?',
    'ann_a': ['Q o :: What are you suspecting—e.g. the SVG plugin or the legacy browser plugin?'],
    'ann_b': ['Q e :: Which plugin should I disable to test — the SVG plugin or the legacy browser plugin?', 'O the SVG plugin', 'O the legacy browser plugin'],
  },
  {
    'n': 653,
    'boundary': 'examples/options',
    'note_a': 'e.g. Alembic revision styles -> open',
    'note_b': 'same styles as multi_choice',
    'text_a': 'Migration naming is inconsistent. What style should new ones follow—e.g. timestamp ids, sequential integers, or descriptive slugs—or something else?',
    'text_b': 'Migration naming is inconsistent. Which style should new ones follow — timestamp ids, sequential integers, or descriptive slugs?',
    'ann_a': ['Q o :: What style should new ones follow—e.g. timestamp ids, sequential integers, or descriptive slugs—or something else?'],
    'ann_b': ['Q m :: Which style should new ones follow — timestamp ids, sequential integers, or descriptive slugs?', 'O timestamp ids', 'O sequential integers', 'O descriptive slugs'],
  },
  {
    'n': 654,
    'boundary': 'examples/options',
    'note_a': 'e.g. list illustrates -> open',
    'note_b': 'same channels as multi_choice',
    'text_a': 'Pager routing is ambiguous. Where should pages go—e.g., `#ops`, `#payments`, or `#platform`?',
    'text_b': 'Alert routing is unspecified. Which channel should pages go to — `#ops`, `#payments`, or `#platform`?',
    'ann_a': ['Q o :: Pager routing is ambiguous. Where should pages go—e.g., `#ops`, `#payments`, or `#platform`?'],
    'ann_b': ['Q m :: Which channel should pages go to — `#ops`, `#payments`, or `#platform`?', 'O `#ops`', 'O `#payments`', 'O `#platform`'],
  },
  {
    'n': 655,
    'boundary': 'examples/options',
    'note_a': 'such as JWT claims -> open',
    'note_b': 'Shall I among same -> multi_choice propose',
    'text_a': 'Token payload is bloated. What claim can we drop—such as `roles`, `locale`, or `feature_flags`?',
    'text_b': 'Token payload is bloated. Shall I drop `roles`, `locale`, or `feature_flags` from the JWT?',
    'ann_a': ['Q o :: What claim can we drop—such as `roles`, `locale`, or `feature_flags`?'],
    'ann_b': ['Q m p :: Shall I drop `roles`, `locale`, or `feature_flags` from the JWT?', 'O `roles`', 'O `locale`', 'O `feature_flags`'],
  },
  {
    'n': 656,
    'boundary': 'examples/options',
    'note_a': 'e.g. two CSS modules vs Tailwind -> open',
    'note_b': 'same styling systems as either_or',
    'text_a': 'New page styling is undecided. What system should it use—e.g. CSS modules or Tailwind utilities?',
    'text_b': 'New page styling is undecided. Which system should it use — CSS modules or Tailwind utilities?',
    'ann_a': ['Q o :: What system should it use—e.g. CSS modules or Tailwind utilities?'],
    'ann_b': ['Q e :: Which system should it use — CSS modules or Tailwind utilities?', 'O CSS modules', 'O Tailwind utilities'],
  },
  {
    'n': 657,
    'boundary': 'examples/options',
    'note_a': 'e.g. Prometheus metrics -> open',
    'note_b': 'same metrics as multi_choice',
    'text_a': 'Dashboard is empty. Could you say which series you expected—e.g. `http_request_duration_seconds`, `queue_depth`, or `db_pool_in_use`—or something else?',
    'text_b': 'Dashboard is empty. Which series should I plot first — `http_request_duration_seconds`, `queue_depth`, or `db_pool_in_use`?',
    'ann_a': ['Q o :: Could you say which series you expected—e.g. `http_request_duration_seconds`, `queue_depth`, or `db_pool_in_use`—or something else?'],
    'ann_b': ['Q m :: Which series should I plot first — `http_request_duration_seconds`, `queue_depth`, or `db_pool_in_use`?', 'O `http_request_duration_seconds`', 'O `queue_depth`', 'O `db_pool_in_use`'],
  },
  {
    'n': 658,
    'boundary': 'examples/options',
    'note_a': 'e.g. list illustrates -> open',
    'note_b': 'Want me among same -> multi_choice propose',
    'text_a': 'Next.js groups overlap. Which area felt broken—e.g., `(marketing)`, `(app)`, or `(admin)`?',
    'text_b': 'App router layout is tangled. Want me to untangle `(marketing)`, `(app)`, or `(admin)` first?',
    'ann_a': ['Q o :: Which area felt broken—e.g., `(marketing)`, `(app)`, or `(admin)`?'],
    'ann_b': ['Q m p :: Want me to untangle `(marketing)`, `(app)`, or `(admin)` first?', 'O `(marketing)`', 'O `(app)`', 'O `(admin)`'],
  },
  {
    'n': 659,
    'boundary': 'examples/options',
    'note_a': 'such as Gradle tasks -> open',
    'note_b': 'same tasks as multi_choice',
    'text_a': 'CI matrix is slow. Which Gradle task is essential—such as `assembleDebug`, `test`, or `lint`?',
    'text_b': 'CI matrix is slow. Which Gradle task should stay in the required check — `assembleDebug`, `test`, or `lint`?',
    'ann_a': ['Q o :: Which Gradle task is essential—such as `assembleDebug`, `test`, or `lint`?'],
    'ann_b': ['Q m :: Which Gradle task should stay in the required check — `assembleDebug`, `test`, or `lint`?', 'O `assembleDebug`', 'O `test`', 'O `lint`'],
  },
  {
    'n': 660,
    'boundary': 'examples/options',
    'note_a': 'e.g. two protobuf codecs -> open',
    'note_b': 'same codecs as either_or',
    'text_a': 'Wire format negotiation is fuzzy. What encoding should clients default to—e.g. protobuf binary or JSON mapping?',
    'text_b': 'Wire format negotiation is fuzzy. Which encoding should clients default to — protobuf binary or JSON mapping?',
    'ann_a': ['Q o :: What encoding should clients default to—e.g. protobuf binary or JSON mapping?'],
    'ann_b': ['Q e :: Which encoding should clients default to — protobuf binary or JSON mapping?', 'O protobuf binary', 'O JSON mapping'],
  },
  {
    'n': 661,
    'boundary': 'examples/options',
    'note_a': 'e.g. ESLint flat-config files -> open',
    'note_b': 'same configs as multi_choice',
    'text_a': 'Lint config is split across packages. Could you say which file is canonical—e.g. `eslint.config.mjs`, `packages/web/eslint.config.mjs`, or the shared preset—or something else?',
    'text_b': 'Lint config is split across packages. Which file should be canonical — `eslint.config.mjs`, `packages/web/eslint.config.mjs`, or the shared preset?',
    'ann_a': ['Q o :: Could you say which file is canonical—e.g. `eslint.config.mjs`, `packages/web/eslint.config.mjs`, or the shared preset—or something else?'],
    'ann_b': ['Q m :: Which file should be canonical — `eslint.config.mjs`, `packages/web/eslint.config.mjs`, or the shared preset?', 'O `eslint.config.mjs`', 'O `packages/web/eslint.config.mjs`', 'O the shared preset'],
  },
  {
    'n': 662,
    'boundary': 'examples/options',
    'note_a': 'e.g. list illustrates -> open',
    'note_b': 'same syncs as multi_choice',
    'text_a': 'Airbyte had multiple sync errors. Which source was it—e.g., Salesforce, Stripe, or HubSpot?',
    'text_b': 'Warehouse tables look stale. Which sync should I re-run — Salesforce, Stripe, or HubSpot?',
    'ann_a': ['Q o :: Which source was it—e.g., Salesforce, Stripe, or HubSpot?'],
    'ann_b': ['Q m :: Which sync should I re-run — Salesforce, Stripe, or HubSpot?', 'O Salesforce', 'O Stripe', 'O HubSpot'],
  },
  {
    'n': 663,
    'boundary': 'examples/options',
    'note_a': 'such as CSP directives -> open',
    'note_b': 'Shall I among same -> multi_choice propose',
    'text_a': 'Browser console shows CSP blocks. What directive is too tight—such as `script-src`, `img-src`, or `connect-src`?',
    'text_b': 'Browser console shows CSP blocks. Shall I loosen `script-src`, `img-src`, or `connect-src`?',
    'ann_a': ['Q o :: What directive is too tight—such as `script-src`, `img-src`, or `connect-src`?'],
    'ann_b': ['Q m p :: Shall I loosen `script-src`, `img-src`, or `connect-src`?', 'O `script-src`', 'O `img-src`', 'O `connect-src`'],
  },
  {
    'n': 664,
    'boundary': 'examples/options',
    'note_a': 'e.g. two conda envs -> open',
    'note_b': 'same envs as either_or',
    'text_a': 'Import paths resolve differently per shell. Which env were you in—e.g. `ml-train` or `ml-serve`?',
    'text_b': 'Import paths resolve differently per shell. Which env should docs assume — `ml-train` or `ml-serve`?',
    'ann_a': ['Q o :: Which env were you in—e.g. `ml-train` or `ml-serve`?'],
    'ann_b': ['Q e :: Which env should docs assume — `ml-train` or `ml-serve`?', 'O `ml-train`', 'O `ml-serve`'],
  },
  {
    'n': 665,
    'boundary': 'examples/options',
    'note_a': 'e.g. with URL docs then open',
    'note_b': 'same API areas as multi_choice',
    'text_a': 'Partner docs are at [URL]. What endpoint family do you need—e.g. catalog, inventory, or fulfillment—or something else?',
    'text_b': 'Partner docs are at [URL]. Which endpoint family should I implement first — catalog, inventory, or fulfillment?',
    'ann_a': ['Q o :: What endpoint family do you need—e.g. catalog, inventory, or fulfillment—or something else?'],
    'ann_b': ['Q m :: Which endpoint family should I implement first — catalog, inventory, or fulfillment?', 'O catalog', 'O inventory', 'O fulfillment'],
  },
  {
    'n': 666,
    'boundary': 'examples/options',
    'note_a': 'e.g. list illustrates -> open',
    'note_b': 'Want me among same -> multi_choice propose',
    'text_a': 'SwiftUI preview failed. Which device preset were you on—e.g., iPhone SE, iPhone 16 Pro, or iPad mini?',
    'text_b': 'Preview canvas crashed. Want me to reproduce on iPhone SE, iPhone 16 Pro, or iPad mini?',
    'ann_a': ['Q o :: Which device preset were you on—e.g., iPhone SE, iPhone 16 Pro, or iPad mini?'],
    'ann_b': ['Q m p :: Want me to reproduce on iPhone SE, iPhone 16 Pro, or iPad mini?', 'O iPhone SE', 'O iPhone 16 Pro', 'O iPad mini'],
  },
  {
    'n': 667,
    'boundary': 'examples/options',
    'note_a': 'such as ClickHouse engines -> open',
    'note_b': 'same engines as multi_choice',
    'text_a': 'Table engine choice is open. What did you have in mind—such as MergeTree, ReplacingMergeTree, or AggregatingMergeTree?',
    'text_b': 'Table engine choice is open. Which engine should we use — MergeTree, ReplacingMergeTree, or AggregatingMergeTree?',
    'ann_a': ['Q o :: What did you have in mind—such as MergeTree, ReplacingMergeTree, or AggregatingMergeTree?'],
    'ann_b': ['Q m :: Which engine should we use — MergeTree, ReplacingMergeTree, or AggregatingMergeTree?', 'O MergeTree', 'O ReplacingMergeTree', 'O AggregatingMergeTree'],
  },
  {
    'n': 668,
    'boundary': 'examples/options',
    'note_a': 'e.g. two release channels -> open',
    'note_b': 'same channels as either_or',
    'text_a': 'Electron update feed is unset. Which channel should builds publish to—e.g. `beta` or `stable`?',
    'text_b': 'Electron update feed is unset. Which channel should builds publish to — `beta` or `stable`?',
    'ann_a': ['Q o :: Which channel should builds publish to—e.g. `beta` or `stable`?'],
    'ann_b': ['Q e :: Which channel should builds publish to — `beta` or `stable`?', 'O `beta`', 'O `stable`'],
  },
  {
    'n': 669,
    'boundary': 'examples/options',
    'note_a': 'e.g. Storybook stories -> open',
    'note_b': 'same stories as multi_choice',
    'text_a': 'Component API shifted. Could you say which story is broken—e.g. Default, WithError, or Loading—or something else?',
    'text_b': 'Component API shifted. Which story should I update first — Default, WithError, or Loading?',
    'ann_a': ['Q o :: Could you say which story is broken—e.g. Default, WithError, or Loading—or something else?'],
    'ann_b': ['Q m :: Which story should I update first — Default, WithError, or Loading?', 'O Default', 'O WithError', 'O Loading'],
  },
  {
    'n': 670,
    'boundary': 'examples/options',
    'note_a': 'e.g. list illustrates -> open',
    'note_b': 'same locations as multi_choice',
    'text_a': 'Nginx looked wrong. Which location block is involved—e.g., `/api`, `/static`, or `/ws`?',
    'text_b': 'Proxy returned 502. Which `location` block should I check — `/api`, `/static`, or `/ws`?',
    'ann_a': ['Q o :: Which location block is involved—e.g., `/api`, `/static`, or `/ws`?'],
    'ann_b': ['Q m :: Which `location` block should I check — `/api`, `/static`, or `/ws`?', 'O `/api`', 'O `/static`', 'O `/ws`'],
  },
  {
    'n': 671,
    'boundary': 'examples/options',
    'note_a': 'such as pandas dtypes -> open',
    'note_b': 'Shall I among same -> multi_choice propose',
    'text_a': 'CSV ingest is inferring badly. What dtype should `amount` use—such as `float64`, `Decimal`, or `Int64`?',
    'text_b': 'CSV ingest is inferring badly. Shall I cast `amount` to `float64`, `Decimal`, or `Int64`?',
    'ann_a': ['Q o :: What dtype should `amount` use—such as `float64`, `Decimal`, or `Int64`?'],
    'ann_b': ['Q m p :: Shall I cast `amount` to `float64`, `Decimal`, or `Int64`?', 'O `float64`', 'O `Decimal`', 'O `Int64`'],
  },
  {
    'n': 672,
    'boundary': 'examples/options',
    'note_a': 'e.g. two soft-delete strategies -> open',
    'note_b': 'same strategies as either_or',
    'text_a': 'Delete semantics are unclear. What did you want—e.g. a `deleted_at` column or a tombstone flag?',
    'text_b': 'Delete semantics are unclear. Which do you prefer — a `deleted_at` column or a tombstone flag?',
    'ann_a': ['Q o :: What did you want—e.g. a `deleted_at` column or a tombstone flag?'],
    'ann_b': ['Q e :: Which do you prefer — a `deleted_at` column or a tombstone flag?', 'O a `deleted_at` column', 'O a tombstone flag'],
  },
  {
    'n': 673,
    'boundary': 'examples/options',
    'note_a': 'e.g. GitHub Actions jobs -> open',
    'note_b': 'same jobs as multi_choice',
    'text_a': 'Workflow failed mid-matrix. Could you say which job—e.g. `build`, `test-node`, or `publish`—or something else?',
    'text_b': 'Workflow failed mid-matrix. Which job should I re-run — `build`, `test-node`, or `publish`?',
    'ann_a': ['Q o :: Could you say which job—e.g. `build`, `test-node`, or `publish`—or something else?'],
    'ann_b': ['Q m :: Which job should I re-run — `build`, `test-node`, or `publish`?', 'O `build`', 'O `test-node`', 'O `publish`'],
  },
  {
    'n': 674,
    'boundary': 'examples/options',
    'note_a': 'e.g. list illustrates -> open',
    'note_b': 'same breakpoints as multi_choice',
    'text_a': 'Responsive bug. Which breakpoint showed it—e.g., `sm`, `md`, or `lg`?',
    'text_b': 'Layout breaks between sizes. Which breakpoint should I fix first — `sm`, `md`, or `lg`?',
    'ann_a': ['Q o :: Which breakpoint showed it—e.g., `sm`, `md`, or `lg`?'],
    'ann_b': ['Q m :: Which breakpoint should I fix first — `sm`, `md`, or `lg`?', 'O `sm`', 'O `md`', 'O `lg`'],
  },
  {
    'n': 675,
    'boundary': 'examples/options',
    'note_a': 'such as OTEL exporters -> open',
    'note_b': 'Want me among same -> multi_choice propose',
    'text_a': "Traces aren't landing. What exporter config matches your stack—such as OTLP/HTTP, Jaeger, or Zipkin?",
    'text_b': "Traces aren't landing. Want me to switch to OTLP/HTTP, Jaeger, or Zipkin?",
    'ann_a': ['Q o :: What exporter config matches your stack—such as OTLP/HTTP, Jaeger, or Zipkin?'],
    'ann_b': ['Q m p :: Want me to switch to OTLP/HTTP, Jaeger, or Zipkin?', 'O OTLP/HTTP', 'O Jaeger', 'O Zipkin'],
  },
  {
    'n': 676,
    'boundary': 'examples/options',
    'note_a': 'e.g. two Python packaging tools -> open',
    'note_b': 'same tools as either_or',
    'text_a': 'Lockfile format is undecided. What tool should we standardize on—e.g. `uv` or `poetry`?',
    'text_b': 'Lockfile format is undecided. Which tool should we standardize on — `uv` or `poetry`?',
    'ann_a': ['Q o :: What tool should we standardize on—e.g. `uv` or `poetry`?'],
    'ann_b': ['Q e :: Which tool should we standardize on — `uv` or `poetry`?', 'O `uv`', 'O `poetry`'],
  },
  {
    'n': 677,
    'boundary': 'examples/options',
    'note_a': 'e.g. with CODE snippet then open',
    'note_b': 'same validation modes as multi_choice',
    'text_a': 'Current validator:\n[CODE]\nWhat mode should new fields use—e.g. strict reject, coerce-and-warn, or strip unknown—or something else?',
    'text_b': 'Current validator:\n[CODE]\nWhich mode should new fields use — strict reject, coerce-and-warn, or strip unknown?',
    'ann_a': ['Q o :: What mode should new fields use—e.g. strict reject, coerce-and-warn, or strip unknown—or something else?'],
    'ann_b': ['Q m :: Which mode should new fields use — strict reject, coerce-and-warn, or strip unknown?', 'O strict reject', 'O coerce-and-warn', 'O strip unknown'],
  },
  {
    'n': 678,
    'boundary': 'examples/options',
    'note_a': 'e.g. list illustrates -> open',
    'note_b': 'same rules as multi_choice',
    'text_a': 'Cloudflare rule noise. Which rule id looks wrong—e.g., `100201`, `100215`, or `100340`?',
    'text_b': 'WAF tripped on a legit request. Which rule id should I relax — `100201`, `100215`, or `100340`?',
    'ann_a': ['Q o :: Which rule id looks wrong—e.g., `100201`, `100215`, or `100340`?'],
    'ann_b': ['Q m :: Which rule id should I relax — `100201`, `100215`, or `100340`?', 'O `100201`', 'O `100215`', 'O `100340`'],
  },
  {
    'n': 679,
    'boundary': 'examples/options',
    'note_a': 'such as Prisma relations -> open',
    'note_b': 'same relations as multi_choice',
    'text_a': 'Schema review is vague. Which relation is the pain—such as `User`↔`Org`, `Order`↔`LineItem`, or `Post`↔`Tag`?',
    'text_b': 'Schema review is vague. Which relation should I remodel — `User`↔`Org`, `Order`↔`LineItem`, or `Post`↔`Tag`?',
    'ann_a': ['Q o :: Which relation is the pain—such as `User`↔`Org`, `Order`↔`LineItem`, or `Post`↔`Tag`?'],
    'ann_b': ['Q m :: Which relation should I remodel — `User`↔`Org`, `Order`↔`LineItem`, or `Post`↔`Tag`?', 'O `User`↔`Org`', 'O `Order`↔`LineItem`', 'O `Post`↔`Tag`'],
  },
  {
    'n': 680,
    'boundary': 'examples/options',
    'note_a': 'e.g. two TLS modes -> open',
    'note_b': 'same modes as either_or',
    'text_a': 'Postgres connection string needs TLS. What mode should clients use—e.g. `require` or `verify-full`?',
    'text_b': 'Postgres connection string needs TLS. Which mode should clients use — `require` or `verify-full`?',
    'ann_a': ['Q o :: What mode should clients use—e.g. `require` or `verify-full`?'],
    'ann_b': ['Q e :: Which mode should clients use — `require` or `verify-full`?', 'O `require`', 'O `verify-full`'],
  },
  {
    'n': 681,
    'boundary': 'examples/options',
    'note_a': 'e.g. changelog audiences -> open',
    'note_b': 'Shall I among same -> multi_choice propose',
    'text_a': 'Release notes draft is ready. Who is the audience—e.g. external users, internal eng, or support—or something else?',
    'text_b': 'Release notes draft is ready. Shall I tailor them for external users, internal eng, or support?',
    'ann_a': ['Q o :: Who is the audience—e.g. external users, internal eng, or support—or something else?'],
    'ann_b': ['Q m p :: Shall I tailor them for external users, internal eng, or support?', 'O external users', 'O internal eng', 'O support'],
  },
  {
    'n': 682,
    'boundary': 'examples/options',
    'note_a': 'e.g. list illustrates -> open',
    'note_b': 'same policies as multi_choice',
    'text_a': 'Redis memory pressure. Which eviction policy fits your intent—e.g., `allkeys-lru`, `volatile-ttl`, or `noeviction`?',
    'text_b': 'Memory pressure on the cache node. Which eviction policy should I set — `allkeys-lru`, `volatile-ttl`, or `noeviction`?',
    'ann_a': ['Q o :: Which eviction policy fits your intent—e.g., `allkeys-lru`, `volatile-ttl`, or `noeviction`?'],
    'ann_b': ['Q m :: Which eviction policy should I set — `allkeys-lru`, `volatile-ttl`, or `noeviction`?', 'O `allkeys-lru`', 'O `volatile-ttl`', 'O `noeviction`'],
  },
  {
    'n': 683,
    'boundary': 'examples/options',
    'note_a': 'such as ARIA roles -> open',
    'note_b': 'same roles as multi_choice',
    'text_a': 'Screen reader announces oddly. What role should the widget use—such as `dialog`, `menu`, or `listbox`?',
    'text_b': 'Screen reader announces oddly. Which role should the widget use — `dialog`, `menu`, or `listbox`?',
    'ann_a': ['Q o :: What role should the widget use—such as `dialog`, `menu`, or `listbox`?'],
    'ann_b': ['Q m :: Which role should the widget use — `dialog`, `menu`, or `listbox`?', 'O `dialog`', 'O `menu`', 'O `listbox`'],
  },
  {
    'n': 684,
    'boundary': 'examples/options',
    'note_a': 'e.g. two flake quarantine policies -> open',
    'note_b': 'same policies as either_or',
    'text_a': 'Flaky test keeps returning. What policy do you want—e.g. quarantine with a ticket or delete it?',
    'text_b': 'Flaky test keeps returning. Which policy do you want — quarantine with a ticket or delete it?',
    'ann_a': ['Q o :: What policy do you want—e.g. quarantine with a ticket or delete it?'],
    'ann_b': ['Q e :: Which policy do you want — quarantine with a ticket or delete it?', 'O quarantine with a ticket', 'O delete it'],
  },
  {
    'n': 685,
    'boundary': 'examples/options',
    'note_a': 'e.g. Spark shuffle configs -> open',
    'note_b': 'same configs as multi_choice',
    'text_a': 'Job OOMs on shuffle. Could you say which knob to try—e.g. `spark.sql.shuffle.partitions`, executor memory, or broadcast join threshold—or something else?',
    'text_b': 'Job OOMs on shuffle. Which knob should I raise first — `spark.sql.shuffle.partitions`, executor memory, or broadcast join threshold?',
    'ann_a': ['Q o :: Could you say which knob to try—e.g. `spark.sql.shuffle.partitions`, executor memory, or broadcast join threshold—or something else?'],
    'ann_b': ['Q m :: Which knob should I raise first — `spark.sql.shuffle.partitions`, executor memory, or broadcast join threshold?', 'O `spark.sql.shuffle.partitions`', 'O executor memory', 'O broadcast join threshold'],
  },
  {
    'n': 686,
    'boundary': 'examples/options',
    'note_a': 'e.g. list illustrates -> open',
    'note_b': 'Want me among same -> multi_choice propose',
    'text_a': 'Brew bundle incomplete. Which formula is missing—e.g., `postgresql@16`, `redis`, or `ffmpeg`?',
    'text_b': 'Dev bootstrap is incomplete. Want me to install `postgresql@16`, `redis`, or `ffmpeg`?',
    'ann_a': ['Q o :: Which formula is missing—e.g., `postgresql@16`, `redis`, or `ffmpeg`?'],
    'ann_b': ['Q m p :: Want me to install `postgresql@16`, `redis`, or `ffmpeg`?', 'O `postgresql@16`', 'O `redis`', 'O `ffmpeg`'],
  },
  {
    'n': 687,
    'boundary': 'examples/options',
    'note_a': 'such as HTTP methods -> open',
    'note_b': 'same methods as multi_choice',
    'text_a': 'Idempotency middleware only covers writes. Which method still needs coverage—such as `POST`, `PUT`, or `PATCH`?',
    'text_b': 'Idempotency middleware only covers writes. Which method should I add next — `POST`, `PUT`, or `PATCH`?',
    'ann_a': ['Q o :: Which method still needs coverage—such as `POST`, `PUT`, or `PATCH`?'],
    'ann_b': ['Q m :: Which method should I add next — `POST`, `PUT`, or `PATCH`?', 'O `POST`', 'O `PUT`', 'O `PATCH`'],
  },
  {
    'n': 688,
    'boundary': 'examples/options',
    'note_a': 'e.g. two map tile styles -> open',
    'note_b': 'same styles as either_or',
    'text_a': 'Map basemap is undecided. What style should the default be—e.g. light streets or dark satellite?',
    'text_b': 'Map basemap is undecided. Which style should the default be — light streets or dark satellite?',
    'ann_a': ['Q o :: What style should the default be—e.g. light streets or dark satellite?'],
    'ann_b': ['Q e :: Which style should the default be — light streets or dark satellite?', 'O light streets', 'O dark satellite'],
  },
  {
    'n': 689,
    'boundary': 'examples/options',
    'note_a': 'e.g. with long status then open',
    'note_b': 'same rollback targets as multi_choice',
    'text_a': 'Deploy of `api@1.8.2` is live; canaries look fine on p50, but error rate ticked up in `eu-west-1`. What should we roll back—e.g. the whole region, just the canary pods, or the feature flag—or something else?',
    'text_b': 'Deploy of `api@1.8.2` is live; canaries look fine on p50, but error rate ticked up in `eu-west-1`. Which should we roll back — the whole region, just the canary pods, or the feature flag?',
    'ann_a': ['Q o :: What should we roll back—e.g. the whole region, just the canary pods, or the feature flag—or something else?'],
    'ann_b': ['Q m :: Which should we roll back — the whole region, just the canary pods, or the feature flag?', 'O the whole region', 'O just the canary pods', 'O the feature flag'],
  },
  {
    'n': 690,
    'boundary': 'examples/options',
    'note_a': 'e.g. list illustrates -> open',
    'note_b': 'same modes as multi_choice',
    'text_a': 'Vite env confusion. Which mode were you building—e.g., `development`, `staging`, or `production`?',
    'text_b': 'Env loading is confusing. Which mode should the script assume — `development`, `staging`, or `production`?',
    'ann_a': ['Q o :: Which mode were you building—e.g., `development`, `staging`, or `production`?'],
    'ann_b': ['Q m :: Which mode should the script assume — `development`, `staging`, or `production`?', 'O `development`', 'O `staging`', 'O `production`'],
  },
  {
    'n': 691,
    'boundary': 'examples/options',
    'note_a': 'such as Lucene analyzers -> open',
    'note_b': 'Shall I among same -> multi_choice propose',
    'text_a': 'Search relevance is off for compound words. What analyzer should the field use—such as `standard`, `german`, or a custom ngram?',
    'text_b': 'Search relevance is off for compound words. Shall I switch the field to `standard`, `german`, or a custom ngram analyzer?',
    'ann_a': ['Q o :: What analyzer should the field use—such as `standard`, `german`, or a custom ngram?'],
    'ann_b': ['Q m p :: Shall I switch the field to `standard`, `german`, or a custom ngram analyzer?', 'O `standard`', 'O `german`', 'O a custom ngram'],
  },
  {
    'n': 692,
    'boundary': 'examples/options',
    'note_a': 'e.g. two SEO title strategies -> open',
    'note_b': 'same strategies as either_or',
    'text_a': 'Product pages need titles. What pattern did you want—e.g. `{name} | Shop` or `{name} – {category}`?',
    'text_b': 'Product pages need titles. Which pattern do you want — `{name} | Shop` or `{name} – {category}`?',
    'ann_a': ['Q o :: What pattern did you want—e.g. `{name} | Shop` or `{name} – {category}`?'],
    'ann_b': ['Q e :: Which pattern do you want — `{name} | Shop` or `{name} – {category}`?', 'O `{name} | Shop`', 'O `{name} – {category}`'],
  },
  {
    'n': 693,
    'boundary': 'examples/options',
    'note_a': 'e.g. Fly.io regions -> open',
    'note_b': 'same regions as multi_choice',
    'text_a': 'Latency is high for APAC users. Could you say which region to add—e.g. `sin`, `nrt`, or `syd`—or something else?',
    'text_b': 'Latency is high for APAC users. Which region should I add — `sin`, `nrt`, or `syd`?',
    'ann_a': ['Q o :: Could you say which region to add—e.g. `sin`, `nrt`, or `syd`—or something else?'],
    'ann_b': ['Q m :: Which region should I add — `sin`, `nrt`, or `syd`?', 'O `sin`', 'O `nrt`', 'O `syd`'],
  },
  {
    'n': 694,
    'boundary': 'examples/options',
    'note_a': 'e.g. list illustrates -> open',
    'note_b': 'Want me among same -> multi_choice propose',
    'text_a': 'Cypress flake. Which mitigation are you thinking about—e.g., run retries, longer timeouts, or stubbing the clock?',
    'text_b': 'E2E flake rate is up. Want me to enable run retries, longer timeouts, or stubbing the clock?',
    'ann_a': ['Q o :: Which mitigation are you thinking about—e.g., run retries, longer timeouts, or stubbing the clock?'],
    'ann_b': ['Q m p :: Want me to enable run retries, longer timeouts, or stubbing the clock?', 'O run retries', 'O longer timeouts', 'O stubbing the clock'],
  },
  {
    'n': 695,
    'boundary': 'examples/options',
    'note_a': 'such as WASM targets -> open',
    'note_b': 'same targets as multi_choice',
    'text_a': 'Rust build matrix is large. Which WASM target matters—such as `wasm32-unknown-unknown`, `wasm32-wasi`, or `wasm32-unknown-emscripten`?',
    'text_b': 'Rust build matrix is large. Which WASM target should CI keep — `wasm32-unknown-unknown`, `wasm32-wasi`, or `wasm32-unknown-emscripten`?',
    'ann_a': ['Q o :: Which WASM target matters—such as `wasm32-unknown-unknown`, `wasm32-wasi`, or `wasm32-unknown-emscripten`?'],
    'ann_b': ['Q m :: Which WASM target should CI keep — `wasm32-unknown-unknown`, `wasm32-wasi`, or `wasm32-unknown-emscripten`?', 'O `wasm32-unknown-unknown`', 'O `wasm32-wasi`', 'O `wasm32-unknown-emscripten`'],
  },
  {
    'n': 696,
    'boundary': 'examples/options',
    'note_a': 'e.g. two rate-limit scopes -> open',
    'note_b': 'same scopes as either_or',
    'text_a': 'Throttling is too coarse. What scope should the limiter use—e.g. per API key or per IP?',
    'text_b': 'Throttling is too coarse. Which scope should the limiter use — per API key or per IP?',
    'ann_a': ['Q o :: What scope should the limiter use—e.g. per API key or per IP?'],
    'ann_b': ['Q e :: Which scope should the limiter use — per API key or per IP?', 'O per API key', 'O per IP'],
  },
  {
    'n': 697,
    'boundary': 'examples/options',
    'note_a': 'e.g. markdown lint rules -> open',
    'note_b': 'same rules as multi_choice',
    'text_a': 'Docs lint is noisy. Could you say which rule to keep—e.g. MD013 line length, MD024 duplicate headings, or MD041 first-line heading—or something else?',
    'text_b': 'Docs lint is noisy. Which rule should stay enabled — MD013 line length, MD024 duplicate headings, or MD041 first-line heading?',
    'ann_a': ['Q o :: Could you say which rule to keep—e.g. MD013 line length, MD024 duplicate headings, or MD041 first-line heading—or something else?'],
    'ann_b': ['Q m :: Which rule should stay enabled — MD013 line length, MD024 duplicate headings, or MD041 first-line heading?', 'O MD013 line length', 'O MD024 duplicate headings', 'O MD041 first-line heading'],
  },
  {
    'n': 698,
    'boundary': 'examples/options',
    'note_a': 'e.g. list illustrates -> open',
    'note_b': 'same timeouts as multi_choice',
    'text_a': 'SQS visibility. Which timeout feels right in your mind—e.g., 30s, 2m, or 5m?',
    'text_b': 'Messages are becoming visible too soon. Which visibility timeout should I set — 30s, 2m, or 5m?',
    'ann_a': ['Q o :: Which timeout feels right in your mind—e.g., 30s, 2m, or 5m?'],
    'ann_b': ['Q m :: Which visibility timeout should I set — 30s, 2m, or 5m?', 'O 30s', 'O 2m', 'O 5m'],
  },
  {
    'n': 699,
    'boundary': 'examples/options',
    'note_a': 'such as biome format scopes -> open',
    'note_b': 'Shall I among same -> multi_choice propose',
    'text_a': 'Format check fails on generated files. What should we exclude—such as `dist/`, `coverage/`, or `*.gen.ts`?',
    'text_b': 'Format check fails on generated files. Shall I exclude `dist/`, `coverage/`, or `*.gen.ts` from Biome?',
    'ann_a': ['Q o :: What should we exclude—such as `dist/`, `coverage/`, or `*.gen.ts`?'],
    'ann_b': ['Q m p :: Shall I exclude `dist/`, `coverage/`, or `*.gen.ts` from Biome?', 'O `dist/`', 'O `coverage/`', 'O `*.gen.ts`'],
  },
  {
    'n': 700,
    'boundary': 'examples/options',
    'note_a': 'e.g. two commit message styles -> open',
    'note_b': 'same styles as either_or',
    'text_a': 'History is messy before the squash. What message style do you want—e.g. conventional commits or a short prose summary?',
    'text_b': 'History is messy before the squash. Which message style do you want — conventional commits or a short prose summary?',
    'ann_a': ['Q o :: What message style do you want—e.g. conventional commits or a short prose summary?'],
    'ann_b': ['Q e :: Which message style do you want — conventional commits or a short prose summary?', 'O conventional commits', 'O a short prose summary'],
  },
]
