# Contrastive pairs pa0001–pa0100: yes_no vs either_or
# boundary: yes_no/either_or
# a = either_or (two deliverables); b = yes_no (one change, several attributes)

PAIRS = [
    {
        "n": 1,
        "boundary": "yes_no/either_or",
        "note_a": "diff vs walkthrough = two deliverables -> either_or",
        "note_b": "color or label = attributes of one indicator tweak -> yes_no",
        "text_a": "Refactor of `Badge` is in. The `!` urgency marker now renders next to the title.\n\nWant a diff or a walkthrough of any section?",
        "text_b": "Refactor of `Badge` is in. The `!` urgency marker now renders next to the title.\n\nWant the `!` indicator to use a different color or label?",
        "ann_a": [
            "Q e p :: Want a diff or a walkthrough of any section?",
            "O a diff",
            "O a walkthrough of any section",
        ],
        "ann_b": [
            "Q y p :: Want the `!` indicator to use a different color or label?",
        ],
    },
    {
        "n": 2,
        "boundary": "yes_no/either_or",
        "note_a": "PR vs push = two git deliverables -> either_or",
        "note_b": "title or base = attributes of one PR action -> yes_no",
        "text_a": "Branch `fix/auth-timeout` is clean and ahead of `main` by 3 commits. Tests pass locally.\n\nWant me to open a PR or just push the branch?",
        "text_b": "Branch `fix/auth-timeout` is clean and ahead of `main` by 3 commits. Tests pass locally.\n\nWant me to use a different PR title or base branch?",
        "ann_a": [
            "Q e p :: Want me to open a PR or just push the branch?",
            "O open a PR",
            "O just push the branch",
        ],
        "ann_b": [
            "Q y p :: Want me to use a different PR title or base branch?",
        ],
    },
    {
        "n": 3,
        "boundary": "yes_no/either_or",
        "note_a": "revert vs bisect = two actions -> either_or",
        "note_b": "range or depth = attributes of one bisect -> yes_no",
        "text_a": "`main` went red after the merge. Last good SHA looks like `a1b2c3d`.\n\nShall I revert the merge or start a bisect?",
        "text_b": "`main` went red after the merge. Last good SHA looks like `a1b2c3d`.\n\nShall I start a bisect with a different range or depth?",
        "ann_a": [
            "Q e p :: Shall I revert the merge or start a bisect?",
            "O revert the merge",
            "O start a bisect",
        ],
        "ann_b": [
            "Q y p :: Shall I start a bisect with a different range or depth?",
        ],
    },
    {
        "n": 4,
        "boundary": "yes_no/either_or",
        "note_a": "commit message vs changelog = two docs -> either_or",
        "note_b": "filename or speed = attributes of one export tweak -> yes_no",
        "text_a": "Staged everything for the release cut. Diff is ~180 lines across `cli/` and `docs/`.\n\nWant a commit message draft or a changelog entry?",
        "text_b": "Staged everything for the release cut. Diff is ~180 lines across `cli/` and `docs/`.\n\nWant a different filename or speed?",
        "ann_a": [
            "Q e p :: Want a commit message draft or a changelog entry?",
            "O a commit message draft",
            "O a changelog entry",
        ],
        "ann_b": [
            "Q y p :: Want a different filename or speed?",
        ],
    },
    {
        "n": 5,
        "boundary": "yes_no/either_or",
        "note_a": "squash vs keep commits = two history shapes -> either_or",
        "note_b": "author or date = attributes of one rewrite -> yes_no",
        "text_a": "Ready to land `feature/cache-headers`. Five WIP commits on the branch.\n\nWant me to squash into one commit or keep the history?",
        "text_b": "Ready to land `feature/cache-headers`. Five WIP commits on the branch.\n\nWant me to rewrite with a different author or date?",
        "ann_a": [
            "Q e p :: Want me to squash into one commit or keep the history?",
            "O squash into one commit",
            "O keep the history",
        ],
        "ann_b": [
            "Q y p :: Want me to rewrite with a different author or date?",
        ],
    },
    {
        "n": 6,
        "boundary": "yes_no/either_or",
        "note_a": "patch file vs inline summary = two deliverables -> either_or",
        "note_b": "encoding or line endings = attributes of one patch tweak -> yes_no",
        "text_a": "Fixed the off-by-one in `paginate()`.\n\n[CODE]\n- return items[start:end]\n+ return items[start:end + 1]\n[/CODE]\n\nWant a patch file or an inline summary?",
        "text_b": "Fixed the off-by-one in `paginate()`.\n\n[CODE]\n- return items[start:end]\n+ return items[start:end + 1]\n[/CODE]\n\nWant the patch with a different encoding or line endings?",
        "ann_a": [
            "Q e p :: Want a patch file or an inline summary?",
            "O a patch file",
            "O an inline summary",
        ],
        "ann_b": [
            "Q y p :: Want the patch with a different encoding or line endings?",
        ],
    },
    {
        "n": 7,
        "boundary": "yes_no/either_or",
        "note_a": "force-with-lease vs new branch = two push strategies -> either_or",
        "note_b": "remote or refspec = attributes of one push -> yes_no",
        "text_a": "Rebased onto `origin/main`. Local and remote histories diverged.\n\nShall I push with `--force-with-lease` or open a fresh branch?",
        "text_b": "Rebased onto `origin/main`. Local and remote histories diverged.\n\nShall I push with a different remote or refspec?",
        "ann_a": [
            "Q e p :: Shall I push with `--force-with-lease` or open a fresh branch?",
            "O push with `--force-with-lease`",
            "O open a fresh branch",
        ],
        "ann_b": [
            "Q y p :: Shall I push with a different remote or refspec?",
        ],
    },
    {
        "n": 8,
        "boundary": "yes_no/either_or",
        "note_a": "tag vs release notes = two release artifacts -> either_or",
        "note_b": "prefix or message = attributes of one tag -> yes_no",
        "text_a": "Version bump to `1.4.0` is ready in `package.json` and `Cargo.toml`.\n\nWant me to cut the git tag or draft the GitHub release notes?",
        "text_b": "Version bump to `1.4.0` is ready in `package.json` and `Cargo.toml`.\n\nWant me to cut the tag with a different prefix or message?",
        "ann_a": [
            "Q e p :: Want me to cut the git tag or draft the GitHub release notes?",
            "O cut the git tag",
            "O draft the GitHub release notes",
        ],
        "ann_b": [
            "Q y p :: Want me to cut the tag with a different prefix or message?",
        ],
    },
    {
        "n": 9,
        "boundary": "yes_no/either_or",
        "note_a": "stash vs WIP commit = two ways to park work -> either_or",
        "note_b": "name or include-untracked = attributes of one stash -> yes_no",
        "text_a": "You have dirty changes in `src/parser.rs` and untracked fixtures.\n\nWant me to stash them or make a WIP commit?",
        "text_b": "You have dirty changes in `src/parser.rs` and untracked fixtures.\n\nWant me to stash with a different name or include-untracked flag?",
        "ann_a": [
            "Q e p :: Want me to stash them or make a WIP commit?",
            "O stash them",
            "O make a WIP commit",
        ],
        "ann_b": [
            "Q y p :: Want me to stash with a different name or include-untracked flag?",
        ],
    },
    {
        "n": 10,
        "boundary": "yes_no/either_or",
        "note_a": "cherry-pick vs cherry-pick script = two deliverables -> either_or",
        "note_b": "order or conflict strategy = attributes of one cherry-pick -> yes_no",
        "text_a": "Three hotfixes on `release/2.1` need to land on `main`:\n- `f00d1` rate-limit\n- `beef2` null-guard\n- `cafe3` log redaction\n\nWant me to cherry-pick them now or write a cherry-pick script?",
        "text_b": "Three hotfixes on `release/2.1` need to land on `main`:\n- `f00d1` rate-limit\n- `beef2` null-guard\n- `cafe3` log redaction\n\nWant me to cherry-pick with a different order or conflict strategy?",
        "ann_a": [
            "Q e p :: Want me to cherry-pick them now or write a cherry-pick script?",
            "O cherry-pick them now",
            "O write a cherry-pick script",
        ],
        "ann_b": [
            "Q y p :: Want me to cherry-pick with a different order or conflict strategy?",
        ],
    },
    {
        "n": 11,
        "boundary": "yes_no/either_or",
        "note_a": "rerun job vs widen matrix = two CI actions -> either_or",
        "note_b": "OS or Node version = attributes of one matrix tweak -> yes_no",
        "text_a": "CI failed on `lint` only; `test` and `build` were green.\n\n[URL]\n\nWant me to rerun the failed job or widen the matrix?",
        "text_b": "CI failed on `lint` only; `test` and `build` were green.\n\n[URL]\n\nWant me to widen the matrix with a different OS or Node version?",
        "ann_a": [
            "Q e p :: Want me to rerun the failed job or widen the matrix?",
            "O rerun the failed job",
            "O widen the matrix",
        ],
        "ann_b": [
            "Q y p :: Want me to widen the matrix with a different OS or Node version?",
        ],
    },
    {
        "n": 12,
        "boundary": "yes_no/either_or",
        "note_a": "flake quarantine vs root-cause fix = two paths -> either_or",
        "note_b": "timeout or retry count = attributes of one flake tweak -> yes_no",
        "text_a": "`test_upload_retries` failed 2/20 in CI, passed locally. Looks timing-sensitive around the mock server boot.\n\nShall I quarantine the flake or dig for a root-cause fix?",
        "text_b": "`test_upload_retries` failed 2/20 in CI, passed locally. Looks timing-sensitive around the mock server boot.\n\nShall I tweak the flake with a different timeout or retry count?",
        "ann_a": [
            "Q e p :: Shall I quarantine the flake or dig for a root-cause fix?",
            "O quarantine the flake",
            "O dig for a root-cause fix",
        ],
        "ann_b": [
            "Q y p :: Shall I tweak the flake with a different timeout or retry count?",
        ],
    },
    {
        "n": 13,
        "boundary": "yes_no/either_or",
        "note_a": "coverage report vs failing test list = two artifacts -> either_or",
        "note_b": "threshold or include glob = attributes of one coverage change -> yes_no",
        "text_a": "Ran the suite: 412 passed, 3 failed, coverage 78.4%.\n\nWant a coverage report or a failing-test triage list?",
        "text_b": "Ran the suite: 412 passed, 3 failed, coverage 78.4%.\n\nWant coverage with a different threshold or include glob?",
        "ann_a": [
            "Q e p :: Want a coverage report or a failing-test triage list?",
            "O a coverage report",
            "O a failing-test triage list",
        ],
        "ann_b": [
            "Q y p :: Want coverage with a different threshold or include glob?",
        ],
    },
    {
        "n": 14,
        "boundary": "yes_no/either_or",
        "note_a": "snapshot update vs assert rewrite = two test fixes -> either_or",
        "note_b": "serializer or path = attributes of one snapshot update -> yes_no",
        "text_a": "Snapshot mismatch in `Button.test.tsx` after the padding change.\n\nWant me to update the snapshot or rewrite the assertion?",
        "text_b": "Snapshot mismatch in `Button.test.tsx` after the padding change.\n\nWant me to update the snapshot with a different serializer or path?",
        "ann_a": [
            "Q e p :: Want me to update the snapshot or rewrite the assertion?",
            "O update the snapshot",
            "O rewrite the assertion",
        ],
        "ann_b": [
            "Q y p :: Want me to update the snapshot with a different serializer or path?",
        ],
    },
    {
        "n": 15,
        "boundary": "yes_no/either_or",
        "note_a": "unit fixtures vs e2e scenario = two test deliverables -> either_or",
        "note_b": "seed or locale = attributes of one fixture tweak -> yes_no",
        "text_a": "Auth flow is wired. Still missing regression coverage for the locked-out path.\n\nWant unit fixtures or an e2e scenario?",
        "text_b": "Auth flow is wired. Still missing regression coverage for the locked-out path.\n\nWant fixtures with a different seed or locale?",
        "ann_a": [
            "Q e p :: Want unit fixtures or an e2e scenario?",
            "O unit fixtures",
            "O an e2e scenario",
        ],
        "ann_b": [
            "Q y p :: Want fixtures with a different seed or locale?",
        ],
    },
    {
        "n": 16,
        "boundary": "yes_no/either_or",
        "note_a": "skip flaky job vs pin action version = two CI mitigations -> either_or",
        "note_b": "cache key or runner label = attributes of one workflow tweak -> yes_no",
        "text_a": "Workflow `publish.yml` keeps flaking on the npm cache restore step.\n\nWant me to skip that job for now or pin the action version?",
        "text_b": "Workflow `publish.yml` keeps flaking on the npm cache restore step.\n\nWant me to tweak the workflow with a different cache key or runner label?",
        "ann_a": [
            "Q e p :: Want me to skip that job for now or pin the action version?",
            "O skip that job for now",
            "O pin the action version",
        ],
        "ann_b": [
            "Q y p :: Want me to tweak the workflow with a different cache key or runner label?",
        ],
    },
    {
        "n": 17,
        "boundary": "yes_no/either_or",
        "note_a": "junit XML vs markdown summary = two CI outputs -> either_or",
        "note_b": "artifact name or retention = attributes of one upload -> yes_no",
        "text_a": "Added a `test-report` step. Output is currently dumped to stdout only.\n\nShall I emit junit XML or a markdown job summary?",
        "text_b": "Added a `test-report` step. Output is currently dumped to stdout only.\n\nShall I upload the report with a different artifact name or retention?",
        "ann_a": [
            "Q e p :: Shall I emit junit XML or a markdown job summary?",
            "O junit XML",
            "O a markdown job summary",
        ],
        "ann_b": [
            "Q y p :: Shall I upload the report with a different artifact name or retention?",
        ],
    },
    {
        "n": 18,
        "boundary": "yes_no/either_or",
        "note_a": "parallelize suite vs shard by package = two speedups -> either_or",
        "note_b": "worker count or shard count = attributes of one parallel setup -> yes_no",
        "text_a": "Full suite is ~14m on CI. Bottleneck is serial integration tests.\n\nWant me to parallelize the suite or shard by package?",
        "text_b": "Full suite is ~14m on CI. Bottleneck is serial integration tests.\n\nWant me to parallelize with a different worker count or shard count?",
        "ann_a": [
            "Q e p :: Want me to parallelize the suite or shard by package?",
            "O parallelize the suite",
            "O shard by package",
        ],
        "ann_b": [
            "Q y p :: Want me to parallelize with a different worker count or shard count?",
        ],
    },
    {
        "n": 19,
        "boundary": "yes_no/either_or",
        "note_a": "mock server vs recorded cassette = two test approaches -> either_or",
        "note_b": "port or fixture path = attributes of one mock setup -> yes_no",
        "text_a": "The payment client tests hit the live sandbox and need network.\n\nWant a local mock server or recorded cassettes?",
        "text_b": "The payment client tests hit the live sandbox and need network.\n\nWant the mock with a different port or fixture path?",
        "ann_a": [
            "Q e p :: Want a local mock server or recorded cassettes?",
            "O a local mock server",
            "O recorded cassettes",
        ],
        "ann_b": [
            "Q y p :: Want the mock with a different port or fixture path?",
        ],
    },
    {
        "n": 20,
        "boundary": "yes_no/either_or",
        "note_a": "fail-fast off vs continue-on-error = two CI behaviors -> either_or",
        "note_b": "timeout-minutes or concurrency group = attributes of one job tweak -> yes_no",
        "text_a": "Matrix aborts after the first OS failure, so we lose signal from the others.\n\nWant fail-fast off or `continue-on-error` on that job?",
        "text_b": "Matrix aborts after the first OS failure, so we lose signal from the others.\n\nWant that job with a different `timeout-minutes` or concurrency group?",
        "ann_a": [
            "Q e p :: Want fail-fast off or `continue-on-error` on that job?",
            "O fail-fast off",
            "O `continue-on-error` on that job",
        ],
        "ann_b": [
            "Q y p :: Want that job with a different `timeout-minutes` or concurrency group?",
        ],
    },
    {
        "n": 21,
        "boundary": "yes_no/either_or",
        "note_a": "extract helper vs inline fix = two refactor shapes -> either_or",
        "note_b": "name or module = attributes of one extract -> yes_no",
        "text_a": "Duplicated date parsing in `Invoice` and `Receipt`. Same three-line regex.\n\nWant me to extract a shared helper or just inline the fix in both?",
        "text_b": "Duplicated date parsing in `Invoice` and `Receipt`. Same three-line regex.\n\nWant me to extract the helper with a different name or module?",
        "ann_a": [
            "Q e p :: Want me to extract a shared helper or just inline the fix in both?",
            "O extract a shared helper",
            "O just inline the fix in both",
        ],
        "ann_b": [
            "Q y p :: Want me to extract the helper with a different name or module?",
        ],
    },
    {
        "n": 22,
        "boundary": "yes_no/either_or",
        "note_a": "rename symbol vs move file = two refactors -> either_or",
        "note_b": "visibility or package = attributes of one move -> yes_no",
        "text_a": "`LegacyClient` is only used from `billing/`. Name is misleading.\n\nShall I rename the symbol or move the file under `billing/`?",
        "text_b": "`LegacyClient` is only used from `billing/`. Name is misleading.\n\nShall I move it with a different visibility or package path?",
        "ann_a": [
            "Q e p :: Shall I rename the symbol or move the file under `billing/`?",
            "O rename the symbol",
            "O move the file under `billing/`",
        ],
        "ann_b": [
            "Q y p :: Shall I move it with a different visibility or package path?",
        ],
    },
    {
        "n": 23,
        "boundary": "yes_no/either_or",
        "note_a": "typed dict vs dataclass = two type designs -> either_or",
        "note_b": "frozen or slots = attributes of one dataclass choice -> yes_no",
        "text_a": "Config loading still returns a bare `dict`. Call sites keep guessing keys.\n\nWant a `TypedDict` or a `@dataclass`?",
        "text_b": "Config loading still returns a bare `dict`. Call sites keep guessing keys.\n\nWant the dataclass with a different `frozen` or `slots` setting?",
        "ann_a": [
            "Q e p :: Want a `TypedDict` or a `@dataclass`?",
            "O a `TypedDict`",
            "O a `@dataclass`",
        ],
        "ann_b": [
            "Q y p :: Want the dataclass with a different `frozen` or `slots` setting?",
        ],
    },
    {
        "n": 24,
        "boundary": "yes_no/either_or",
        "note_a": "strangler facade vs big-bang delete = two migration tactics -> either_or",
        "note_b": "deprecation window or alias name = attributes of one strangler -> yes_no",
        "text_a": "`old_api/` still has 40 call sites. New module is ready under `api/v2/`.\n\nWant a strangler facade or a big-bang delete?",
        "text_b": "`old_api/` still has 40 call sites. New module is ready under `api/v2/`.\n\nWant the strangler with a different deprecation window or alias name?",
        "ann_a": [
            "Q e p :: Want a strangler facade or a big-bang delete?",
            "O a strangler facade",
            "O a big-bang delete",
        ],
        "ann_b": [
            "Q y p :: Want the strangler with a different deprecation window or alias name?",
        ],
    },
    {
        "n": 25,
        "boundary": "yes_no/either_or",
        "note_a": "dependency injection vs service locator = two designs -> either_or",
        "note_b": "lifetime or scope = attributes of one DI registration -> yes_no",
        "text_a": "`Notifier` constructs its own SMTP client. Hard to test.\n\nWant constructor injection or a service-locator hook?",
        "text_b": "`Notifier` constructs its own SMTP client. Hard to test.\n\nWant the DI registration with a different lifetime or scope?",
        "ann_a": [
            "Q e p :: Want constructor injection or a service-locator hook?",
            "O constructor injection",
            "O a service-locator hook",
        ],
        "ann_b": [
            "Q y p :: Want the DI registration with a different lifetime or scope?",
        ],
    },
    {
        "n": 26,
        "boundary": "yes_no/either_or",
        "note_a": "split module vs keep monolith file = two layouts -> either_or",
        "note_b": "directory or barrel export = attributes of one split -> yes_no",
        "text_a": "`utils.ts` is 1.2k lines across formatting, dates, and HTTP helpers.\n\nWant me to split the module or leave the monolith and just document sections?",
        "text_b": "`utils.ts` is 1.2k lines across formatting, dates, and HTTP helpers.\n\nWant me to split with a different directory layout or barrel export?",
        "ann_a": [
            "Q e p :: Want me to split the module or leave the monolith and just document sections?",
            "O split the module",
            "O leave the monolith and just document sections",
        ],
        "ann_b": [
            "Q y p :: Want me to split with a different directory layout or barrel export?",
        ],
    },
    {
        "n": 27,
        "boundary": "yes_no/either_or",
        "note_a": "error union vs exception = two error styles -> either_or",
        "note_b": "error code or message template = attributes of one error type -> yes_no",
        "text_a": "`parseConfig` currently throws on missing keys. Callers can't recover cleanly.\n\nShall I switch to a Result/error-union or keep exceptions and document them?",
        "text_b": "`parseConfig` currently throws on missing keys. Callers can't recover cleanly.\n\nShall I keep exceptions with a different error code or message template?",
        "ann_a": [
            "Q e p :: Shall I switch to a Result/error-union or keep exceptions and document them?",
            "O switch to a Result/error-union",
            "O keep exceptions and document them",
        ],
        "ann_b": [
            "Q y p :: Shall I keep exceptions with a different error code or message template?",
        ],
    },
    {
        "n": 28,
        "boundary": "yes_no/either_or",
        "note_a": "codegen regen vs hand-edit stubs = two approaches -> either_or",
        "note_b": "template or output path = attributes of one codegen run -> yes_no",
        "text_a": "OpenAPI bumped; generated client is stale. Manual stubs diverge.\n\nWant me to regenerate from the spec or hand-edit the stubs?",
        "text_b": "OpenAPI bumped; generated client is stale. Manual stubs diverge.\n\nWant me to regenerate with a different template or output path?",
        "ann_a": [
            "Q e p :: Want me to regenerate from the spec or hand-edit the stubs?",
            "O regenerate from the spec",
            "O hand-edit the stubs",
        ],
        "ann_b": [
            "Q y p :: Want me to regenerate with a different template or output path?",
        ],
    },
    {
        "n": 29,
        "boundary": "yes_no/either_or",
        "note_a": "feature flag vs hard cutover = two rollout tactics -> either_or",
        "note_b": "default or rollout percentage = attributes of one flag -> yes_no",
        "text_a": "New ranking model is ready behind `use_v2_ranker`.\n\nWant a gradual feature flag or a hard cutover?",
        "text_b": "New ranking model is ready behind `use_v2_ranker`.\n\nWant the flag with a different default or rollout percentage?",
        "ann_a": [
            "Q e p :: Want a gradual feature flag or a hard cutover?",
            "O a gradual feature flag",
            "O a hard cutover",
        ],
        "ann_b": [
            "Q y p :: Want the flag with a different default or rollout percentage?",
        ],
    },
    {
        "n": 30,
        "boundary": "yes_no/either_or",
        "note_a": "dead-code delete vs comment-out = two cleanups -> either_or",
        "note_b": "scope or allowlist = attributes of one delete pass -> yes_no",
        "text_a": "Found 12 unused exports flagged by knip in `lib/`.\n\nWant me to delete the dead code or comment it out with a TODO?",
        "text_b": "Found 12 unused exports flagged by knip in `lib/`.\n\nWant me to delete with a different scope or allowlist?",
        "ann_a": [
            "Q e p :: Want me to delete the dead code or comment it out with a TODO?",
            "O delete the dead code",
            "O comment it out with a TODO",
        ],
        "ann_b": [
            "Q y p :: Want me to delete with a different scope or allowlist?",
        ],
    },
    {
        "n": 31,
        "boundary": "yes_no/either_or",
        "note_a": "CSS tweak vs component rewrite = two UI paths -> either_or",
        "note_b": "spacing or font size = attributes of one style tweak -> yes_no",
        "text_a": "Modal footer buttons overflow on 320px widths.\n\nWant a quick CSS tweak or a small component rewrite?",
        "text_b": "Modal footer buttons overflow on 320px widths.\n\nWant a CSS tweak with different spacing or font size?",
        "ann_a": [
            "Q e p :: Want a quick CSS tweak or a small component rewrite?",
            "O a quick CSS tweak",
            "O a small component rewrite",
        ],
        "ann_b": [
            "Q y p :: Want a CSS tweak with different spacing or font size?",
        ],
    },
    {
        "n": 32,
        "boundary": "yes_no/either_or",
        "note_a": "dark theme tokens vs screenshot = two deliverables -> either_or",
        "note_b": "contrast or hue = attributes of one token tweak -> yes_no",
        "text_a": "Light theme looks fine; dark theme still uses the old gray ramp.\n\nWant updated dark-theme tokens or a before/after screenshot set?",
        "text_b": "Light theme looks fine; dark theme still uses the old gray ramp.\n\nWant the tokens with a different contrast or hue?",
        "ann_a": [
            "Q e p :: Want updated dark-theme tokens or a before/after screenshot set?",
            "O updated dark-theme tokens",
            "O a before/after screenshot set",
        ],
        "ann_b": [
            "Q y p :: Want the tokens with a different contrast or hue?",
        ],
    },
    {
        "n": 33,
        "boundary": "yes_no/either_or",
        "note_a": "skeleton loader vs spinner = two loading UIs -> either_or",
        "note_b": "duration or shape = attributes of one skeleton -> yes_no",
        "text_a": "List page flashes empty while data loads.\n\nWant skeleton loaders or a centered spinner?",
        "text_b": "List page flashes empty while data loads.\n\nWant skeletons with a different duration or shape?",
        "ann_a": [
            "Q e p :: Want skeleton loaders or a centered spinner?",
            "O skeleton loaders",
            "O a centered spinner",
        ],
        "ann_b": [
            "Q y p :: Want skeletons with a different duration or shape?",
        ],
    },
    {
        "n": 34,
        "boundary": "yes_no/either_or",
        "note_a": "toast vs inline banner = two feedback patterns -> either_or",
        "note_b": "duration or placement = attributes of one toast -> yes_no",
        "text_a": "Save succeeded silently — easy to miss.\n\nShall I add a toast or an inline success banner?",
        "text_b": "Save succeeded silently — easy to miss.\n\nShall I add a toast with a different duration or placement?",
        "ann_a": [
            "Q e p :: Shall I add a toast or an inline success banner?",
            "O a toast",
            "O an inline success banner",
        ],
        "ann_b": [
            "Q y p :: Shall I add a toast with a different duration or placement?",
        ],
    },
    {
        "n": 35,
        "boundary": "yes_no/either_or",
        "note_a": "icon-only vs labeled button = two control designs -> either_or",
        "note_b": "size or aria-label = attributes of one icon button -> yes_no",
        "text_a": "Toolbar is crowded on tablet. The export control is the worst offender.\n\nWant an icon-only control or a labeled button that wraps?",
        "text_b": "Toolbar is crowded on tablet. The export control is the worst offender.\n\nWant the icon button with a different size or aria-label?",
        "ann_a": [
            "Q e p :: Want an icon-only control or a labeled button that wraps?",
            "O an icon-only control",
            "O a labeled button that wraps",
        ],
        "ann_b": [
            "Q y p :: Want the icon button with a different size or aria-label?",
        ],
    },
    {
        "n": 36,
        "boundary": "yes_no/either_or",
        "note_a": "focus trap vs autofocus = two a11y fixes -> either_or",
        "note_b": "tab order or initial target = attributes of one focus fix -> yes_no",
        "text_a": "Dialog opens but keyboard focus stays on the page behind it.\n\nWant a focus trap or just autofocus on the primary button?",
        "text_b": "Dialog opens but keyboard focus stays on the page behind it.\n\nWant focus handling with a different tab order or initial target?",
        "ann_a": [
            "Q e p :: Want a focus trap or just autofocus on the primary button?",
            "O a focus trap",
            "O just autofocus on the primary button",
        ],
        "ann_b": [
            "Q y p :: Want focus handling with a different tab order or initial target?",
        ],
    },
    {
        "n": 37,
        "boundary": "yes_no/either_or",
        "note_a": "chart lib swap vs custom SVG = two viz paths -> either_or",
        "note_b": "palette or animation = attributes of one chart tweak -> yes_no",
        "text_a": "Dashboard sparkline is a brittle canvas hack.\n\nWant me to swap in a chart library or draw a custom SVG?",
        "text_b": "Dashboard sparkline is a brittle canvas hack.\n\nWant the chart with a different palette or animation?",
        "ann_a": [
            "Q e p :: Want me to swap in a chart library or draw a custom SVG?",
            "O swap in a chart library",
            "O draw a custom SVG",
        ],
        "ann_b": [
            "Q y p :: Want the chart with a different palette or animation?",
        ],
    },
    {
        "n": 38,
        "boundary": "yes_no/either_or",
        "note_a": "empty state illustration vs copy-only = two empty UIs -> either_or",
        "note_b": "headline or CTA text = attributes of one empty-state copy tweak -> yes_no",
        "text_a": "Empty inbox currently shows a blank white panel.\n\nWant an illustration empty-state or copy-only guidance?",
        "text_b": "Empty inbox currently shows a blank white panel.\n\nWant empty-state copy with a different headline or CTA text?",
        "ann_a": [
            "Q e p :: Want an illustration empty-state or copy-only guidance?",
            "O an illustration empty-state",
            "O copy-only guidance",
        ],
        "ann_b": [
            "Q y p :: Want empty-state copy with a different headline or CTA text?",
        ],
    },
    {
        "n": 39,
        "boundary": "yes_no/either_or",
        "note_a": "responsive table vs card list = two layouts -> either_or",
        "note_b": "breakpoint or column set = attributes of one responsive tweak -> yes_no",
        "text_a": "Admin table horizontal-scrolls badly on phone.\n\nWant a responsive table collapse or a card list on small screens?",
        "text_b": "Admin table horizontal-scrolls badly on phone.\n\nWant the responsive table with a different breakpoint or column set?",
        "ann_a": [
            "Q e p :: Want a responsive table collapse or a card list on small screens?",
            "O a responsive table collapse",
            "O a card list on small screens",
        ],
        "ann_b": [
            "Q y p :: Want the responsive table with a different breakpoint or column set?",
        ],
    },
    {
        "n": 40,
        "boundary": "yes_no/either_or",
        "note_a": "storybook story vs visual regression = two UI artifacts -> either_or",
        "note_b": "viewport or theme = attributes of one story -> yes_no",
        "text_a": "`AlertBanner` variants aren't documented anywhere designers look.\n\nWant a Storybook story or a visual-regression baseline?",
        "text_b": "`AlertBanner` variants aren't documented anywhere designers look.\n\nWant the Storybook story with a different viewport or theme?",
        "ann_a": [
            "Q e p :: Want a Storybook story or a visual-regression baseline?",
            "O a Storybook story",
            "O a visual-regression baseline",
        ],
        "ann_b": [
            "Q y p :: Want the Storybook story with a different viewport or theme?",
        ],
    },
    {
        "n": 41,
        "boundary": "yes_no/either_or",
        "note_a": "migration SQL vs reverse script = two DB deliverables -> either_or",
        "note_b": "batch size or lock timeout = attributes of one migration -> yes_no",
        "text_a": "Need to add `users.last_login_at` without locking the table too long.\n\nWant the forward migration SQL or a paired reverse script?",
        "text_b": "Need to add `users.last_login_at` without locking the table too long.\n\nWant the migration with a different batch size or lock timeout?",
        "ann_a": [
            "Q e p :: Want the forward migration SQL or a paired reverse script?",
            "O the forward migration SQL",
            "O a paired reverse script",
        ],
        "ann_b": [
            "Q y p :: Want the migration with a different batch size or lock timeout?",
        ],
    },
    {
        "n": 42,
        "boundary": "yes_no/either_or",
        "note_a": "index vs query rewrite = two perf fixes -> either_or",
        "note_b": "index type or column order = attributes of one index -> yes_no",
        "text_a": "Slow query on `orders` by `(status, created_at)` — EXPLAIN shows seq scan.\n\n[CODE]\nEXPLAIN SELECT * FROM orders WHERE status = 'open' ORDER BY created_at;\n[/CODE]\n\nWant a new index or a query rewrite?",
        "text_b": "Slow query on `orders` by `(status, created_at)` — EXPLAIN shows seq scan.\n\n[CODE]\nEXPLAIN SELECT * FROM orders WHERE status = 'open' ORDER BY created_at;\n[/CODE]\n\nWant the index with a different type or column order?",
        "ann_a": [
            "Q e p :: Want a new index or a query rewrite?",
            "O a new index",
            "O a query rewrite",
        ],
        "ann_b": [
            "Q y p :: Want the index with a different type or column order?",
        ],
    },
    {
        "n": 43,
        "boundary": "yes_no/either_or",
        "note_a": "CSV export vs parquet dump = two data artifacts -> either_or",
        "note_b": "delimiter or compression = attributes of one export -> yes_no",
        "text_a": "Analytics asked for a one-off extract of last week's events (~2M rows).\n\nWant a CSV export or a Parquet dump?",
        "text_b": "Analytics asked for a one-off extract of last week's events (~2M rows).\n\nWant the export with a different delimiter or compression?",
        "ann_a": [
            "Q e p :: Want a CSV export or a Parquet dump?",
            "O a CSV export",
            "O a Parquet dump",
        ],
        "ann_b": [
            "Q y p :: Want the export with a different delimiter or compression?",
        ],
    },
    {
        "n": 44,
        "boundary": "yes_no/either_or",
        "note_a": "backfill job vs one-shot SQL = two backfill tactics -> either_or",
        "note_b": "chunk size or sleep = attributes of one backfill job -> yes_no",
        "text_a": "`accounts.region` is null for ~30% of rows after the import.\n\nShall I write a backfill job or a one-shot SQL update?",
        "text_b": "`accounts.region` is null for ~30% of rows after the import.\n\nShall I tune the backfill with a different chunk size or sleep?",
        "ann_a": [
            "Q e p :: Shall I write a backfill job or a one-shot SQL update?",
            "O write a backfill job",
            "O a one-shot SQL update",
        ],
        "ann_b": [
            "Q y p :: Shall I tune the backfill with a different chunk size or sleep?",
        ],
    },
    {
        "n": 45,
        "boundary": "yes_no/either_or",
        "note_a": "seed script vs fixture YAML = two test-data deliverables -> either_or",
        "note_b": "locale or row count = attributes of one seed -> yes_no",
        "text_a": "Dev DB boots empty; onboarding demos need sample tenants.\n\nWant a seed script or checked-in fixture YAML?",
        "text_b": "Dev DB boots empty; onboarding demos need sample tenants.\n\nWant the seed with a different locale or row count?",
        "ann_a": [
            "Q e p :: Want a seed script or checked-in fixture YAML?",
            "O a seed script",
            "O checked-in fixture YAML",
        ],
        "ann_b": [
            "Q y p :: Want the seed with a different locale or row count?",
        ],
    },
    {
        "n": 46,
        "boundary": "yes_no/either_or",
        "note_a": "soft delete vs hard purge = two deletion policies -> either_or",
        "note_b": "retention days or tombstone flag = attributes of one soft-delete -> yes_no",
        "text_a": "GDPR deletion request for tenant `t_demo`. Cascades touch 8 tables.\n\nWant soft-delete everywhere or a hard purge script?",
        "text_b": "GDPR deletion request for tenant `t_demo`. Cascades touch 8 tables.\n\nWant soft-delete with a different retention days or tombstone flag?",
        "ann_a": [
            "Q e p :: Want soft-delete everywhere or a hard purge script?",
            "O soft-delete everywhere",
            "O a hard purge script",
        ],
        "ann_b": [
            "Q y p :: Want soft-delete with a different retention days or tombstone flag?",
        ],
    },
    {
        "n": 47,
        "boundary": "yes_no/either_or",
        "note_a": "read replica routing vs cache layer = two scale tactics -> either_or",
        "note_b": "TTL or key prefix = attributes of one cache -> yes_no",
        "text_a": "Read traffic on `reports` is saturating the primary.\n\nWant read-replica routing or a Redis cache layer?",
        "text_b": "Read traffic on `reports` is saturating the primary.\n\nWant the cache with a different TTL or key prefix?",
        "ann_a": [
            "Q e p :: Want read-replica routing or a Redis cache layer?",
            "O read-replica routing",
            "O a Redis cache layer",
        ],
        "ann_b": [
            "Q y p :: Want the cache with a different TTL or key prefix?",
        ],
    },
    {
        "n": 48,
        "boundary": "yes_no/either_or",
        "note_a": "schema dump vs ER diagram = two docs -> either_or",
        "note_b": "format or include views = attributes of one schema dump -> yes_no",
        "text_a": "Onboarding engineers keep asking how `invoice_line` relates to `tax_rate`.\n\nWant a schema dump or an ER diagram?",
        "text_b": "Onboarding engineers keep asking how `invoice_line` relates to `tax_rate`.\n\nWant the schema dump with a different format or include-views setting?",
        "ann_a": [
            "Q e p :: Want a schema dump or an ER diagram?",
            "O a schema dump",
            "O an ER diagram",
        ],
        "ann_b": [
            "Q y p :: Want the schema dump with a different format or include-views setting?",
        ],
    },
    {
        "n": 49,
        "boundary": "yes_no/either_or",
        "note_a": "partition table vs archive job = two retention tactics -> either_or",
        "note_b": "partition key or interval = attributes of one partition plan -> yes_no",
        "text_a": "`events` is 400GB and growing ~5GB/day.\n\nWant monthly table partitions or a nightly archive job?",
        "text_b": "`events` is 400GB and growing ~5GB/day.\n\nWant partitions with a different partition key or interval?",
        "ann_a": [
            "Q e p :: Want monthly table partitions or a nightly archive job?",
            "O monthly table partitions",
            "O a nightly archive job",
        ],
        "ann_b": [
            "Q y p :: Want partitions with a different partition key or interval?",
        ],
    },
    {
        "n": 50,
        "boundary": "yes_no/either_or",
        "note_a": "nullability migration vs app-level default = two null fixes -> either_or",
        "note_b": "default value or backfill source = attributes of one nullability change -> yes_no",
        "text_a": "`sessions.user_agent` is nullable but every writer sends a string now.\n\nWant a NOT NULL migration or an app-level default only?",
        "text_b": "`sessions.user_agent` is nullable but every writer sends a string now.\n\nWant the NOT NULL change with a different default value or backfill source?",
        "ann_a": [
            "Q e p :: Want a NOT NULL migration or an app-level default only?",
            "O a NOT NULL migration",
            "O an app-level default only",
        ],
        "ann_b": [
            "Q y p :: Want the NOT NULL change with a different default value or backfill source?",
        ],
    },
    {
        "n": 51,
        "boundary": "yes_no/either_or",
        "note_a": "Dockerfile vs compose overlay = two infra deliverables -> either_or",
        "note_b": "base image or user = attributes of one Dockerfile tweak -> yes_no",
        "text_a": "API image still uses a fat `python:3.12` base; build is ~1.8GB.\n\nWant a slimmer Dockerfile or a compose overlay for local mounts?",
        "text_b": "API image still uses a fat `python:3.12` base; build is ~1.8GB.\n\nWant the Dockerfile with a different base image or user?",
        "ann_a": [
            "Q e p :: Want a slimmer Dockerfile or a compose overlay for local mounts?",
            "O a slimmer Dockerfile",
            "O a compose overlay for local mounts",
        ],
        "ann_b": [
            "Q y p :: Want the Dockerfile with a different base image or user?",
        ],
    },
    {
        "n": 52,
        "boundary": "yes_no/either_or",
        "note_a": "helm values vs kustomize overlay = two deploy configs -> either_or",
        "note_b": "replica count or resource limits = attributes of one values tweak -> yes_no",
        "text_a": "Staging needs lower replicas and a different ingress host than prod.\n\nWant a Helm values file or a Kustomize overlay?",
        "text_b": "Staging needs lower replicas and a different ingress host than prod.\n\nWant the values with a different replica count or resource limits?",
        "ann_a": [
            "Q e p :: Want a Helm values file or a Kustomize overlay?",
            "O a Helm values file",
            "O a Kustomize overlay",
        ],
        "ann_b": [
            "Q y p :: Want the values with a different replica count or resource limits?",
        ],
    },
    {
        "n": 53,
        "boundary": "yes_no/either_or",
        "note_a": "rollback vs canary pause = two incident actions -> either_or",
        "note_b": "canary percent or bake time = attributes of one canary tweak -> yes_no",
        "text_a": "Error rate spiked after the 14:02 deploy. Canary is at 20%.\n\nShall I roll back fully or pause the canary?",
        "text_b": "Error rate spiked after the 14:02 deploy. Canary is at 20%.\n\nShall I adjust the canary with a different percent or bake time?",
        "ann_a": [
            "Q e p :: Shall I roll back fully or pause the canary?",
            "O roll back fully",
            "O pause the canary",
        ],
        "ann_b": [
            "Q y p :: Shall I adjust the canary with a different percent or bake time?",
        ],
    },
    {
        "n": 54,
        "boundary": "yes_no/either_or",
        "note_a": "nginx config vs CDN rule = two edge fixes -> either_or",
        "note_b": "cache-control or path pattern = attributes of one CDN rule -> yes_no",
        "text_a": "Static assets are still hitting origin on every request.\n\nWant an nginx cache config or a CDN cache rule?",
        "text_b": "Static assets are still hitting origin on every request.\n\nWant the CDN rule with a different cache-control or path pattern?",
        "ann_a": [
            "Q e p :: Want an nginx cache config or a CDN cache rule?",
            "O an nginx cache config",
            "O a CDN cache rule",
        ],
        "ann_b": [
            "Q y p :: Want the CDN rule with a different cache-control or path pattern?",
        ],
    },
    {
        "n": 55,
        "boundary": "yes_no/either_or",
        "note_a": "runbook vs alert rule = two ops deliverables -> either_or",
        "note_b": "threshold or window = attributes of one alert -> yes_no",
        "text_a": "Disk on `db-1` crossed 85% twice this week with no playbook.\n\nWant a runbook or a new alert rule?",
        "text_b": "Disk on `db-1` crossed 85% twice this week with no playbook.\n\nWant the alert with a different threshold or window?",
        "ann_a": [
            "Q e p :: Want a runbook or a new alert rule?",
            "O a runbook",
            "O a new alert rule",
        ],
        "ann_b": [
            "Q y p :: Want the alert with a different threshold or window?",
        ],
    },
    {
        "n": 56,
        "boundary": "yes_no/either_or",
        "note_a": "terraform module vs manual apply notes = two IaC paths -> either_or",
        "note_b": "module version or workspace = attributes of one terraform change -> yes_no",
        "text_a": "S3 bucket for exports was created in the console; state is drifting.\n\nWant a Terraform module import or just manual apply notes?",
        "text_b": "S3 bucket for exports was created in the console; state is drifting.\n\nWant Terraform with a different module version or workspace?",
        "ann_a": [
            "Q e p :: Want a Terraform module import or just manual apply notes?",
            "O a Terraform module import",
            "O just manual apply notes",
        ],
        "ann_b": [
            "Q y p :: Want Terraform with a different module version or workspace?",
        ],
    },
    {
        "n": 57,
        "boundary": "yes_no/either_or",
        "note_a": "secrets rotation script vs vault policy = two secrets deliverables -> either_or",
        "note_b": "TTL or path = attributes of one vault policy -> yes_no",
        "text_a": "API keys in env files are overdue for rotation.\n\nWant a rotation script or a Vault policy update?",
        "text_b": "API keys in env files are overdue for rotation.\n\nWant the Vault policy with a different TTL or path?",
        "ann_a": [
            "Q e p :: Want a rotation script or a Vault policy update?",
            "O a rotation script",
            "O a Vault policy update",
        ],
        "ann_b": [
            "Q y p :: Want the Vault policy with a different TTL or path?",
        ],
    },
    {
        "n": 58,
        "boundary": "yes_no/either_or",
        "note_a": "healthcheck endpoint vs probe config = two health deliverables -> either_or",
        "note_b": "interval or failure threshold = attributes of one probe -> yes_no",
        "text_a": "Kube restarts the pod during long migrations because liveness is too aggressive.\n\nWant a dedicated healthcheck endpoint or adjusted probe config?",
        "text_b": "Kube restarts the pod during long migrations because liveness is too aggressive.\n\nWant the probe with a different interval or failure threshold?",
        "ann_a": [
            "Q e p :: Want a dedicated healthcheck endpoint or adjusted probe config?",
            "O a dedicated healthcheck endpoint",
            "O adjusted probe config",
        ],
        "ann_b": [
            "Q y p :: Want the probe with a different interval or failure threshold?",
        ],
    },
    {
        "n": 59,
        "boundary": "yes_no/either_or",
        "note_a": "log sampling vs structured fields = two logging fixes -> either_or",
        "note_b": "sample rate or field set = attributes of one logging tweak -> yes_no",
        "text_a": "Request logs are drowning the sink; `debug` dumps full bodies.\n\nWant log sampling or stricter structured fields?",
        "text_b": "Request logs are drowning the sink; `debug` dumps full bodies.\n\nWant logging with a different sample rate or field set?",
        "ann_a": [
            "Q e p :: Want log sampling or stricter structured fields?",
            "O log sampling",
            "O stricter structured fields",
        ],
        "ann_b": [
            "Q y p :: Want logging with a different sample rate or field set?",
        ],
    },
    {
        "n": 60,
        "boundary": "yes_no/either_or",
        "note_a": "autoscaling policy vs fixed capacity = two capacity plans -> either_or",
        "note_b": "min replicas or CPU target = attributes of one HPA -> yes_no",
        "text_a": "Traffic spikes at 09:00 UTC flatten the API (p99 > 2s).\n\nWant an HPA autoscaling policy or fixed higher capacity?",
        "text_b": "Traffic spikes at 09:00 UTC flatten the API (p99 > 2s).\n\nWant the HPA with a different min replicas or CPU target?",
        "ann_a": [
            "Q e p :: Want an HPA autoscaling policy or fixed higher capacity?",
            "O an HPA autoscaling policy",
            "O fixed higher capacity",
        ],
        "ann_b": [
            "Q y p :: Want the HPA with a different min replicas or CPU target?",
        ],
    },
    {
        "n": 61,
        "boundary": "yes_no/either_or",
        "note_a": "README section vs ADR = two doc deliverables -> either_or",
        "note_b": "tone or depth = attributes of one README tweak -> yes_no",
        "text_a": "Auth middleware behavior isn't documented; people keep re-asking in chat.\n\nWant a README section or a short ADR?",
        "text_b": "Auth middleware behavior isn't documented; people keep re-asking in chat.\n\nWant the README with a different tone or depth?",
        "ann_a": [
            "Q e p :: Want a README section or a short ADR?",
            "O a README section",
            "O a short ADR",
        ],
        "ann_b": [
            "Q y p :: Want the README with a different tone or depth?",
        ],
    },
    {
        "n": 62,
        "boundary": "yes_no/either_or",
        "note_a": "mermaid diagram vs sequence prose = two explainers -> either_or",
        "note_b": "detail level or orientation = attributes of one diagram -> yes_no",
        "text_a": "Webhook retry flow spans worker, queue, and partner API — hard to narrate.\n\nWant a Mermaid diagram or sequence prose?",
        "text_b": "Webhook retry flow spans worker, queue, and partner API — hard to narrate.\n\nWant the diagram with a different detail level or orientation?",
        "ann_a": [
            "Q e p :: Want a Mermaid diagram or sequence prose?",
            "O a Mermaid diagram",
            "O sequence prose",
        ],
        "ann_b": [
            "Q y p :: Want the diagram with a different detail level or orientation?",
        ],
    },
    {
        "n": 63,
        "boundary": "yes_no/either_or",
        "note_a": "changelog blurb vs migration guide = two release docs -> either_or",
        "note_b": "audience or length = attributes of one migration guide -> yes_no",
        "text_a": "Breaking: `Client.connect` now requires `timeout=`.\n\nWant a changelog blurb or a migration guide?",
        "text_b": "Breaking: `Client.connect` now requires `timeout=`.\n\nWant the migration guide with a different audience or length?",
        "ann_a": [
            "Q e p :: Want a changelog blurb or a migration guide?",
            "O a changelog blurb",
            "O a migration guide",
        ],
        "ann_b": [
            "Q y p :: Want the migration guide with a different audience or length?",
        ],
    },
    {
        "n": 64,
        "boundary": "yes_no/either_or",
        "note_a": "docstring pass vs external docs page = two doc targets -> either_or",
        "note_b": "style or verbosity = attributes of one docstring pass -> yes_no",
        "text_a": "Public helpers in `sdk/` have empty or misleading docstrings.\n\nWant an in-code docstring pass or an external docs page?",
        "text_b": "Public helpers in `sdk/` have empty or misleading docstrings.\n\nWant the docstring pass with a different style or verbosity?",
        "ann_a": [
            "Q e p :: Want an in-code docstring pass or an external docs page?",
            "O an in-code docstring pass",
            "O an external docs page",
        ],
        "ann_b": [
            "Q y p :: Want the docstring pass with a different style or verbosity?",
        ],
    },
    {
        "n": 65,
        "boundary": "yes_no/either_or",
        "note_a": "FAQ entry vs troubleshooting tree = two support docs -> either_or",
        "note_b": "order or section title = attributes of one FAQ tweak -> yes_no",
        "text_a": "Top support ticket is still \"upload stuck at 99%\".\n\nWant an FAQ entry or a troubleshooting decision tree?",
        "text_b": "Top support ticket is still \"upload stuck at 99%\".\n\nWant the FAQ with a different order or section title?",
        "ann_a": [
            "Q e p :: Want an FAQ entry or a troubleshooting decision tree?",
            "O an FAQ entry",
            "O a troubleshooting decision tree",
        ],
        "ann_b": [
            "Q y p :: Want the FAQ with a different order or section title?",
        ],
    },
    {
        "n": 66,
        "boundary": "yes_no/either_or",
        "note_a": "API reference stub vs example cookbook = two API docs -> either_or",
        "note_b": "language or endpoint focus = attributes of one cookbook -> yes_no",
        "text_a": "New `/v2/search` is live but undocumented beyond the OpenAPI field list.\n\nWant an API reference stub or an example cookbook?",
        "text_b": "New `/v2/search` is live but undocumented beyond the OpenAPI field list.\n\nWant the cookbook with a different language or endpoint focus?",
        "ann_a": [
            "Q e p :: Want an API reference stub or an example cookbook?",
            "O an API reference stub",
            "O an example cookbook",
        ],
        "ann_b": [
            "Q y p :: Want the cookbook with a different language or endpoint focus?",
        ],
    },
    {
        "n": 67,
        "boundary": "yes_no/either_or",
        "note_a": "comment cleanup vs inline links = two code-doc styles -> either_or",
        "note_b": "link target or anchor text = attributes of one link pass -> yes_no",
        "text_a": "Legacy comments still say \"see wiki\" with no URL.\n\nWant a comment cleanup pass or inline `[URL]` links to the new docs?",
        "text_b": "Legacy comments still say \"see wiki\" with no URL.\n\nWant the links with a different target or anchor text?",
        "ann_a": [
            "Q e p :: Want a comment cleanup pass or inline `[URL]` links to the new docs?",
            "O a comment cleanup pass",
            "O inline `[URL]` links to the new docs",
        ],
        "ann_b": [
            "Q y p :: Want the links with a different target or anchor text?",
        ],
    },
    {
        "n": 68,
        "boundary": "yes_no/either_or",
        "note_a": "onboarding checklist vs video script = two onboarding artifacts -> either_or",
        "note_b": "step count or tool assumptions = attributes of one checklist -> yes_no",
        "text_a": "New hires take ~2 days to get a local stack running.\n\nWant an onboarding checklist or a short video script?",
        "text_b": "New hires take ~2 days to get a local stack running.\n\nWant the checklist with a different step count or tool assumptions?",
        "ann_a": [
            "Q e p :: Want an onboarding checklist or a short video script?",
            "O an onboarding checklist",
            "O a short video script",
        ],
        "ann_b": [
            "Q y p :: Want the checklist with a different step count or tool assumptions?",
        ],
    },
    {
        "n": 69,
        "boundary": "yes_no/either_or",
        "note_a": "RFC draft vs Slack summary = two communication artifacts -> either_or",
        "note_b": "title or stakeholder list = attributes of one RFC -> yes_no",
        "text_a": "Proposal: move rate limiting from nginx to the app edge.\n\nWant an RFC draft or a Slack summary for the team?",
        "text_b": "Proposal: move rate limiting from nginx to the app edge.\n\nWant the RFC with a different title or stakeholder list?",
        "ann_a": [
            "Q e p :: Want an RFC draft or a Slack summary for the team?",
            "O an RFC draft",
            "O a Slack summary for the team",
        ],
        "ann_b": [
            "Q y p :: Want the RFC with a different title or stakeholder list?",
        ],
    },
    {
        "n": 70,
        "boundary": "yes_no/either_or",
        "note_a": "glossaries vs examples appendix = two doc additions -> either_or",
        "note_b": "term set or sort order = attributes of one glossary -> yes_no",
        "text_a": "Domain jargon (`ledger`, `hold`, `capture`) confuses external contributors.\n\nWant a glossary or an examples appendix?",
        "text_b": "Domain jargon (`ledger`, `hold`, `capture`) confuses external contributors.\n\nWant the glossary with a different term set or sort order?",
        "ann_a": [
            "Q e p :: Want a glossary or an examples appendix?",
            "O a glossary",
            "O an examples appendix",
        ],
        "ann_b": [
            "Q y p :: Want the glossary with a different term set or sort order?",
        ],
    },
    {
        "n": 71,
        "boundary": "yes_no/either_or",
        "note_a": "profile flamegraph vs allocation report = two perf artifacts -> either_or",
        "note_b": "sample rate or duration = attributes of one profile run -> yes_no",
        "text_a": "p99 on `/search` jumped from 120ms → 480ms after the tokenizer change.\n\nWant a CPU flamegraph or an allocation report?",
        "text_b": "p99 on `/search` jumped from 120ms → 480ms after the tokenizer change.\n\nWant the profile with a different sample rate or duration?",
        "ann_a": [
            "Q e p :: Want a CPU flamegraph or an allocation report?",
            "O a CPU flamegraph",
            "O an allocation report",
        ],
        "ann_b": [
            "Q y p :: Want the profile with a different sample rate or duration?",
        ],
    },
    {
        "n": 72,
        "boundary": "yes_no/either_or",
        "note_a": "benchmark harness vs one-off timing = two measurement approaches -> either_or",
        "note_b": "warmup or iteration count = attributes of one bench -> yes_no",
        "text_a": "Suspect `json.dumps` in the hot path. Need numbers before optimizing.\n\nShall I add a benchmark harness or do a one-off timing script?",
        "text_b": "Suspect `json.dumps` in the hot path. Need numbers before optimizing.\n\nShall I run the bench with a different warmup or iteration count?",
        "ann_a": [
            "Q e p :: Shall I add a benchmark harness or do a one-off timing script?",
            "O add a benchmark harness",
            "O do a one-off timing script",
        ],
        "ann_b": [
            "Q y p :: Shall I run the bench with a different warmup or iteration count?",
        ],
    },
    {
        "n": 73,
        "boundary": "yes_no/either_or",
        "note_a": "memoize vs precompute table = two speedups -> either_or",
        "note_b": "cache size or eviction = attributes of one memoize -> yes_no",
        "text_a": "`score_row` recomputes the same weights per request.\n\nWant me to memoize it or precompute a lookup table?",
        "text_b": "`score_row` recomputes the same weights per request.\n\nWant memoization with a different cache size or eviction policy?",
        "ann_a": [
            "Q e p :: Want me to memoize it or precompute a lookup table?",
            "O memoize it",
            "O precompute a lookup table",
        ],
        "ann_b": [
            "Q y p :: Want memoization with a different cache size or eviction policy?",
        ],
    },
    {
        "n": 74,
        "boundary": "yes_no/either_or",
        "note_a": "bundle analyzer report vs lazy route = two frontend perf paths -> either_or",
        "note_b": "chunk name or preload = attributes of one lazy route -> yes_no",
        "text_a": "Initial JS is 890KB gzipped; `AdminPanel` alone is ~180KB.\n\nWant a bundle analyzer report or to lazy-load that route?",
        "text_b": "Initial JS is 890KB gzipped; `AdminPanel` alone is ~180KB.\n\nWant the lazy route with a different chunk name or preload strategy?",
        "ann_a": [
            "Q e p :: Want a bundle analyzer report or to lazy-load that route?",
            "O a bundle analyzer report",
            "O to lazy-load that route",
        ],
        "ann_b": [
            "Q y p :: Want the lazy route with a different chunk name or preload strategy?",
        ],
    },
    {
        "n": 75,
        "boundary": "yes_no/either_or",
        "note_a": "connection pool bump vs query batching = two DB perf fixes -> either_or",
        "note_b": "pool size or idle timeout = attributes of one pool tweak -> yes_no",
        "text_a": "Under load, workers block waiting on DB connections (`too many clients`).\n\nWant a connection-pool bump or query batching?",
        "text_b": "Under load, workers block waiting on DB connections (`too many clients`).\n\nWant the pool with a different size or idle timeout?",
        "ann_a": [
            "Q e p :: Want a connection-pool bump or query batching?",
            "O a connection-pool bump",
            "O query batching",
        ],
        "ann_b": [
            "Q y p :: Want the pool with a different size or idle timeout?",
        ],
    },
    {
        "n": 76,
        "boundary": "yes_no/either_or",
        "note_a": "security advisory note vs patch PR = two security deliverables -> either_or",
        "note_b": "severity or CVE id field = attributes of one advisory -> yes_no",
        "text_a": "Dependabot flagged `lodash` prototype-pollution advisory in a transitive dep.\n\nWant a security advisory note for the team or a patch PR that bumps the tree?",
        "text_b": "Dependabot flagged `lodash` prototype-pollution advisory in a transitive dep.\n\nWant the advisory note with a different severity or CVE id field?",
        "ann_a": [
            "Q e p :: Want a security advisory note for the team or a patch PR that bumps the tree?",
            "O a security advisory note for the team",
            "O a patch PR that bumps the tree",
        ],
        "ann_b": [
            "Q y p :: Want the advisory note with a different severity or CVE id field?",
        ],
    },
    {
        "n": 77,
        "boundary": "yes_no/either_or",
        "note_a": "CSP header vs nonce helper = two XSS mitigations -> either_or",
        "note_b": "directive or report-uri = attributes of one CSP -> yes_no",
        "text_a": "Inline scripts still required for the marketing landing page.\n\nWant a Content-Security-Policy header draft or a nonce helper in the template?",
        "text_b": "Inline scripts still required for the marketing landing page.\n\nWant the CSP with a different directive set or report-uri?",
        "ann_a": [
            "Q e p :: Want a Content-Security-Policy header draft or a nonce helper in the template?",
            "O a Content-Security-Policy header draft",
            "O a nonce helper in the template",
        ],
        "ann_b": [
            "Q y p :: Want the CSP with a different directive set or report-uri?",
        ],
    },
    {
        "n": 78,
        "boundary": "yes_no/either_or",
        "note_a": "secret scan report vs pre-commit hook = two secret controls -> either_or",
        "note_b": "allowlist or scanner ruleset = attributes of one scan -> yes_no",
        "text_a": "Found a committed `.pem` in history (dummy fixture, not live).\n\nWant a secret-scan report or a pre-commit hook to block repeats?",
        "text_b": "Found a committed `.pem` in history (dummy fixture, not live).\n\nWant the scan with a different allowlist or ruleset?",
        "ann_a": [
            "Q e p :: Want a secret-scan report or a pre-commit hook to block repeats?",
            "O a secret-scan report",
            "O a pre-commit hook to block repeats",
        ],
        "ann_b": [
            "Q y p :: Want the scan with a different allowlist or ruleset?",
        ],
    },
    {
        "n": 79,
        "boundary": "yes_no/either_or",
        "note_a": "rate limit middleware vs WAF rule = two abuse controls -> either_or",
        "note_b": "burst or window = attributes of one rate limit -> yes_no",
        "text_a": "Scrapers are hammering `/api/public/search` from a few ASNs.\n\nWant app rate-limit middleware or an edge WAF rule?",
        "text_b": "Scrapers are hammering `/api/public/search` from a few ASNs.\n\nWant the rate limit with a different burst or window?",
        "ann_a": [
            "Q e p :: Want app rate-limit middleware or an edge WAF rule?",
            "O app rate-limit middleware",
            "O an edge WAF rule",
        ],
        "ann_b": [
            "Q y p :: Want the rate limit with a different burst or window?",
        ],
    },
    {
        "n": 80,
        "boundary": "yes_no/either_or",
        "note_a": "threat model doc vs checklist = two security docs -> either_or",
        "note_b": "scope or asset list = attributes of one threat model -> yes_no",
        "text_a": "Before exposing the admin GraphQL surface externally, we should write something down.\n\nWant a short threat-model doc or a security checklist?",
        "text_b": "Before exposing the admin GraphQL surface externally, we should write something down.\n\nWant the threat model with a different scope or asset list?",
        "ann_a": [
            "Q e p :: Want a short threat-model doc or a security checklist?",
            "O a short threat-model doc",
            "O a security checklist",
        ],
        "ann_b": [
            "Q y p :: Want the threat model with a different scope or asset list?",
        ],
    },
    {
        "n": 81,
        "boundary": "yes_no/either_or",
        "note_a": "terse: rebase vs merge = two git ops -> either_or",
        "note_b": "terse: strategy or message = attributes of one merge -> yes_no",
        "text_a": "Conflicts in `Cargo.lock`.\n\nRebase or merge?",
        "text_b": "Conflicts in `Cargo.lock`.\n\nMerge with a different strategy or message?",
        "ann_a": [
            "Q e p :: Rebase or merge?",
            "O Rebase",
            "O merge",
        ],
        "ann_b": [
            "Q y p :: Merge with a different strategy or message?",
        ],
    },
    {
        "n": 82,
        "boundary": "yes_no/either_or",
        "note_a": "terse CLI: patch vs commit = two deliverables -> either_or",
        "note_b": "terse: message or trailer = attributes of one commit -> yes_no",
        "text_a": "fix applied. green.\n\npatch or commit?",
        "text_b": "fix applied. green.\n\ncommit with a different message or trailer?",
        "ann_a": [
            "Q e p :: patch or commit?",
            "O patch",
            "O commit",
        ],
        "ann_b": [
            "Q y p :: commit with a different message or trailer?",
        ],
    },
    {
        "n": 83,
        "boundary": "yes_no/either_or",
        "note_a": "chatty: walkthrough vs checklist = two teaching artifacts -> either_or",
        "note_b": "chatty: pace or depth = attributes of one walkthrough -> yes_no",
        "text_a": "Okay — the flaky test is sorted. I left a couple breadcrumbs in the PR description in case this bites us again.\n\nHonestly happy to keep going if useful: want a slow walkthrough of the race, or a short checklist you can paste into the runbook?",
        "text_b": "Okay — the flaky test is sorted. I left a couple breadcrumbs in the PR description in case this bites us again.\n\nHonestly happy to keep going if useful: want that walkthrough with a different pace or depth?",
        "ann_a": [
            "Q e p :: want a slow walkthrough of the race, or a short checklist you can paste into the runbook?",
            "O a slow walkthrough of the race",
            "O a short checklist you can paste into the runbook",
        ],
        "ann_b": [
            "Q y p :: want that walkthrough with a different pace or depth?",
        ],
    },
    {
        "n": 84,
        "boundary": "yes_no/either_or",
        "note_a": "long status then diff vs plan = two next steps -> either_or",
        "note_b": "long status then plan attributes = yes_no",
        "text_a": "Here's where things stand on the billing refactor:\n\n1. **Extracted** `InvoiceLine` from the god-object `Invoice`\n2. **Moved** tax calculation into `tax/engine.py`\n3. **Left** PDF rendering alone — still couples to the old model\n\nRemaining risk is the PDF path: it reaches into private fields.\n\nWant a diff of the tax extraction or a plan for the PDF decoupling?",
        "text_b": "Here's where things stand on the billing refactor:\n\n1. **Extracted** `InvoiceLine` from the god-object `Invoice`\n2. **Moved** tax calculation into `tax/engine.py`\n3. **Left** PDF rendering alone — still couples to the old model\n\nRemaining risk is the PDF path: it reaches into private fields.\n\nWant the PDF plan with a different scope or milestone order?",
        "ann_a": [
            "Q e p :: Want a diff of the tax extraction or a plan for the PDF decoupling?",
            "O a diff of the tax extraction",
            "O a plan for the PDF decoupling",
        ],
        "ann_b": [
            "Q y p :: Want the PDF plan with a different scope or milestone order?",
        ],
    },
    {
        "n": 85,
        "boundary": "yes_no/either_or",
        "note_a": "code block then fixture vs mock = two test helpers -> either_or",
        "note_b": "code block then fixture attrs = yes_no",
        "text_a": "Reproduction for the timezone bug:\n\n[CODE]\n>>> from app.timeutil import end_of_day\n>>> end_of_day(\"2026-09-24\", tz=\"America/Los_Angeles\")\ndatetime.datetime(2026, 9, 25, 6, 59, 59, tzinfo=datetime.timezone.utc)  # wrong\n[/CODE]\n\nWant a failing fixture or a timezone mock helper?",
        "text_b": "Reproduction for the timezone bug:\n\n[CODE]\n>>> from app.timeutil import end_of_day\n>>> end_of_day(\"2026-09-24\", tz=\"America/Los_Angeles\")\ndatetime.datetime(2026, 9, 25, 6, 59, 59, tzinfo=datetime.timezone.utc)  # wrong\n[/CODE]\n\nWant the fixture with a different timezone or assertion style?",
        "ann_a": [
            "Q e p :: Want a failing fixture or a timezone mock helper?",
            "O a failing fixture",
            "O a timezone mock helper",
        ],
        "ann_b": [
            "Q y p :: Want the fixture with a different timezone or assertion style?",
        ],
    },
    {
        "n": 86,
        "boundary": "yes_no/either_or",
        "note_a": "bold list then implement vs spike = two work modes -> either_or",
        "note_b": "bold list then spike attrs = yes_no",
        "text_a": "Two approaches look viable for the search ranking tweak:\n\n- **Boost recent** — simple time-decay on existing scores\n- **Learned ranker** — needs labeled clicks we don't have yet\n\nWant me to implement the boost or spike the learned ranker?",
        "text_b": "Two approaches look viable for the search ranking tweak:\n\n- **Boost recent** — simple time-decay on existing scores\n- **Learned ranker** — needs labeled clicks we don't have yet\n\nWant the boost with a different half-life or weight?",
        "ann_a": [
            "Q e p :: Want me to implement the boost or spike the learned ranker?",
            "O implement the boost",
            "O spike the learned ranker",
        ],
        "ann_b": [
            "Q y p :: Want the boost with a different half-life or weight?",
        ],
    },
    {
        "n": 87,
        "boundary": "yes_no/either_or",
        "note_a": "URL status then reopen vs comment = two GH actions -> either_or",
        "note_b": "URL status then comment attrs = yes_no",
        "text_a": "Issue looks fixed on `main` but the bot never closed it.\n\n[URL]\n\nWant me to reopen it with a note or just leave a closing comment?",
        "text_b": "Issue looks fixed on `main` but the bot never closed it.\n\n[URL]\n\nWant the closing comment with a different tone or commit link?",
        "ann_a": [
            "Q e p :: Want me to reopen it with a note or just leave a closing comment?",
            "O reopen it with a note",
            "O just leave a closing comment",
        ],
        "ann_b": [
            "Q y p :: Want the closing comment with a different tone or commit link?",
        ],
    },
    {
        "n": 88,
        "boundary": "yes_no/either_or",
        "note_a": "multi-para then types stub vs runtime check = two safety nets -> either_or",
        "note_b": "multi-para then types attrs = yes_no",
        "text_a": "I traced the `NoneType` crash. `UserProfile.avatar_url` is optional in the DB but treated as `str` in the serializer.\n\nA proper fix is either tightening types at the boundary or adding a runtime guard before render. Types would catch it in CI; the guard protects prod tonight.\n\nWant a types stub update or a runtime check?",
        "text_b": "I traced the `NoneType` crash. `UserProfile.avatar_url` is optional in the DB but treated as `str` in the serializer.\n\nA proper fix is either tightening types at the boundary or adding a runtime guard before render. Types would catch it in CI; the guard protects prod tonight.\n\nWant the types stub with a different Optional placement or import style?",
        "ann_a": [
            "Q e p :: Want a types stub update or a runtime check?",
            "O a types stub update",
            "O a runtime check",
        ],
        "ann_b": [
            "Q y p :: Want the types stub with a different Optional placement or import style?",
        ],
    },
    {
        "n": 89,
        "boundary": "yes_no/either_or",
        "note_a": "table then migrate now vs dry-run = two migration modes -> either_or",
        "note_b": "table then dry-run attrs = yes_no",
        "text_a": "Migration preview:\n\n| Step | Action | Est. lock |\n|------|--------|-----------|\n| 1 | add column nullable | <1s |\n| 2 | backfill in batches | ~12m |\n| 3 | set NOT NULL | ~3s |\n\nWant me to run the migration now or only the dry-run plan?",
        "text_b": "Migration preview:\n\n| Step | Action | Est. lock |\n|------|--------|-----------|\n| 1 | add column nullable | <1s |\n| 2 | backfill in batches | ~12m |\n| 3 | set NOT NULL | ~3s |\n\nWant the dry-run with a different batch size or lock budget?",
        "ann_a": [
            "Q e p :: Want me to run the migration now or only the dry-run plan?",
            "O run the migration now",
            "O only the dry-run plan",
        ],
        "ann_b": [
            "Q y p :: Want the dry-run with a different batch size or lock budget?",
        ],
    },
    {
        "n": 90,
        "boundary": "yes_no/either_or",
        "note_a": "inline code heavy then lint rule vs ignore = two lint paths -> either_or",
        "note_b": "inline code heavy then rule attrs = yes_no",
        "text_a": "`ruff` is complaining about `B006` on default mutable args in `cli/flags.py`:\n\n[CODE]\ndef parse(args, seen={}):  # B006\n[/CODE]\n\nWant a lint rule fix (use `None` + init) or a targeted `# noqa`?",
        "text_b": "`ruff` is complaining about `B006` on default mutable args in `cli/flags.py`:\n\n[CODE]\ndef parse(args, seen={}):  # B006\n[/CODE]\n\nWant the lint fix with a different helper name or module placement?",
        "ann_a": [
            "Q e p :: Want a lint rule fix (use `None` + init) or a targeted `# noqa`?",
            "O a lint rule fix (use `None` + init)",
            "O a targeted `# noqa`",
        ],
        "ann_b": [
            "Q y p :: Want the lint fix with a different helper name or module placement?",
        ],
    },
    {
        "n": 91,
        "boundary": "yes_no/either_or",
        "note_a": "Shall I…? two deliverables with backticks -> either_or",
        "note_b": "Shall I…? attribute pair on one change -> yes_no",
        "text_a": "Typed the public surface of `CacheClient`. Private helpers still `Any`.\n\nShall I publish the `.pyi` stubs or generate HTML type docs?",
        "text_b": "Typed the public surface of `CacheClient`. Private helpers still `Any`.\n\nShall I publish the stubs with a different package layout or version tag?",
        "ann_a": [
            "Q e p :: Shall I publish the `.pyi` stubs or generate HTML type docs?",
            "O publish the `.pyi` stubs",
            "O generate HTML type docs",
        ],
        "ann_b": [
            "Q y p :: Shall I publish the stubs with a different package layout or version tag?",
        ],
    },
    {
        "n": 92,
        "boundary": "yes_no/either_or",
        "note_a": "Would you like me to… two CI actions -> either_or",
        "note_b": "Would you like me to… one workflow attribute tweak -> yes_no",
        "text_a": "Nightly job is red on `windows-latest` only (path separators).\n\nWould you like me to fix the path handling or disable the Windows matrix entry?",
        "text_b": "Nightly job is red on `windows-latest` only (path separators).\n\nWould you like me to tweak the matrix with a different runner image or shell?",
        "ann_a": [
            "Q e p :: Would you like me to fix the path handling or disable the Windows matrix entry?",
            "O fix the path handling",
            "O disable the Windows matrix entry",
        ],
        "ann_b": [
            "Q y p :: Would you like me to tweak the matrix with a different runner image or shell?",
        ],
    },
    {
        "n": 93,
        "boundary": "yes_no/either_or",
        "note_a": "Want me to… draft vs apply = two states of change -> either_or",
        "note_b": "Want me to… format or section order = attrs of one draft -> yes_no",
        "text_a": "I drafted release notes from the merged PRs since `v1.3.0`.\n\nWant me to leave them as a draft file or apply them to `CHANGELOG.md`?",
        "text_b": "I drafted release notes from the merged PRs since `v1.3.0`.\n\nWant me to revise the draft with a different format or section order?",
        "ann_a": [
            "Q e p :: Want me to leave them as a draft file or apply them to `CHANGELOG.md`?",
            "O leave them as a draft file",
            "O apply them to `CHANGELOG.md`",
        ],
        "ann_b": [
            "Q y p :: Want me to revise the draft with a different format or section order?",
        ],
    },
    {
        "n": 94,
        "boundary": "yes_no/either_or",
        "note_a": "two-sentence Q spanning choice arms -> either_or",
        "note_b": "single yes_no on attribute pair -> yes_no",
        "text_a": "Feature flag `new_checkout` is at 5% and metrics look flat.\n\nShall I bump it to 25% next? Or would you rather roll it back to 0%?",
        "text_b": "Feature flag `new_checkout` is at 5% and metrics look flat.\n\nShall I adjust the flag with a different percentage or bake time?",
        "ann_a": [
            "Q e p :: Shall I bump it to 25% next? Or would you rather roll it back to 0%?",
            "O bump it to 25% next",
            "O roll it back to 0%",
        ],
        "ann_b": [
            "Q y p :: Shall I adjust the flag with a different percentage or bake time?",
        ],
    },
    {
        "n": 95,
        "boundary": "yes_no/either_or",
        "note_a": " monorepo: package publish vs workspace bump = two release actions -> either_or",
        "note_b": " monorepo: tag or channel = attrs of one publish -> yes_no",
        "text_a": "`packages/ui` is ready; dependents still on the old workspace protocol.\n\nWant me to publish `@acme/ui@2.0.0` or only bump the workspace references?",
        "text_b": "`packages/ui` is ready; dependents still on the old workspace protocol.\n\nWant me to publish with a different tag or channel?",
        "ann_a": [
            "Q e p :: Want me to publish `@acme/ui@2.0.0` or only bump the workspace references?",
            "O publish `@acme/ui@2.0.0`",
            "O only bump the workspace references",
        ],
        "ann_b": [
            "Q y p :: Want me to publish with a different tag or channel?",
        ],
    },
    {
        "n": 96,
        "boundary": "yes_no/either_or",
        "note_a": "observability: dashboard vs trace sample = two o11y artifacts -> either_or",
        "note_b": "observability: panel or time range = attrs of one dashboard -> yes_no",
        "text_a": "Added spans around `CheckoutService.charge`. Nothing wired to Grafana yet.\n\nWant a starter dashboard or a saved trace sample?",
        "text_b": "Added spans around `CheckoutService.charge`. Nothing wired to Grafana yet.\n\nWant the dashboard with a different panel set or time range?",
        "ann_a": [
            "Q e p :: Want a starter dashboard or a saved trace sample?",
            "O a starter dashboard",
            "O a saved trace sample",
        ],
        "ann_b": [
            "Q y p :: Want the dashboard with a different panel set or time range?",
        ],
    },
    {
        "n": 97,
        "boundary": "yes_no/either_or",
        "note_a": "i18n: extract strings vs add locale file = two i18n deliverables -> either_or",
        "note_b": "i18n: locale code or plural rules = attrs of one locale add -> yes_no",
        "text_a": "Hard-coded English strings in `ErrorBanner` and `EmptyState`.\n\nWant me to extract the strings or add a `de` locale file scaffold?",
        "text_b": "Hard-coded English strings in `ErrorBanner` and `EmptyState`.\n\nWant the locale scaffold with a different locale code or plural rules?",
        "ann_a": [
            "Q e p :: Want me to extract the strings or add a `de` locale file scaffold?",
            "O extract the strings",
            "O add a `de` locale file scaffold",
        ],
        "ann_b": [
            "Q y p :: Want the locale scaffold with a different locale code or plural rules?",
        ],
    },
    {
        "n": 98,
        "boundary": "yes_no/either_or",
        "note_a": "proto: regen stubs vs hand-edit = two API sync paths -> either_or",
        "note_b": "proto: plugin or out dir = attrs of one regen -> yes_no",
        "text_a": "`payments.proto` added `RefundReason`. Generated Go stubs are stale.\n\nWant me to regenerate the stubs or hand-edit the Go types?",
        "text_b": "`payments.proto` added `RefundReason`. Generated Go stubs are stale.\n\nWant regeneration with a different plugin or out directory?",
        "ann_a": [
            "Q e p :: Want me to regenerate the stubs or hand-edit the Go types?",
            "O regenerate the stubs",
            "O hand-edit the Go types",
        ],
        "ann_b": [
            "Q y p :: Want regeneration with a different plugin or out directory?",
        ],
    },
    {
        "n": 99,
        "boundary": "yes_no/either_or",
        "note_a": "email: template preview vs send test = two email QA actions -> either_or",
        "note_b": "email: subject or from-name = attrs of one template tweak -> yes_no",
        "text_a": "Password-reset email HTML is updated; MJML compiles clean.\n\nWant a rendered preview or a send-to-yourself test?",
        "text_b": "Password-reset email HTML is updated; MJML compiles clean.\n\nWant the template with a different subject or from-name?",
        "ann_a": [
            "Q e p :: Want a rendered preview or a send-to-yourself test?",
            "O a rendered preview",
            "O a send-to-yourself test",
        ],
        "ann_b": [
            "Q y p :: Want the template with a different subject or from-name?",
        ],
    },
    {
        "n": 100,
        "boundary": "yes_no/either_or",
        "note_a": "wrap-up: summary doc vs follow-up issues = two closing deliverables -> either_or",
        "note_b": "wrap-up: title or label set = attrs of one issue draft -> yes_no",
        "text_a": "All requested items from the punch list are done:\n\n- flaky CI quarantined\n- docs stub for the new flag\n- changelog entry drafted\n\nWant a one-page summary doc or follow-up GitHub issues for the leftovers?",
        "text_b": "All requested items from the punch list are done:\n\n- flaky CI quarantined\n- docs stub for the new flag\n- changelog entry drafted\n\nWant the follow-up issues with a different title style or label set?",
        "ann_a": [
            "Q e p :: Want a one-page summary doc or follow-up GitHub issues for the leftovers?",
            "O a one-page summary doc",
            "O follow-up GitHub issues for the leftovers",
        ],
        "ann_b": [
            "Q y p :: Want the follow-up issues with a different title style or label set?",
        ],
    },
]
