# _batch_yn_eo_101_200.py

PAIRS = [
  {
    'n': 101,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Rebase onto `main` is clean; only the release notes conflicted and I resolved them by keeping both changelog bullets.\n\nShall I open a draft PR or push straight to your feature branch?',
    'text_b': 'Rebase onto `main` is clean; only the release notes conflicted and I resolved them by keeping both changelog bullets.\n\nShall I use a different PR title or description?',
    'ann_a': ['Q e p :: Shall I open a draft PR or push straight to your feature branch?', 'O open a draft PR', 'O push straight to your feature branch'],
    'ann_b': ['Q y p :: Shall I use a different PR title or description?'],
  },
  {
    'n': 102,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'CI failed on `lint` only — `test` and `typecheck` are green. The flake is the unused import I left in `src/cache.ts`.\n\nWant me to fix the lint and re-run, or paste the failing job log first?',
    'text_b': 'CI failed on `lint` only — `test` and `typecheck` are green. The flake is the unused import I left in `src/cache.ts`.\n\nWant me to fix the lint with a different rule severity or ignore path?',
    'ann_a': ['Q e p :: Want me to fix the lint and re-run, or paste the failing job log first?', 'O fix the lint and re-run', 'O paste the failing job log first'],
    'ann_b': ['Q y p :: Want me to fix the lint with a different rule severity or ignore path?'],
  },
  {
    'n': 103,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Snapshot mismatch in `Button.test.tsx` after the padding tweak.\n\nPrefer I update the snapshot or revert the CSS change?',
    'text_b': 'Snapshot mismatch in `Button.test.tsx` after the padding tweak.\n\nPrefer I use a different snapshot name or path?',
    'ann_a': ['Q e p :: Prefer I update the snapshot or revert the CSS change?', 'O update the snapshot', 'O revert the CSS change'],
    'ann_b': ['Q y p :: Prefer I use a different snapshot name or path?'],
  },
  {
    'n': 104,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Refactored `parseArgs` into a pure function; callers still use the old wrapper. Ready to delete the wrapper or keep it as a deprecated shim?',
    'text_b': 'Refactored `parseArgs` into a pure function; callers still use the old wrapper. Ready to use a different wrapper name or deprecation message?',
    'ann_a': ['Q e p :: Ready to delete the wrapper or keep it as a deprecated shim?', 'O delete the wrapper', 'O keep it as a deprecated shim'],
    'ann_b': ['Q y p :: Ready to use a different wrapper name or deprecation message?'],
  },
  {
    'n': 105,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Diff against HEAD is ready in the index; nothing pushed.\n\nThe empty-state illustration is in, but the CTA still says **Retry**.\n\nDo you want me to rewrite the empty copy or swap the illustration asset?',
    'text_b': 'Diff against HEAD is ready in the index; nothing pushed.\n\nThe empty-state illustration is in, but the CTA still says **Retry**.\n\nDo you want me to give the CTA a different label or color?',
    'ann_a': ['Q e p :: Do you want me to rewrite the empty copy or swap the illustration asset?', 'O rewrite the empty copy', 'O swap the illustration asset'],
    'ann_b': ['Q y p :: Do you want me to give the CTA a different label or color?'],
  },
  {
    'n': 106,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Migration `2026_09_25_add_audit_log` applies cleanly locally. Prod still has the old `events` table.\n\nWould you rather me draft the backfill script or schedule a maintenance window note?',
    'text_b': 'Migration `2026_09_25_add_audit_log` applies cleanly locally. Prod still has the old `events` table.\n\nWould you rather me use a different migration name or timestamp?',
    'ann_a': ['Q e p :: Would you rather me draft the backfill script or schedule a maintenance window note?', 'O draft the backfill script', 'O schedule a maintenance window note'],
    'ann_b': ['Q y p :: Would you rather me use a different migration name or timestamp?'],
  },
  {
    'n': 107,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Docs for the webhook verifier are stubbed under `docs/webhooks.md`. Want a full tutorial page or just an API reference table?',
    'text_b': 'Docs for the webhook verifier are stubbed under `docs/webhooks.md`. Want a different filename or section heading?',
    'ann_a': ['Q e p :: Want a full tutorial page or just an API reference table?', 'O a full tutorial page', 'O just an API reference table'],
    'ann_b': ['Q y p :: Want a different filename or section heading?'],
  },
  {
    'n': 108,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Found the N+1: `loadOrders` hits the DB once per row in the invoice loop.\n\n[CODE]\nSELECT * FROM line_items WHERE order_id = $1\n[/CODE]\n\nWant me to batch-load with `WHERE order_id = ANY($1)` or add a dataloader layer?',
    'text_b': 'Found the N+1: `loadOrders` hits the DB once per row in the invoice loop.\n\n[CODE]\nSELECT * FROM line_items WHERE order_id = $1\n[/CODE]\n\nWant me to use a different query alias or parameter name?',
    'ann_a': ['Q e p :: Want me to batch-load with `WHERE order_id = ANY($1)` or add a dataloader layer?', 'O batch-load with `WHERE order_id = ANY($1)`', 'O add a dataloader layer'],
    'ann_b': ['Q y p :: Want me to use a different query alias or parameter name?'],
  },
  {
    'n': 109,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': '`terraform plan` wants to replace the node pool (AMI bump). Shall I apply that replace or pin the old AMI for now?',
    'text_b': '`terraform plan` wants to replace the node pool (AMI bump). Shall I use a different AMI id or region tag?',
    'ann_a': ['Q e p :: Shall I apply that replace or pin the old AMI for now?', 'O apply that replace', 'O pin the old AMI for now'],
    'ann_b': ['Q y p :: Shall I use a different AMI id or region tag?'],
  },
  {
    'n': 110,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Typecheck is clean after the `UserId` branded-type change. Want a short changelog blurb or a before/after typediff?',
    'text_b': 'Typecheck is clean after the `UserId` branded-type change. Want a different changelog tone or length?',
    'ann_a': ['Q e p :: Want a short changelog blurb or a before/after typediff?', 'O a short changelog blurb', 'O a before/after typediff'],
    'ann_b': ['Q y p :: Want a different changelog tone or length?'],
  },
  {
    'n': 111,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Snippet of the current config:\n\n[CODE]\n\nThe flaky `e2e/login.spec.ts` failed once on the wait for `#session`.\n\nWould you like me to harden the assertion or quarantine the test?',
    'text_b': 'Snippet of the current config:\n\n[CODE]\n\nThe flaky `e2e/login.spec.ts` failed once on the wait for `#session`.\n\nWould you like me to use a different timeout or selector?',
    'ann_a': ['Q e p :: Would you like me to harden the assertion or quarantine the test?', 'O harden the assertion', 'O quarantine the test'],
    'ann_b': ['Q y p :: Would you like me to use a different timeout or selector?'],
  },
  {
    'n': 112,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Stashed your WIP as `wip-billing-form`. Prefer I restore that stash or start fresh from `main`?',
    'text_b': 'Stashed your WIP as `wip-billing-form`. Prefer I use a different stash name or message?',
    'ann_a': ['Q e p :: Prefer I restore that stash or start fresh from `main`?', 'O restore that stash', 'O start fresh from `main`'],
    'ann_b': ['Q y p :: Prefer I use a different stash name or message?'],
  },
  {
    'n': 113,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Dark-mode tokens for the sidebar are in `tokens.css`. The active nav item still uses the light accent.\n\nWant me to flip the active state to the dark accent or leave a screenshot comparison?',
    'text_b': 'Dark-mode tokens for the sidebar are in `tokens.css`. The active nav item still uses the light accent.\n\nWant me to give the active state a different accent color or weight?',
    'ann_a': ['Q e p :: Want me to flip the active state to the dark accent or leave a screenshot comparison?', 'O flip the active state to the dark accent', 'O leave a screenshot comparison'],
    'ann_b': ['Q y p :: Want me to give the active state a different accent color or weight?'],
  },
  {
    'n': 114,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nCSV import accepts the new `sku` column. Rows with blank SKUs are skipped silently today.\n\nShall I reject those rows with an error or map them to a placeholder SKU?',
    'text_b': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nCSV import accepts the new `sku` column. Rows with blank SKU are skipped silently today.\n\nShall I use a different error code or message text?',
    'ann_a': ['Q e p :: Shall I reject those rows with an error or map them to a placeholder SKU?', 'O reject those rows with an error', 'O map them to a placeholder SKU'],
    'ann_b': ['Q y p :: Shall I use a different error code or message text?'],
  },
  {
    'n': 115,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Helm chart bumps `image.tag` to `1.4.2`. The values file still points at the old pull secret name.\n\nDo you want me to update the secret reference or document the manual rotate step?',
    'text_b': 'Helm chart bumps `image.tag` to `1.4.2`. The values file still points at the old pull secret name.\n\nDo you want me to use a different secret name or namespace?',
    'ann_a': ['Q e p :: Do you want me to update the secret reference or document the manual rotate step?', 'O update the secret reference', 'O document the manual rotate step'],
    'ann_b': ['Q y p :: Do you want me to use a different secret name or namespace?'],
  },
  {
    'n': 116,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'I sketched the ADR for switching to connection pooling.\n\nWant me to commit the ADR draft or expand it into a design doc with diagrams?',
    'text_b': 'I sketched the ADR for switching to connection pooling.\n\nWant me to use a different ADR number or title?',
    'ann_a': ['Q e p :: Want me to commit the ADR draft or expand it into a design doc with diagrams?', 'O commit the ADR draft', 'O expand it into a design doc with diagrams'],
    'ann_b': ['Q y p :: Want me to use a different ADR number or title?'],
  },
  {
    'n': 117,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Diff against HEAD is ready in the index; nothing pushed.\n\nCoverage dropped 1.2% because the new `retry` helper is untested.\n\nReady for me to add unit tests or a single integration case around the HTTP client?',
    'text_b': 'Diff against HEAD is ready in the index; nothing pushed.\n\nCoverage dropped 1.2% because the new `retry` helper is untested.\n\nReady for me to aim for a different coverage target or report format?',
    'ann_a': ['Q e p :: Ready for me to add unit tests or a single integration case around the HTTP client?', 'O add unit tests', 'O a single integration case around the HTTP client'],
    'ann_b': ['Q y p :: Ready for me to aim for a different coverage target or report format?'],
  },
  {
    'n': 118,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Git history has three tiny fixup commits on top of the feature. Want a soft reset into one commit or an interactive rebase recipe you can run?',
    'text_b': 'Git history has three tiny fixup commits on top of the feature. Want a different commit subject or body style?',
    'ann_a': ['Q e p :: Want a soft reset into one commit or an interactive rebase recipe you can run?', 'O a soft reset into one commit', 'O an interactive rebase recipe you can run'],
    'ann_b': ['Q y p :: Want a different commit subject or body style?'],
  },
  {
    'n': 119,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'The modal traps focus correctly now. Escape still does nothing.\n\nWould you rather me wire Escape to close or add a visible Close button only?',
    'text_b': 'The modal traps focus correctly now. Escape still does nothing.\n\nWould you rather me use a different Escape keybinding or aria-label?',
    'ann_a': ['Q e p :: Would you rather me wire Escape to close or add a visible Close button only?', 'O wire Escape to close', 'O add a visible Close button only'],
    'ann_b': ['Q y p :: Would you rather me use a different Escape keybinding or aria-label?'],
  },
  {
    'n': 120,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'I finished the exploratory pass and stopped before writing files.\n\nPipeline artifact is 180MB because we ship source maps. Shall I strip maps from the release zip or split a separate `*-debug` artifact?',
    'text_b': 'I finished the exploratory pass and stopped before writing files.\n\nPipeline artifact is 180MB because we ship source maps. Shall I use a different artifact name or retention days?',
    'ann_a': ['Q e p :: Shall I strip maps from the release zip or split a separate `*-debug` artifact?', 'O strip maps from the release zip', 'O split a separate `*-debug` artifact'],
    'ann_b': ['Q y p :: Shall I use a different artifact name or retention days?'],
  },
  {
    'n': 121,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Status after the cache migration:\n\n- Redis key prefix moved to `v2:`\n- cold-start latency +12ms median\n- hit rate recovered to 94%\n\nWant a Grafana panel dump or a short ops note for the channel?',
    'text_b': 'Status after the cache migration:\n\n- Redis key prefix moved to `v2:`\n- cold-start latency +12ms median\n- hit rate recovered to 94%\n\nWant a different Redis key prefix or TTL?',
    'ann_a': ['Q e p :: Want a Grafana panel dump or a short ops note for the channel?', 'O a Grafana panel dump', 'O a short ops note for the channel'],
    'ann_b': ['Q y p :: Want a different Redis key prefix or TTL?'],
  },
  {
    'n': 122,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': '`npm audit` reports one moderate in `semver` (dev-only). Prefer I bump the lockfile or leave a tracked exception?',
    'text_b': '`npm audit` reports one moderate in `semver` (dev-only). Prefer I use a different exception id or expiry?',
    'ann_a': ['Q e p :: Prefer I bump the lockfile or leave a tracked exception?', 'O bump the lockfile', 'O leave a tracked exception'],
    'ann_b': ['Q y p :: Prefer I use a different exception id or expiry?'],
  },
  {
    'n': 123,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Snippet of the current config:\n\n[CODE]\n\nExtracted `formatMoney` to `lib/money.ts`. Call sites still import from `utils`.\n\nDo you want me to update all imports now or leave a re-export shim for a sprint?',
    'text_b': 'Snippet of the current config:\n\n[CODE]\n\nExtracted `formatMoney` to `lib/money.ts`. Call sites still import from `utils`.\n\nDo you want me to use a different module path or export name?',
    'ann_a': ['Q e p :: Do you want me to update all imports now or leave a re-export shim for a sprint?', 'O update all imports now', 'O leave a re-export shim for a sprint'],
    'ann_b': ['Q y p :: Do you want me to use a different module path or export name?'],
  },
  {
    'n': 124,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'The toast stacks bottom-right and can cover the save button on short viewports.\n\nWant me to move toasts top-center or shrink the toast width?',
    'text_b': 'The toast stacks bottom-right and can cover the save button on short viewports.\n\nWant me to use a different toast duration or position offset?',
    'ann_a': ['Q e p :: Want me to move toasts top-center or shrink the toast width?', 'O move toasts top-center', 'O shrink the toast width'],
    'ann_b': ['Q y p :: Want me to use a different toast duration or position offset?'],
  },
  {
    'n': 125,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Parquet export of `events_daily` is ~2.1GB uncompressed. Shall I switch to zstd or sample a week for the debug drop?',
    'text_b': 'Parquet export of `events_daily` is ~2.1GB uncompressed. Shall I use a different compression codec or row-group size?',
    'ann_a': ['Q e p :: Shall I switch to zstd or sample a week for the debug drop?', 'O switch to zstd', 'O sample a week for the debug drop'],
    'ann_b': ['Q y p :: Shall I use a different compression codec or row-group size?'],
  },
  {
    'n': 126,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nNginx config now sets `client_max_body_size 32m`. Want a diff of the full server block or a one-line runbook for ops?',
    'text_b': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nNginx config now sets `client_max_body_size 32m`. Want a different body-size limit or unit?',
    'ann_a': ['Q e p :: Want a diff of the full server block or a one-line runbook for ops?', 'O a diff of the full server block', 'O a one-line runbook for ops'],
    'ann_b': ['Q y p :: Want a different body-size limit or unit?'],
  },
  {
    'n': 127,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'README install section still says `yarn`. Repo is on `pnpm`.\n\nWould you like me to rewrite the install docs or add a migration callout banner?',
    'text_b': 'README install section still says `yarn`. Repo is on `pnpm`.\n\nWould you like me to use a different package-manager wording or badge?',
    'ann_a': ['Q e p :: Would you like me to rewrite the install docs or add a migration callout banner?', 'O rewrite the install docs', 'O add a migration callout banner'],
    'ann_b': ['Q y p :: Would you like me to use a different package-manager wording or badge?'],
  },
  {
    'n': 128,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Feature flag `billing_v2` is at 10% in staging. Ready to bump to 50% or roll back to 0%?',
    'text_b': 'Feature flag `billing_v2` is at 10% in staging. Ready to use a different rollout percent or sticky key?',
    'ann_a': ['Q e p :: Ready to bump to 50% or roll back to 0%?', 'O bump to 50%', 'O roll back to 0%'],
    'ann_b': ['Q y p :: Ready to use a different rollout percent or sticky key?'],
  },
  {
    'n': 129,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Diff against HEAD is ready in the index; nothing pushed.\n\nJest is warning about open handles from the Redis client in teardown.\n\nWant me to add an explicit `quit()` in `afterAll` or switch the suite to a mock client?',
    'text_b': 'Diff against HEAD is ready in the index; nothing pushed.\n\nJest is warning about open handles from the Redis client in teardown.\n\nWant me to use a different teardown hook or timeout?',
    'ann_a': ['Q e p :: Want me to add an explicit `quit()` in `afterAll` or switch the suite to a mock client?', 'O add an explicit `quit()` in `afterAll`', 'O switch the suite to a mock client'],
    'ann_b': ['Q y p :: Want me to use a different teardown hook or timeout?'],
  },
  {
    'n': 130,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Branch is 4 commits ahead of `origin/main` with no conflicts.\n\nPrefer I force-with-lease push or open a PR from here?',
    'text_b': 'Branch is 4 commits ahead of `origin/main` with no conflicts.\n\nPrefer I use a different remote or branch name?',
    'ann_a': ['Q e p :: Prefer I force-with-lease push or open a PR from here?', 'O force-with-lease push', 'O open a PR from here'],
    'ann_b': ['Q y p :: Prefer I use a different remote or branch name?'],
  },
  {
    'n': 131,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Form validation now runs on blur. Submit still shows a generic **Something went wrong**.\n\nShall I map field errors into the inputs or keep a top-of-form summary only?',
    'text_b': 'Form validation now runs on blur. Submit still shows a generic **Something went wrong**.\n\nShall I use a different error tone or copy length?',
    'ann_a': ['Q e p :: Shall I map field errors into the inputs or keep a top-of-form summary only?', 'O map field errors into the inputs', 'O keep a top-of-form summary only'],
    'ann_b': ['Q y p :: Shall I use a different error tone or copy length?'],
  },
  {
    'n': 132,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'I finished the exploratory pass and stopped before writing files.\n\nS3 lifecycle rule drafts:\n\n1. Transition to IA after 30d\n2. Expire noncurrent versions after 90d\n\nWant me to apply both rules or only the IA transition for now?',
    'text_b': 'I finished the exploratory pass and stopped before writing files.\n\nS3 lifecycle rule drafts:\n\n1. Transition to IA after 30d\n2. Expire noncurrent versions after 90d\n\nWant me to use a different transition day count or storage class?',
    'ann_a': ['Q e p :: Want me to apply both rules or only the IA transition for now?', 'O apply both rules', 'O only the IA transition for now'],
    'ann_b': ['Q y p :: Want me to use a different transition day count or storage class?'],
  },
  {
    'n': 133,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Sphinx build warns about a missing reference to `AuthClient`.\n\nDo you want me to fix the cross-link or stub an autodoc page for that class?',
    'text_b': 'Sphinx build warns about a missing reference to `AuthClient`.\n\nDo you want me to use a different Sphinx role or link text?',
    'ann_a': ['Q e p :: Do you want me to fix the cross-link or stub an autodoc page for that class?', 'O fix the cross-link', 'O stub an autodoc page for that class'],
    'ann_b': ['Q y p :: Do you want me to use a different Sphinx role or link text?'],
  },
  {
    'n': 134,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Profiler flamegraph for `/checkout`:\n\n[CODE]\nrender: 42%\njson.parse: 18%\nnetwork wait: 31%\n[/CODE]\n\nWant a written bottleneck summary or the raw `.speedscope` file?',
    'text_b': 'Profiler flamegraph for `/checkout`:\n\n[CODE]\nrender: 42%\njson.parse: 18%\nnetwork wait: 31%\n[/CODE]\n\nWant a different profiler sample rate or output format?',
    'ann_a': ['Q e p :: Want a written bottleneck summary or the raw `.speedscope` file?', 'O a written bottleneck summary', 'O the raw `.speedscope` file'],
    'ann_b': ['Q y p :: Want a different profiler sample rate or output format?'],
  },
  {
    'n': 135,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Snippet of the current config:\n\n[CODE]\n\n`pre-commit` hook failed on `black`. Would you rather me reformat the staged files or skip hooks for this commit?',
    'text_b': 'Snippet of the current config:\n\n[CODE]\n\n`pre-commit` hook failed on `black`. Would you rather me use a different line length or target version?',
    'ann_a': ['Q e p :: Would you rather me reformat the staged files or skip hooks for this commit?', 'O reformat the staged files', 'O skip hooks for this commit'],
    'ann_b': ['Q y p :: Would you rather me use a different line length or target version?'],
  },
  {
    'n': 136,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'The search bar debounce is 300ms. Typing still feels sticky on slow CPUs.\n\nWant me to drop to 150ms or move filtering to a web worker?',
    'text_b': 'The search bar debounce is 300ms. Typing still feels sticky on slow CPUs.\n\nWant me to use a different debounce delay or leading/trailing mode?',
    'ann_a': ['Q e p :: Want me to drop to 150ms or move filtering to a web worker?', 'O drop to 150ms', 'O move filtering to a web worker'],
    'ann_b': ['Q y p :: Want me to use a different debounce delay or leading/trailing mode?'],
  },
  {
    'n': 137,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': "Airflow DAG `ingest_clicks` missed yesterday's partition. Shall I trigger a backfill for that day or widen the catchup window going forward?",
    'text_b': "Airflow DAG `ingest_clicks` missed yesterday's partition. Shall I use a different DAG id or schedule interval?",
    'ann_a': ['Q e p :: Shall I trigger a backfill for that day or widen the catchup window going forward?', 'O trigger a backfill for that day', 'O widen the catchup window going forward'],
    'ann_b': ['Q y p :: Shall I use a different DAG id or schedule interval?'],
  },
  {
    'n': 138,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nChangelog entry is drafted under **Unreleased**. Prefer I cut a `v0.9.1` section now or leave it until you tag?',
    'text_b': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nChangelog entry is drafted under **Unreleased**. Prefer I use a different version label or date format?',
    'ann_a': ['Q e p :: Prefer I cut a `v0.9.1` section now or leave it until you tag?', 'O cut a `v0.9.1` section now', 'O leave it until you tag'],
    'ann_b': ['Q y p :: Prefer I use a different version label or date format?'],
  },
  {
    'n': 139,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Storybook story for `EmptyState` compiles. Controls for `title`/`subtitle` are missing.\n\nWant me to add argTypes or export a second story for the error variant?',
    'text_b': 'Storybook story for `EmptyState` compiles. Controls for `title`/`subtitle` are missing.\n\nWant me to use a different story title or layout?',
    'ann_a': ['Q e p :: Want me to add argTypes or export a second story for the error variant?', 'O add argTypes', 'O export a second story for the error variant'],
    'ann_b': ['Q y p :: Want me to use a different story title or layout?'],
  },
  {
    'n': 140,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Dockerfile multi-stage build shaves 80MB. `HEALTHCHECK` still curls `/` instead of `/readyz`.\n\nDo you want me to fix the healthcheck or leave a note in the deploy checklist?',
    'text_b': 'Dockerfile multi-stage build shaves 80MB. `HEALTHCHECK` still curls `/` instead of `/readyz`.\n\nDo you want me to use a different health path or interval?',
    'ann_a': ['Q e p :: Do you want me to fix the healthcheck or leave a note in the deploy checklist?', 'O fix the healthcheck', 'O leave a note in the deploy checklist'],
    'ann_b': ['Q y p :: Do you want me to use a different health path or interval?'],
  },
  {
    'n': 141,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Diff against HEAD is ready in the index; nothing pushed.\n\nTyped the public SDK surface; internals stay `any` for now.\n\nReady for me to publish a typed alpha or keep shipping untyped until internals settle?',
    'text_b': 'Diff against HEAD is ready in the index; nothing pushed.\n\nTyped the public SDK surface; internals stay `any` for now.\n\nReady for me to use a different package name or version tag?',
    'ann_a': ['Q e p :: Ready for me to publish a typed alpha or keep shipping untyped until internals settle?', 'O publish a typed alpha', 'O keep shipping untyped until internals settle'],
    'ann_b': ['Q y p :: Ready for me to use a different package name or version tag?'],
  },
  {
    'n': 142,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Matrix job matrix grows to 12 cells with the new Node versions. Want me to trim to LTS only or keep the full matrix and accept longer CI?',
    'text_b': 'Matrix job matrix grows to 12 cells with the new Node versions. Want me to use a different Node version set or OS image?',
    'ann_a': ['Q e p :: Want me to trim to LTS only or keep the full matrix and accept longer CI?', 'O trim to LTS only', 'O keep the full matrix and accept longer CI'],
    'ann_b': ['Q y p :: Want me to use a different Node version set or OS image?'],
  },
  {
    'n': 143,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Index on `(org_id, created_at)` is ready in a migration. Prod EXPLAIN still shows seq scan on the hot path.\n\nShall I `CREATE INDEX CONCURRENTLY` now or wait for the next blue/green?',
    'text_b': 'Index on `(org_id, created_at)` is ready in a migration. Prod EXPLAIN still shows seq scan on the hot path.\n\nShall I use a different index name or column order?',
    'ann_a': ['Q e p :: Shall I `CREATE INDEX CONCURRENTLY` now or wait for the next blue/green?', 'O `CREATE INDEX CONCURRENTLY` now', 'O wait for the next blue/green'],
    'ann_b': ['Q y p :: Shall I use a different index name or column order?'],
  },
  {
    'n': 144,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'I finished the exploratory pass and stopped before writing files.\n\ni18n keys for the checkout flow are in `en.json`. French is empty.\n\nWant a machine-translated draft or a English-only freeze with TODO comments?',
    'text_b': 'I finished the exploratory pass and stopped before writing files.\n\ni18n keys for the checkout flow are in `en.json`. French is empty.\n\nWant a different locale code or key naming scheme?',
    'ann_a': ['Q e p :: Want a machine-translated draft or a English-only freeze with TODO comments?', 'O a machine-translated draft', 'O a English-only freeze with TODO comments'],
    'ann_b': ['Q y p :: Want a different locale code or key naming scheme?'],
  },
  {
    'n': 145,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Oauth callback now validates `state`. Refresh tokens still land in localStorage.\n\nWould you like me to move them to httpOnly cookies or document the XSS tradeoff?',
    'text_b': 'Oauth callback now validates `state`. Refresh tokens still land in localStorage.\n\nWould you like me to use a different cookie name or SameSite mode?',
    'ann_a': ['Q e p :: Would you like me to move them to httpOnly cookies or document the XSS tradeoff?', 'O move them to httpOnly cookies', 'O document the XSS tradeoff'],
    'ann_b': ['Q y p :: Would you like me to use a different cookie name or SameSite mode?'],
  },
  {
    'n': 146,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Patch applied. Summary:\n\n- `RateLimiter` uses token bucket\n- burst=20, refill=5/s\n- 429 body includes `Retry-After`\n\nWant a load-test script next or a Mermaid sequence for the middleware?',
    'text_b': 'Patch applied. Summary:\n\n- `RateLimiter` uses token bucket\n- burst=20, refill=5/s\n- 429 body includes `Retry-After`\n\nWant a different burst size or refill rate?',
    'ann_a': ['Q e p :: Want a load-test script next or a Mermaid sequence for the middleware?', 'O a load-test script next', 'O a Mermaid sequence for the middleware'],
    'ann_b': ['Q y p :: Want a different burst size or refill rate?'],
  },
  {
    'n': 147,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Snippet of the current config:\n\n[CODE]\n\n`git bisect` landed on `c3f901a` (formatter config). Prefer I revert that commit or cherry-pick the formatter fix onto a clean base?',
    'text_b': 'Snippet of the current config:\n\n[CODE]\n\n`git bisect` landed on `c3f901a` (formatter config). Prefer I use a different bisect start or end SHA?',
    'ann_a': ['Q e p :: Prefer I revert that commit or cherry-pick the formatter fix onto a clean base?', 'O revert that commit', 'O cherry-pick the formatter fix onto a clean base'],
    'ann_b': ['Q y p :: Prefer I use a different bisect start or end SHA?'],
  },
  {
    'n': 148,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'The badge shows `!` in amber when the build is flaky. Design asked for stronger emphasis.\n\nWant the `!` indicator to become a solid red chip or a tooltip with the flake count?',
    'text_b': 'The badge shows `!` in amber when the build is flaky. Design asked for stronger emphasis.\n\nWant the `!` indicator to use a different color or label?',
    'ann_a': ['Q e p :: Want the `!` indicator to become a solid red chip or a tooltip with the flake count?', 'O a solid red chip', 'O a tooltip with the flake count'],
    'ann_b': ['Q y p :: Want the `!` indicator to use a different color or label?'],
  },
  {
    'n': 149,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Kafka consumer lag spiked to 40k on `orders`. Shall I scale the consumer group or pause producers while we drain?',
    'text_b': 'Kafka consumer lag spiked to 40k on `orders`. Shall I use a different consumer group id or max.poll.records?',
    'ann_a': ['Q e p :: Shall I scale the consumer group or pause producers while we drain?', 'O scale the consumer group', 'O pause producers while we drain'],
    'ann_b': ['Q y p :: Shall I use a different consumer group id or max.poll.records?'],
  },
  {
    'n': 150,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nAPI docs at [URL] are stale vs the OpenAPI file. Want me to regenerate from the spec or hand-edit the getting-started page?',
    'text_b': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nAPI docs at [URL] are stale vs the OpenAPI file. Want me to use a different docs theme or base path?',
    'ann_a': ['Q e p :: Want me to regenerate from the spec or hand-edit the getting-started page?', 'O regenerate from the spec', 'O hand-edit the getting-started page'],
    'ann_b': ['Q y p :: Want me to use a different docs theme or base path?'],
  },
  {
    'n': 151,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Vitest watch mode is hanging on file deletes under `tmp/`.\n\nWant me to exclude that glob from the watcher or switch the suite to run once in CI mode?',
    'text_b': 'Vitest watch mode is hanging on file deletes under `tmp/`.\n\nWant me to use a different watch ignore glob or poll interval?',
    'ann_a': ['Q e p :: Want me to exclude that glob from the watcher or switch the suite to run once in CI mode?', 'O exclude that glob from the watcher', 'O switch the suite to run once in CI mode'],
    'ann_b': ['Q y p :: Want me to use a different watch ignore glob or poll interval?'],
  },
  {
    'n': 152,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Signed the release with the staging key by mistake. Prefer I yank `0.3.0` and cut `0.3.1` or re-sign in place if the registry allows?',
    'text_b': 'Signed the release with the staging key by mistake. Prefer I use a different tag name or signature algorithm?',
    'ann_a': ['Q e p :: Prefer I yank `0.3.0` and cut `0.3.1` or re-sign in place if the registry allows?', 'O yank `0.3.0` and cut `0.3.1`', 'O re-sign in place if the registry allows'],
    'ann_b': ['Q y p :: Prefer I use a different tag name or signature algorithm?'],
  },
  {
    'n': 153,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Diff against HEAD is ready in the index; nothing pushed.\n\nCSS grid for the dashboard cards wraps awkwardly at 900px.\n\nShall I add a two-column breakpoint or collapse to a single stack earlier?',
    'text_b': 'Diff against HEAD is ready in the index; nothing pushed.\n\nCSS grid for the dashboard cards wraps awkwardly at 900px.\n\nShall I use a different breakpoint width or gap size?',
    'ann_a': ['Q e p :: Shall I add a two-column breakpoint or collapse to a single stack earlier?', 'O add a two-column breakpoint', 'O collapse to a single stack earlier'],
    'ann_b': ['Q y p :: Shall I use a different breakpoint width or gap size?'],
  },
  {
    'n': 154,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Seed script populates 50 demo orgs. Local Postgres is fine; the shared staging DB will bloat.\n\nDo you want me to gate seeds behind `SEED_DEMO=1` or shrink the default set to 5?',
    'text_b': 'Seed script populates 50 demo orgs. Local Postgres is fine; the shared staging DB will bloat.\n\nDo you want me to use a different seed count or fixture name prefix?',
    'ann_a': ['Q e p :: Do you want me to gate seeds behind `SEED_DEMO=1` or shrink the default set to 5?', 'O gate seeds behind `SEED_DEMO=1`', 'O shrink the default set to 5'],
    'ann_b': ['Q y p :: Do you want me to use a different seed count or fixture name prefix?'],
  },
  {
    'n': 155,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Cloudflare page rule for `/assets/*` is caching HTML by accident. Want a purge of that prefix or a rule rewrite that caches only hashed files?',
    'text_b': 'Cloudflare page rule for `/assets/*` is caching HTML by accident. Want a different cache TTL or edge location set?',
    'ann_a': ['Q e p :: Want a purge of that prefix or a rule rewrite that caches only hashed files?', 'O a purge of that prefix', 'O a rule rewrite that caches only hashed files'],
    'ann_b': ['Q y p :: Want a different cache TTL or edge location set?'],
  },
  {
    'n': 156,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'I finished the exploratory pass and stopped before writing files.\n\nRustc clippy is noisy on `too_many_arguments` in the CLI parser.\n\nWould you rather me refactor into a config struct or allowlist that lint for the binary crate?',
    'text_b': 'I finished the exploratory pass and stopped before writing files.\n\nRustc clippy is noisy on `too_many_arguments` in the CLI parser.\n\nWould you rather me use a different lint level or allowlist scope?',
    'ann_a': ['Q e p :: Would you rather me refactor into a config struct or allowlist that lint for the binary crate?', 'O refactor into a config struct', 'O allowlist that lint for the binary crate'],
    'ann_b': ['Q y p :: Would you rather me use a different lint level or allowlist scope?'],
  },
  {
    'n': 157,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'GraphQL schema added `Viewer.permissions`. Clients still query the old `role` field.\n\nReady to deprecate `role` with a sunset date or keep both fields indefinitely?',
    'text_b': 'GraphQL schema added `Viewer.permissions`. Clients still query the old `role` field.\n\nReady to use a different deprecation reason or sunset date format?',
    'ann_a': ['Q e p :: Ready to deprecate `role` with a sunset date or keep both fields indefinitely?', 'O deprecate `role` with a sunset date', 'O keep both fields indefinitely'],
    'ann_b': ['Q y p :: Ready to use a different deprecation reason or sunset date format?'],
  },
  {
    'n': 158,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Playwright trace for the flake is at `test-results/trace.zip`.\n\nWant me to upload it as a CI artifact or walk through the failing step in chat?',
    'text_b': 'Playwright trace for the flake is at `test-results/trace.zip`.\n\nWant me to use a different artifact name or retention?',
    'ann_a': ['Q e p :: Want me to upload it as a CI artifact or walk through the failing step in chat?', 'O upload it as a CI artifact', 'O walk through the failing step in chat'],
    'ann_b': ['Q y p :: Want me to use a different artifact name or retention?'],
  },
  {
    'n': 159,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Snippet of the current config:\n\n[CODE]\n\nMakefile target `proto` regenerates stubs into `gen/`. Checked-in stubs drifted.\n\nShall I commit the regen or add a CI check that fails on drift?',
    'text_b': 'Snippet of the current config:\n\n[CODE]\n\nMakefile target `proto` regenerates stubs into `gen/`. Checked-in stubs drifted.\n\nShall I use a different output directory or plugin version?',
    'ann_a': ['Q e p :: Shall I commit the regen or add a CI check that fails on drift?', 'O commit the regen', 'O add a CI check that fails on drift'],
    'ann_b': ['Q y p :: Shall I use a different output directory or plugin version?'],
  },
  {
    'n': 160,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Sidebar collapse icon is a chevron; design system wants a hamburger on mobile only.\n\nPrefer I swap the mobile icon or keep one icon everywhere?',
    'text_b': 'Sidebar collapse icon is a chevron; design system wants a hamburger on mobile only.\n\nPrefer I use a different icon size or stroke weight?',
    'ann_a': ['Q e p :: Prefer I swap the mobile icon or keep one icon everywhere?', 'O swap the mobile icon', 'O keep one icon everywhere'],
    'ann_b': ['Q y p :: Prefer I use a different icon size or stroke weight?'],
  },
  {
    'n': 161,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'BigQuery job `daily_rollup` scanned 4.2TB. Want a dry-run cost estimate next or a partitioned rewrite of the SQL?',
    'text_b': 'BigQuery job `daily_rollup` scanned 4.2TB. Want a different destination dataset or table suffix?',
    'ann_a': ['Q e p :: Want a dry-run cost estimate next or a partitioned rewrite of the SQL?', 'O a dry-run cost estimate next', 'O a partitioned rewrite of the SQL'],
    'ann_b': ['Q y p :: Want a different destination dataset or table suffix?'],
  },
  {
    'n': 162,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nEnv example lists `DATABASE_URL` but omits `REDIS_URL`. Docs mention both.\n\nDo you want me to sync `.env.example` or update the docs to match the code?',
    'text_b': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nEnv example lists `DATABASE_URL` but omits `REDIS_URL`. Docs mention both.\n\nDo you want me to use a different env var name or default value?',
    'ann_a': ['Q e p :: Do you want me to sync `.env.example` or update the docs to match the code?', 'O sync `.env.example`', 'O update the docs to match the code'],
    'ann_b': ['Q y p :: Do you want me to use a different env var name or default value?'],
  },
  {
    'n': 163,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Crash loop on the worker:\n\n[CODE]\nError: ECONNREFUSED 127.0.0.1:6379\n[/CODE]\n\nWant me to point it at the compose Redis service or add a startup retry with backoff?',
    'text_b': 'Crash loop on the worker:\n\n[CODE]\nError: ECONNREFUSED 127.0.0.1:6379\n[/CODE]\n\nWant me to use a different Redis host or port?',
    'ann_a': ['Q e p :: Want me to point it at the compose Redis service or add a startup retry with backoff?', 'O point it at the compose Redis service', 'O add a startup retry with backoff'],
    'ann_b': ['Q y p :: Want me to use a different Redis host or port?'],
  },
  {
    'n': 164,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'PR description is empty. I have the commit list ready.\n\nWould you like me to draft the PR body or paste a checklist template only?',
    'text_b': 'PR description is empty. I have the commit list ready.\n\nWould you like me to use a different PR template or label set?',
    'ann_a': ['Q e p :: Would you like me to draft the PR body or paste a checklist template only?', 'O draft the PR body', 'O paste a checklist template only'],
    'ann_b': ['Q y p :: Would you like me to use a different PR template or label set?'],
  },
  {
    'n': 165,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Diff against HEAD is ready in the index; nothing pushed.\n\nTailwind purge missed the dynamically built `bg-${tone}-500` classes.\n\nShall I safelist those tones or rewrite to static class maps?',
    'text_b': 'Diff against HEAD is ready in the index; nothing pushed.\n\nTailwind purge missed the dynamically built `bg-${tone}-500` classes.\n\nShall I use a different safelist pattern or content glob?',
    'ann_a': ['Q e p :: Shall I safelist those tones or rewrite to static class maps?', 'O safelist those tones', 'O rewrite to static class maps'],
    'ann_b': ['Q y p :: Shall I use a different safelist pattern or content glob?'],
  },
  {
    'n': 166,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Nightly backup landed in `s3://backups-staging/…` (placeholder bucket). Want a restore drill script or just the inventory listing?',
    'text_b': 'Nightly backup landed in `s3://backups-staging/…` (placeholder bucket). Want a different backup prefix or retention count?',
    'ann_a': ['Q e p :: Want a restore drill script or just the inventory listing?', 'O a restore drill script', 'O just the inventory listing'],
    'ann_b': ['Q y p :: Want a different backup prefix or retention count?'],
  },
  {
    'n': 167,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Hypothesis found a counterexample in `normalize_path` for `//./`.\n\nReady for me to harden the normalizer or mark the property test `@xfail` until Monday?',
    'text_b': 'Hypothesis found a counterexample in `normalize_path` for `//./`.\n\nReady for me to use a different Hypothesis profile or max_examples?',
    'ann_a': ['Q e p :: Ready for me to harden the normalizer or mark the property test `@xfail` until Monday?', 'O harden the normalizer', 'O mark the property test `@xfail` until Monday'],
    'ann_b': ['Q y p :: Ready for me to use a different Hypothesis profile or max_examples?'],
  },
  {
    'n': 168,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'I finished the exploratory pass and stopped before writing files.\n\nWebSocket reconnect storms after deploys. Prefer I add jittered backoff or force a full page reload on protocol mismatch?',
    'text_b': 'I finished the exploratory pass and stopped before writing files.\n\nWebSocket reconnect storms after deploys. Prefer I use a different backoff base or max delay?',
    'ann_a': ['Q e p :: Prefer I add jittered backoff or force a full page reload on protocol mismatch?', 'O add jittered backoff', 'O force a full page reload on protocol mismatch'],
    'ann_b': ['Q y p :: Prefer I use a different backoff base or max delay?'],
  },
  {
    'n': 169,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Cargo feature `experimental-simd` compiles on nightly only. Want me to gate it behind `cfg(nightly)` or drop the feature from the default matrix?',
    'text_b': 'Cargo feature `experimental-simd` compiles on nightly only. Want me to use a different feature name or rustc channel pin?',
    'ann_a': ['Q e p :: Want me to gate it behind `cfg(nightly)` or drop the feature from the default matrix?', 'O gate it behind `cfg(nightly)`', 'O drop the feature from the default matrix'],
    'ann_b': ['Q y p :: Want me to use a different feature name or rustc channel pin?'],
  },
  {
    'n': 170,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Onboarding checklist in the README is outdated (still mentions Heroku).\n\nDo you want me to rewrite that section for Fly.io or move onboarding into a dedicated `docs/onboarding.md`?',
    'text_b': 'Onboarding checklist in the README is outdated (still mentions Heroku).\n\nDo you want me to use a different host name or checklist length?',
    'ann_a': ['Q e p :: Do you want me to rewrite that section for Fly.io or move onboarding into a dedicated `docs/onboarding.md`?', 'O rewrite that section for Fly.io', 'O move onboarding into a dedicated `docs/onboarding.md`'],
    'ann_b': ['Q y p :: Do you want me to use a different host name or checklist length?'],
  },
  {
    'n': 171,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Snippet of the current config:\n\n[CODE]\n\nProgress so far:\n\n1. Extracted `AuthContext`\n2. Wired provider in `App.tsx`\n3. Left legacy `getUser()` shim\n\nWant me to delete the shim now or keep it through the next release?',
    'text_b': 'Snippet of the current config:\n\n[CODE]\n\nProgress so far:\n\n1. Extracted `AuthContext`\n2. Wired provider in `App.tsx`\n3. Left legacy `getUser()` shim\n\nWant me to use a different context displayName or default value?',
    'ann_a': ['Q e p :: Want me to delete the shim now or keep it through the next release?', 'O delete the shim now', 'O keep it through the next release'],
    'ann_b': ['Q y p :: Want me to use a different context displayName or default value?'],
  },
  {
    'n': 172,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': '`eslint-plugin-import` flags a cycle between `models` and `services`. Shall I break it with a types-only module or ignore that path for now?',
    'text_b': '`eslint-plugin-import` flags a cycle between `models` and `services`. Shall I use a different rule severity or ignore comment style?',
    'ann_a': ['Q e p :: Shall I break it with a types-only module or ignore that path for now?', 'O break it with a types-only module', 'O ignore that path for now'],
    'ann_b': ['Q y p :: Shall I use a different rule severity or ignore comment style?'],
  },
  {
    'n': 173,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Image CDN URL builder hardcodes `w=800`. Mobile still downloads desktop sizes.\n\nWould you rather me add responsive `srcset` or a client-side resize param?',
    'text_b': 'Image CDN URL builder hardcodes `w=800`. Mobile still downloads desktop sizes.\n\nWould you rather me use a different default width or quality?',
    'ann_a': ['Q e p :: Would you rather me add responsive `srcset` or a client-side resize param?', 'O add responsive `srcset`', 'O a client-side resize param'],
    'ann_b': ['Q y p :: Would you rather me use a different default width or quality?'],
  },
  {
    'n': 174,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nTerraform state unlock is needed after the cancelled apply. Want me to run `force-unlock` or leave instructions for you?',
    'text_b': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nTerraform state unlock is needed after the cancelled apply. Want me to use a different state backend or lock id?',
    'ann_a': ['Q e p :: Want me to run `force-unlock` or leave instructions for you?', 'O run `force-unlock`', 'O leave instructions for you'],
    'ann_b': ['Q y p :: Want me to use a different state backend or lock id?'],
  },
  {
    'n': 175,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Coverage HTML report is in `coverage/index.html`. Prefer I open a summary table in chat or attach the lcov file?',
    'text_b': 'Coverage HTML report is in `coverage/index.html`. Prefer I use a different report directory or watermark threshold?',
    'ann_a': ['Q e p :: Prefer I open a summary table in chat or attach the lcov file?', 'O open a summary table in chat', 'O attach the lcov file'],
    'ann_b': ['Q y p :: Prefer I use a different report directory or watermark threshold?'],
  },
  {
    'n': 176,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Modal animation uses `ease-out` 200ms. Motion-sensitive users may want less.\n\nWant me to respect `prefers-reduced-motion` or remove the animation entirely?',
    'text_b': 'Modal animation uses `ease-out` 200ms. Motion-sensitive users may want less.\n\nWant me to use a different duration or easing curve?',
    'ann_a': ['Q e p :: Want me to respect `prefers-reduced-motion` or remove the animation entirely?', 'O respect `prefers-reduced-motion`', 'O remove the animation entirely'],
    'ann_b': ['Q y p :: Want me to use a different duration or easing curve?'],
  },
  {
    'n': 177,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Diff against HEAD is ready in the index; nothing pushed.\n\ndbt model `fct_orders` failed the freshness check. Shall I widen the SLA window or page on-call from the freshness job?',
    'text_b': 'Diff against HEAD is ready in the index; nothing pushed.\n\ndbt model `fct_orders` failed the freshness check. Shall I use a different freshness warn or error threshold?',
    'ann_a': ['Q e p :: Shall I widen the SLA window or page on-call from the freshness job?', 'O widen the SLA window', 'O page on-call from the freshness job'],
    'ann_b': ['Q y p :: Shall I use a different freshness warn or error threshold?'],
  },
  {
    'n': 178,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Commit message convention is Conventional Commits, but this branch mixes styles.\n\nDo you want me to rewrite history with consistent subjects or leave a note for the squash merge?',
    'text_b': 'Commit message convention is Conventional Commits, but this branch mixes styles.\n\nDo you want me to use a different commit type prefix or scope?',
    'ann_a': ['Q e p :: Do you want me to rewrite history with consistent subjects or leave a note for the squash merge?', 'O rewrite history with consistent subjects', 'O leave a note for the squash merge'],
    'ann_b': ['Q y p :: Do you want me to use a different commit type prefix or scope?'],
  },
  {
    'n': 179,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Service worker caches `app-shell` forever. After deploys users see stale chrome.\n\nReady to bump the cache version or switch to network-first for HTML?',
    'text_b': 'Service worker caches `app-shell` forever. After deploys users see stale chrome.\n\nReady to use a different cache name or max age?',
    'ann_a': ['Q e p :: Ready to bump the cache version or switch to network-first for HTML?', 'O bump the cache version', 'O switch to network-first for HTML'],
    'ann_b': ['Q y p :: Ready to use a different cache name or max age?'],
  },
  {
    'n': 180,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'I finished the exploratory pass and stopped before writing files.\n\nLog sample (redacted):\n\n[CODE]\nlevel=error msg="token expired" code=401 path=/v1/me\n[/CODE]\n\nWant me to auto-refresh on 401 or surface a re-login modal?',
    'text_b': 'I finished the exploratory pass and stopped before writing files.\n\nLog sample (redacted):\n\n[CODE]\nlevel=error msg="token expired" code=401 path=/v1/me\n[/CODE]\n\nWant me to use a different log level or field name?',
    'ann_a': ['Q e p :: Want me to auto-refresh on 401 or surface a re-login modal?', 'O auto-refresh on 401', 'O surface a re-login modal'],
    'ann_b': ['Q y p :: Want me to use a different log level or field name?'],
  },
  {
    'n': 181,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'kustomize overlay for staging duplicates the prod probe paths. Prefer I share a base probe patch or keep overlays fully explicit?',
    'text_b': 'kustomize overlay for staging duplicates the prod probe paths. Prefer I use a different probe path or initialDelaySeconds?',
    'ann_a': ['Q e p :: Prefer I share a base probe patch or keep overlays fully explicit?', 'O share a base probe patch', 'O keep overlays fully explicit'],
    'ann_b': ['Q y p :: Prefer I use a different probe path or initialDelaySeconds?'],
  },
  {
    'n': 182,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Figma export of the icon set is SVG; the app expects React components.\n\nWant an SVGR transform pass or a one-off hand conversion of the three icons we need?',
    'text_b': 'Figma export of the icon set is SVG; the app expects React components.\n\nWant a different icon filename or export size?',
    'ann_a': ['Q e p :: Want an SVGR transform pass or a one-off hand conversion of the three icons we need?', 'O an SVGR transform pass', 'O a one-off hand conversion of the three icons we need'],
    'ann_b': ['Q y p :: Want a different icon filename or export size?'],
  },
  {
    'n': 183,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Snippet of the current config:\n\n[CODE]\n\npytest-xdist shards oddly with `file` scope — one worker idle. Shall I switch to `loadscope` or drop xdist for this suite?',
    'text_b': 'Snippet of the current config:\n\n[CODE]\n\npytest-xdist shards oddly with `file` scope — one worker idle. Shall I use a different worker count or dist mode?',
    'ann_a': ['Q e p :: Shall I switch to `loadscope` or drop xdist for this suite?', 'O switch to `loadscope`', 'O drop xdist for this suite'],
    'ann_b': ['Q y p :: Shall I use a different worker count or dist mode?'],
  },
  {
    'n': 184,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'DNS cutover checklist is ready. Want me to lower TTLs now or only document the cutover steps?',
    'text_b': 'DNS cutover checklist is ready. Want me to use a different TTL value or record name?',
    'ann_a': ['Q e p :: Want me to lower TTLs now or only document the cutover steps?', 'O lower TTLs now', 'O only document the cutover steps'],
    'ann_b': ['Q y p :: Want me to use a different TTL value or record name?'],
  },
  {
    'n': 185,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Table sort defaults to `created_at` desc. Product asked for last-activity.\n\nWould you like me to change the default sort or add a visible sort control?',
    'text_b': 'Table sort defaults to `created_at` desc. Product asked for last-activity.\n\nWould you like me to use a different default column or sort direction?',
    'ann_a': ['Q e p :: Would you like me to change the default sort or add a visible sort control?', 'O change the default sort', 'O add a visible sort control'],
    'ann_b': ['Q y p :: Would you like me to use a different default column or sort direction?'],
  },
  {
    'n': 186,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nSpark job spills to disk on the join. Ready to broadcast the dimension table or raise executor memory?',
    'text_b': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nSpark job spills to disk on the join. Ready to use a different shuffle partition count or executor memory?',
    'ann_a': ['Q e p :: Ready to broadcast the dimension table or raise executor memory?', 'O broadcast the dimension table', 'O raise executor memory'],
    'ann_b': ['Q y p :: Ready to use a different shuffle partition count or executor memory?'],
  },
  {
    'n': 187,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'ADR-0012 approved the move to edge caching. Implementation notes are still in a Notion dump.\n\nWant me to port them into `docs/adr/0012-impl.md` or leave a link stub?',
    'text_b': 'ADR-0012 approved the move to edge caching. Implementation notes are still in a Notion dump.\n\nWant me to use a different ADR filename or status label?',
    'ann_a': ['Q e p :: Want me to port them into `docs/adr/0012-impl.md` or leave a link stub?', 'O port them into `docs/adr/0012-impl.md`', 'O leave a link stub'],
    'ann_b': ['Q y p :: Want me to use a different ADR filename or status label?'],
  },
  {
    'n': 188,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'gh Actions `deploy` job needs approval. Shall I add an environment protection rule or keep manual `workflow_dispatch` only?',
    'text_b': 'gh Actions `deploy` job needs approval. Shall I use a different environment name or reviewer team?',
    'ann_a': ['Q e p :: Shall I add an environment protection rule or keep manual `workflow_dispatch` only?', 'O add an environment protection rule', 'O keep manual `workflow_dispatch` only'],
    'ann_b': ['Q y p :: Shall I use a different environment name or reviewer team?'],
  },
  {
    'n': 189,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Diff against HEAD is ready in the index; nothing pushed.\n\nHover card clips under the sticky header. Prefer I raise the z-index or flip the card below the trigger?',
    'text_b': 'Diff against HEAD is ready in the index; nothing pushed.\n\nHover card clips under the sticky header. Prefer I use a different z-index or offset?',
    'ann_a': ['Q e p :: Prefer I raise the z-index or flip the card below the trigger?', 'O raise the z-index', 'O flip the card below the trigger'],
    'ann_b': ['Q y p :: Prefer I use a different z-index or offset?'],
  },
  {
    'n': 190,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'CSV dump includes PII columns we should not share. Want a redacted export script or a column allowlist in the query?',
    'text_b': 'CSV dump includes PII columns we should not share. Want a different output delimiter or encoding?',
    'ann_a': ['Q e p :: Want a redacted export script or a column allowlist in the query?', 'O a redacted export script', 'O a column allowlist in the query'],
    'ann_b': ['Q y p :: Want a different output delimiter or encoding?'],
  },
  {
    'n': 191,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'go.mod still requires Go 1.21; CI image is 1.22. Do you want me to bump `go` in go.mod or pin the CI image back?',
    'text_b': 'go.mod still requires Go 1.21; CI image is 1.22. Do you want me to use a different Go version or module path?',
    'ann_a': ['Q e p :: Do you want me to bump `go` in go.mod or pin the CI image back?', 'O bump `go` in go.mod', 'O pin the CI image back'],
    'ann_b': ['Q y p :: Do you want me to use a different Go version or module path?'],
  },
  {
    'n': 192,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'I finished the exploratory pass and stopped before writing files.\n\nNotebook cell timings:\n\n- load parquet: 4.1s\n- feature eng: 12.8s\n- fit: 41s\n\nWant a profiled rewrite of feature eng or a smaller sample for interactive use?',
    'text_b': 'I finished the exploratory pass and stopped before writing files.\n\nNotebook cell timings:\n\n- load parquet: 4.1s\n- feature eng: 12.8s\n- fit: 41s\n\nWant a different sample fraction or random seed?',
    'ann_a': ['Q e p :: Want a profiled rewrite of feature eng or a smaller sample for interactive use?', 'O a profiled rewrite of feature eng', 'O a smaller sample for interactive use'],
    'ann_b': ['Q y p :: Want a different sample fraction or random seed?'],
  },
  {
    'n': 193,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Alertmanager routes `team-payments` to Slack. Pager is quiet after hours.\n\nWould you rather me add a night pager route or mute non-critical severities overnight?',
    'text_b': 'Alertmanager routes `team-payments` to Slack. Pager is quiet after hours.\n\nWould you rather me use a different Slack channel or severity filter?',
    'ann_a': ['Q e p :: Would you rather me add a night pager route or mute non-critical severities overnight?', 'O add a night pager route', 'O mute non-critical severities overnight'],
    'ann_b': ['Q y p :: Would you rather me use a different Slack channel or severity filter?'],
  },
  {
    'n': 194,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'TypeORM entity `Invoice` still uses `synchronize: true` in dev. Shall I turn that off and rely on migrations or keep sync for local only?',
    'text_b': 'TypeORM entity `Invoice` still uses `synchronize: true` in dev. Shall I use a different entity table name or schema?',
    'ann_a': ['Q e p :: Shall I turn that off and rely on migrations or keep sync for local only?', 'O turn that off and rely on migrations', 'O keep sync for local only'],
    'ann_b': ['Q y p :: Shall I use a different entity table name or schema?'],
  },
  {
    'n': 195,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Snippet of the current config:\n\n[CODE]\n\nAccessibility audit: button lacks an accessible name (icon-only).\n\nWant me to add `aria-label` or visible text beside the icon?',
    'text_b': 'Snippet of the current config:\n\n[CODE]\n\nAccessibility audit: button lacks an accessible name (icon-only).\n\nWant me to use a different aria-label wording or tooltip text?',
    'ann_a': ['Q e p :: Want me to add `aria-label` or visible text beside the icon?', 'O add `aria-label`', 'O visible text beside the icon'],
    'ann_b': ['Q y p :: Want me to use a different aria-label wording or tooltip text?'],
  },
  {
    'n': 196,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': "Cherry-pick of `hotfix/timeout` onto `release/2.4` conflicts in `client.ts`.\n\nPrefer I resolve keeping release's dial-timeout or take the hotfix's cancel-token approach?",
    'text_b': 'Cherry-pick of `hotfix/timeout` onto `release/2.4` conflicts in `client.ts`.\n\nPrefer I use a different conflict marker style or merge strategy?',
    'ann_a': ["Q e p :: Prefer I resolve keeping release's dial-timeout or take the hotfix's cancel-token approach?", "O resolve keeping release's dial-timeout", "O take the hotfix's cancel-token approach"],
    'ann_b': ['Q y p :: Prefer I use a different conflict marker style or merge strategy?'],
  },
  {
    'n': 197,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Sentry project still points at the old DSN in `.env.production.example`.\n\nDo you want me to update the example env or add a startup warning when DSN looks stale?',
    'text_b': 'Sentry project still points at the old DSN in `.env.production.example`.\n\nDo you want me to use a different sample rate or environment tag?',
    'ann_a': ['Q e p :: Do you want me to update the example env or add a startup warning when DSN looks stale?', 'O update the example env', 'O add a startup warning when DSN looks stale'],
    'ann_b': ['Q y p :: Do you want me to use a different sample rate or environment tag?'],
  },
  {
    'n': 198,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nWASM build of the tokenizer is 1.8MB. Want a size breakdown with `twiggy` or a streaming load sketch?',
    'text_b': 'Reproduction steps that worked here:\n1. restart the service\n2. hit the flaky endpoint twice\n3. watch the structured log\n\nWASM build of the tokenizer is 1.8MB. Want a different optimization level or target features?',
    'ann_a': ['Q e p :: Want a size breakdown with `twiggy` or a streaming load sketch?', 'O a size breakdown with `twiggy`', 'O a streaming load sketch'],
    'ann_b': ['Q y p :: Want a different optimization level or target features?'],
  },
  {
    'n': 199,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'Legacy `Makefile` target `test` runs everything serially. Ready to parallelize with `-j` or split into `test-unit` / `test-integration`?',
    'text_b': 'Legacy `Makefile` target `test` runs everything serially. Ready to use a different make job count or target name?',
    'ann_a': ['Q e p :: Ready to parallelize with `-j` or split into `test-unit` / `test-integration`?', 'O parallelize with `-j`', 'O split into `test-unit` / `test-integration`'],
    'ann_b': ['Q y p :: Ready to use a different make job count or target name?'],
  },
  {
    'n': 200,
    'boundary': 'yes_no/either_or',
    'note_a': 'two deliverables -> either_or',
    'note_b': 'one change several attributes -> yes_no',
    'text_a': 'All green on the refactor. Files touched: `router.ts`, `auth.ts`, `session.ts`.\n\nWant a unified diff of the three files or a narrated walkthrough of the auth path?',
    'text_b': 'All green on the refactor. Files touched: `router.ts`, `auth.ts`, `session.ts`.\n\nWant a different diff context size or file order?',
    'ann_a': ['Q e p :: Want a unified diff of the three files or a narrated walkthrough of the auth path?', 'O a unified diff of the three files', 'O a narrated walkthrough of the auth path'],
    'ann_b': ['Q y p :: Want a different diff context size or file order?'],
  },
]
